var annotated_dup =
[
    [ "anonymous_namespace{free_list_allocator.cpp}", "namespaceanonymous__namespace_02free__list__allocator_8cpp_03.html", [
      [ "AllocationHeader", "structanonymous__namespace_02free__list__allocator_8cpp_03_1_1AllocationHeader.html", "structanonymous__namespace_02free__list__allocator_8cpp_03_1_1AllocationHeader" ]
    ] ],
    [ "anonymous_namespace{stacktrace.cpp}", "namespaceanonymous__namespace_02stacktrace_8cpp_03.html", [
      [ "CapturedFramesResult", "structanonymous__namespace_02stacktrace_8cpp_03_1_1CapturedFramesResult.html", "structanonymous__namespace_02stacktrace_8cpp_03_1_1CapturedFramesResult" ]
    ] ],
    [ "helios", "namespacehelios.html", [
      [ "app", "namespacehelios_1_1app.html", [
        [ "App", "classhelios_1_1app_1_1App.html", "classhelios_1_1app_1_1App" ],
        [ "AppExit", "structhelios_1_1app_1_1AppExit.html", "structhelios_1_1app_1_1AppExit" ],
        [ "DynamicPlugin", "classhelios_1_1app_1_1DynamicPlugin.html", "classhelios_1_1app_1_1DynamicPlugin" ],
        [ "DynamicPluginConfig", "structhelios_1_1app_1_1DynamicPluginConfig.html", "structhelios_1_1app_1_1DynamicPluginConfig" ],
        [ "Extract", "structhelios_1_1app_1_1Extract.html", "structhelios_1_1app_1_1Extract" ],
        [ "ExtractStage", "structhelios_1_1app_1_1ExtractStage.html", "structhelios_1_1app_1_1ExtractStage" ],
        [ "First", "structhelios_1_1app_1_1First.html", "structhelios_1_1app_1_1First" ],
        [ "FixedRunnerConfig", "structhelios_1_1app_1_1FixedRunnerConfig.html", "structhelios_1_1app_1_1FixedRunnerConfig" ],
        [ "Last", "structhelios_1_1app_1_1Last.html", "structhelios_1_1app_1_1Last" ],
        [ "MainStartup", "structhelios_1_1app_1_1MainStartup.html", "structhelios_1_1app_1_1MainStartup" ],
        [ "Plugin", "classhelios_1_1app_1_1Plugin.html", "classhelios_1_1app_1_1Plugin" ],
        [ "PluginTypeExport", "structhelios_1_1app_1_1PluginTypeExport.html", "structhelios_1_1app_1_1PluginTypeExport" ],
        [ "PostShutdown", "structhelios_1_1app_1_1PostShutdown.html", "structhelios_1_1app_1_1PostShutdown" ],
        [ "PostStartup", "structhelios_1_1app_1_1PostStartup.html", "structhelios_1_1app_1_1PostStartup" ],
        [ "PostUpdate", "structhelios_1_1app_1_1PostUpdate.html", "structhelios_1_1app_1_1PostUpdate" ],
        [ "PreShutdown", "structhelios_1_1app_1_1PreShutdown.html", "structhelios_1_1app_1_1PreShutdown" ],
        [ "PreStartup", "structhelios_1_1app_1_1PreStartup.html", "structhelios_1_1app_1_1PreStartup" ],
        [ "PreUpdate", "structhelios_1_1app_1_1PreUpdate.html", "structhelios_1_1app_1_1PreUpdate" ],
        [ "Scheduler", "classhelios_1_1app_1_1Scheduler.html", "classhelios_1_1app_1_1Scheduler" ],
        [ "Shutdown", "structhelios_1_1app_1_1Shutdown.html", "structhelios_1_1app_1_1Shutdown" ],
        [ "ShutdownStage", "structhelios_1_1app_1_1ShutdownStage.html", "structhelios_1_1app_1_1ShutdownStage" ],
        [ "Startup", "structhelios_1_1app_1_1Startup.html", "structhelios_1_1app_1_1Startup" ],
        [ "StartupStage", "structhelios_1_1app_1_1StartupStage.html", "structhelios_1_1app_1_1StartupStage" ],
        [ "SubApp", "classhelios_1_1app_1_1SubApp.html", "classhelios_1_1app_1_1SubApp" ],
        [ "Update", "structhelios_1_1app_1_1Update.html", "structhelios_1_1app_1_1Update" ],
        [ "UpdateStage", "structhelios_1_1app_1_1UpdateStage.html", "structhelios_1_1app_1_1UpdateStage" ]
      ] ],
      [ "async", "namespacehelios_1_1async.html", [
        [ "AsyncTask", "classhelios_1_1async_1_1AsyncTask.html", "classhelios_1_1async_1_1AsyncTask" ],
        [ "Executor", "classhelios_1_1async_1_1Executor.html", "classhelios_1_1async_1_1Executor" ],
        [ "Future", "classhelios_1_1async_1_1Future.html", "classhelios_1_1async_1_1Future" ],
        [ "SubTaskGraph", "classhelios_1_1async_1_1SubTaskGraph.html", "classhelios_1_1async_1_1SubTaskGraph" ],
        [ "Task", "classhelios_1_1async_1_1Task.html", "classhelios_1_1async_1_1Task" ],
        [ "TaskGraph", "classhelios_1_1async_1_1TaskGraph.html", "classhelios_1_1async_1_1TaskGraph" ]
      ] ],
      [ "container", "namespacehelios_1_1container.html", [
        [ "BasicStaticString", "classhelios_1_1container_1_1BasicStaticString.html", "classhelios_1_1container_1_1BasicStaticString" ],
        [ "CallableBufferArrayImpl", "classhelios_1_1container_1_1CallableBufferArrayImpl.html", "classhelios_1_1container_1_1CallableBufferArrayImpl" ],
        [ "CallableBufferImpl", "classhelios_1_1container_1_1CallableBufferImpl.html", "classhelios_1_1container_1_1CallableBufferImpl" ],
        [ "MultiTypeMap", "classhelios_1_1container_1_1MultiTypeMap.html", "classhelios_1_1container_1_1MultiTypeMap" ],
        [ "SparseSet", "classhelios_1_1container_1_1SparseSet.html", "classhelios_1_1container_1_1SparseSet" ],
        [ "TypedBuffer", "classhelios_1_1container_1_1TypedBuffer.html", "classhelios_1_1container_1_1TypedBuffer" ],
        [ "TypedBufferArray", "classhelios_1_1container_1_1TypedBufferArray.html", "classhelios_1_1container_1_1TypedBufferArray" ]
      ] ],
      [ "details", "namespacehelios_1_1details.html", [
        [ "FreeFunctionTraits", "structhelios_1_1details_1_1FreeFunctionTraits.html", null ],
        [ "FreeFunctionTraits< R(*)(Args...)>", "structhelios_1_1details_1_1FreeFunctionTraits_3_01R_07_5_08_07Args_8_8_8_08_4.html", "structhelios_1_1details_1_1FreeFunctionTraits_3_01R_07_5_08_07Args_8_8_8_08_4" ],
        [ "MemberFunctionTraits", "structhelios_1_1details_1_1MemberFunctionTraits.html", null ],
        [ "MemberFunctionTraits< R(C::*)(Args...) const >", "structhelios_1_1details_1_1MemberFunctionTraits_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01const_01_4.html", "structhelios_1_1details_1_1MemberFunctionTraits_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01const_01_4" ],
        [ "MemberFunctionTraits< R(C::*)(Args...)>", "structhelios_1_1details_1_1MemberFunctionTraits_3_01R_07C_1_1_5_08_07Args_8_8_8_08_4.html", "structhelios_1_1details_1_1MemberFunctionTraits_3_01R_07C_1_1_5_08_07Args_8_8_8_08_4" ],
        [ "TupleToFunctionSignature", "structhelios_1_1details_1_1TupleToFunctionSignature.html", null ],
        [ "TupleToFunctionSignature< std::tuple< R, Args... > >", "structhelios_1_1details_1_1TupleToFunctionSignature_3_01std_1_1tuple_3_01R_00_01Args_8_8_8_01_4_01_4.html", "structhelios_1_1details_1_1TupleToFunctionSignature_3_01std_1_1tuple_3_01R_00_01Args_8_8_8_01_4_01_4" ]
      ] ],
      [ "ecs", "namespacehelios_1_1ecs.html", [
        [ "anonymous_namespace{scheduler.cpp}", "namespacehelios_1_1ecs_1_1anonymous__namespace_02scheduler_8cpp_03.html", [
          [ "TopoNode", "structhelios_1_1ecs_1_1anonymous__namespace_02scheduler_8cpp_03_1_1TopoNode.html", "structhelios_1_1ecs_1_1anonymous__namespace_02scheduler_8cpp_03_1_1TopoNode" ]
        ] ],
        [ "details", "namespacehelios_1_1ecs_1_1details.html", [
          [ "AsyncMessageStorage", "classhelios_1_1ecs_1_1details_1_1AsyncMessageStorage.html", "classhelios_1_1ecs_1_1details_1_1AsyncMessageStorage" ],
          [ "MemberFnArgs", "structhelios_1_1ecs_1_1details_1_1MemberFnArgs.html", null ],
          [ "MemberFnArgs< R(*)(Args...)>", "structhelios_1_1ecs_1_1details_1_1MemberFnArgs_3_01R_07_5_08_07Args_8_8_8_08_4.html", "structhelios_1_1ecs_1_1details_1_1MemberFnArgs_3_01R_07_5_08_07Args_8_8_8_08_4" ],
          [ "MemberFnArgs< R(Args...)>", "structhelios_1_1ecs_1_1details_1_1MemberFnArgs_3_01R_07Args_8_8_8_08_4.html", "structhelios_1_1ecs_1_1details_1_1MemberFnArgs_3_01R_07Args_8_8_8_08_4" ],
          [ "MemberFnArgs< R(C::*)(Args...) const >", "structhelios_1_1ecs_1_1details_1_1MemberFnArgs_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01const_01_4.html", "structhelios_1_1ecs_1_1details_1_1MemberFnArgs_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01const_01_4" ],
          [ "MemberFnArgs< R(C::*)(Args...)>", "structhelios_1_1ecs_1_1details_1_1MemberFnArgs_3_01R_07C_1_1_5_08_07Args_8_8_8_08_4.html", "structhelios_1_1ecs_1_1details_1_1MemberFnArgs_3_01R_07C_1_1_5_08_07Args_8_8_8_08_4" ],
          [ "RegisterQueryAccess", "structhelios_1_1ecs_1_1details_1_1RegisterQueryAccess.html", null ],
          [ "RegisterQueryAccess< std::tuple< Cs... > >", "structhelios_1_1ecs_1_1details_1_1RegisterQueryAccess_3_01std_1_1tuple_3_01Cs_8_8_8_01_4_01_4.html", "structhelios_1_1ecs_1_1details_1_1RegisterQueryAccess_3_01std_1_1tuple_3_01Cs_8_8_8_01_4_01_4" ]
        ] ],
        [ "AccessPolicy", "classhelios_1_1ecs_1_1AccessPolicy.html", "classhelios_1_1ecs_1_1AccessPolicy" ],
        [ "AccessPolicyBuilder", "classhelios_1_1ecs_1_1AccessPolicyBuilder.html", "classhelios_1_1ecs_1_1AccessPolicyBuilder" ],
        [ "AddComponentsCmd", "classhelios_1_1ecs_1_1AddComponentsCmd.html", "classhelios_1_1ecs_1_1AddComponentsCmd" ],
        [ "Archetype", "classhelios_1_1ecs_1_1Archetype.html", "classhelios_1_1ecs_1_1Archetype" ],
        [ "ArchetypeId", "classhelios_1_1ecs_1_1ArchetypeId.html", "classhelios_1_1ecs_1_1ArchetypeId" ],
        [ "AsyncMessageQueue", "classhelios_1_1ecs_1_1AsyncMessageQueue.html", "classhelios_1_1ecs_1_1AsyncMessageQueue" ],
        [ "AsyncMessageReader", "classhelios_1_1ecs_1_1AsyncMessageReader.html", "classhelios_1_1ecs_1_1AsyncMessageReader" ],
        [ "AsyncMessageWrapper", "classhelios_1_1ecs_1_1AsyncMessageWrapper.html", "classhelios_1_1ecs_1_1AsyncMessageWrapper" ],
        [ "AsyncMessageWriter", "classhelios_1_1ecs_1_1AsyncMessageWriter.html", "classhelios_1_1ecs_1_1AsyncMessageWriter" ],
        [ "BasicMessageWriter", "classhelios_1_1ecs_1_1BasicMessageWriter.html", "classhelios_1_1ecs_1_1BasicMessageWriter" ],
        [ "BasicQuery", "classhelios_1_1ecs_1_1BasicQuery.html", "classhelios_1_1ecs_1_1BasicQuery" ],
        [ "BasicQueryIter", "classhelios_1_1ecs_1_1BasicQueryIter.html", "classhelios_1_1ecs_1_1BasicQueryIter" ],
        [ "BasicQueryWithEntity", "classhelios_1_1ecs_1_1BasicQueryWithEntity.html", "classhelios_1_1ecs_1_1BasicQueryWithEntity" ],
        [ "BasicQueryWithEntityIter", "classhelios_1_1ecs_1_1BasicQueryWithEntityIter.html", "classhelios_1_1ecs_1_1BasicQueryWithEntityIter" ],
        [ "ClearAllMessagesCmd", "structhelios_1_1ecs_1_1ClearAllMessagesCmd.html", "structhelios_1_1ecs_1_1ClearAllMessagesCmd" ],
        [ "ClearComponentsCmd", "classhelios_1_1ecs_1_1ClearComponentsCmd.html", "classhelios_1_1ecs_1_1ClearComponentsCmd" ],
        [ "ClearMessagesCmd", "structhelios_1_1ecs_1_1ClearMessagesCmd.html", "structhelios_1_1ecs_1_1ClearMessagesCmd" ],
        [ "CmdQueue", "classhelios_1_1ecs_1_1CmdQueue.html", "classhelios_1_1ecs_1_1CmdQueue" ],
        [ "Commands", "classhelios_1_1ecs_1_1Commands.html", "classhelios_1_1ecs_1_1Commands" ],
        [ "ComponentAddedMsg", "classhelios_1_1ecs_1_1ComponentAddedMsg.html", "classhelios_1_1ecs_1_1ComponentAddedMsg" ],
        [ "ComponentConflictInfo", "structhelios_1_1ecs_1_1ComponentConflictInfo.html", "structhelios_1_1ecs_1_1ComponentConflictInfo" ],
        [ "ComponentManager", "classhelios_1_1ecs_1_1ComponentManager.html", "classhelios_1_1ecs_1_1ComponentManager" ],
        [ "ComponentMetadata", "structhelios_1_1ecs_1_1ComponentMetadata.html", "structhelios_1_1ecs_1_1ComponentMetadata" ],
        [ "ComponentRemovedMsg", "classhelios_1_1ecs_1_1ComponentRemovedMsg.html", "classhelios_1_1ecs_1_1ComponentRemovedMsg" ],
        [ "ComponentsClearedMsg", "classhelios_1_1ecs_1_1ComponentsClearedMsg.html", "classhelios_1_1ecs_1_1ComponentsClearedMsg" ],
        [ "ComponentTraits", "structhelios_1_1ecs_1_1ComponentTraits.html", "structhelios_1_1ecs_1_1ComponentTraits" ],
        [ "ComponentTypeInfo", "classhelios_1_1ecs_1_1ComponentTypeInfo.html", "classhelios_1_1ecs_1_1ComponentTypeInfo" ],
        [ "CompositeSystemParam", "structhelios_1_1ecs_1_1CompositeSystemParam.html", "structhelios_1_1ecs_1_1CompositeSystemParam" ],
        [ "ConsumableMessageReader", "classhelios_1_1ecs_1_1ConsumableMessageReader.html", "classhelios_1_1ecs_1_1ConsumableMessageReader" ],
        [ "ConsumableMessageWrapper", "classhelios_1_1ecs_1_1ConsumableMessageWrapper.html", "classhelios_1_1ecs_1_1ConsumableMessageWrapper" ],
        [ "ConsumableMessageWrapperIter", "classhelios_1_1ecs_1_1ConsumableMessageWrapperIter.html", "classhelios_1_1ecs_1_1ConsumableMessageWrapperIter" ],
        [ "ConsumedMessagesRegistry", "classhelios_1_1ecs_1_1ConsumedMessagesRegistry.html", "classhelios_1_1ecs_1_1ConsumedMessagesRegistry" ],
        [ "Dag", "classhelios_1_1ecs_1_1Dag.html", "classhelios_1_1ecs_1_1Dag" ],
        [ "DagError", "structhelios_1_1ecs_1_1DagError.html", "structhelios_1_1ecs_1_1DagError" ],
        [ "DestroyEntitiesCmd", "classhelios_1_1ecs_1_1DestroyEntitiesCmd.html", "classhelios_1_1ecs_1_1DestroyEntitiesCmd" ],
        [ "DestroyEntityCmd", "classhelios_1_1ecs_1_1DestroyEntityCmd.html", "classhelios_1_1ecs_1_1DestroyEntityCmd" ],
        [ "Entity", "classhelios_1_1ecs_1_1Entity.html", "classhelios_1_1ecs_1_1Entity" ],
        [ "EntityAddedMsg", "classhelios_1_1ecs_1_1EntityAddedMsg.html", "classhelios_1_1ecs_1_1EntityAddedMsg" ],
        [ "EntityCmdBuffer", "classhelios_1_1ecs_1_1EntityCmdBuffer.html", "classhelios_1_1ecs_1_1EntityCmdBuffer" ],
        [ "EntityDestroyedMsg", "classhelios_1_1ecs_1_1EntityDestroyedMsg.html", "classhelios_1_1ecs_1_1EntityDestroyedMsg" ],
        [ "EntityManager", "classhelios_1_1ecs_1_1EntityManager.html", "classhelios_1_1ecs_1_1EntityManager" ],
        [ "Executor", "classhelios_1_1ecs_1_1Executor.html", "classhelios_1_1ecs_1_1Executor" ],
        [ "FunctionCmd", "classhelios_1_1ecs_1_1FunctionCmd.html", "classhelios_1_1ecs_1_1FunctionCmd" ],
        [ "InsertResourceCmd", "classhelios_1_1ecs_1_1InsertResourceCmd.html", "classhelios_1_1ecs_1_1InsertResourceCmd" ],
        [ "Local", "classhelios_1_1ecs_1_1Local.html", "classhelios_1_1ecs_1_1Local" ],
        [ "MainThreadExecutor", "classhelios_1_1ecs_1_1MainThreadExecutor.html", "classhelios_1_1ecs_1_1MainThreadExecutor" ],
        [ "MessageManager", "classhelios_1_1ecs_1_1MessageManager.html", "classhelios_1_1ecs_1_1MessageManager" ],
        [ "MessageMetadata", "structhelios_1_1ecs_1_1MessageMetadata.html", "structhelios_1_1ecs_1_1MessageMetadata" ],
        [ "MessageQueue", "classhelios_1_1ecs_1_1MessageQueue.html", "classhelios_1_1ecs_1_1MessageQueue" ],
        [ "MessageReader", "classhelios_1_1ecs_1_1MessageReader.html", "classhelios_1_1ecs_1_1MessageReader" ],
        [ "MessageReaderBase", "classhelios_1_1ecs_1_1MessageReaderBase.html", "classhelios_1_1ecs_1_1MessageReaderBase" ],
        [ "MessageWrapper", "classhelios_1_1ecs_1_1MessageWrapper.html", "classhelios_1_1ecs_1_1MessageWrapper" ],
        [ "MessageWrapperIter", "classhelios_1_1ecs_1_1MessageWrapperIter.html", "classhelios_1_1ecs_1_1MessageWrapperIter" ],
        [ "MultiThreadedExecutor", "classhelios_1_1ecs_1_1MultiThreadedExecutor.html", "classhelios_1_1ecs_1_1MultiThreadedExecutor" ],
        [ "RemoveComponentsCmd", "classhelios_1_1ecs_1_1RemoveComponentsCmd.html", "classhelios_1_1ecs_1_1RemoveComponentsCmd" ],
        [ "RemoveResourceCmd", "structhelios_1_1ecs_1_1RemoveResourceCmd.html", "structhelios_1_1ecs_1_1RemoveResourceCmd" ],
        [ "Res", "classhelios_1_1ecs_1_1Res.html", "classhelios_1_1ecs_1_1Res" ],
        [ "ResourceConflictInfo", "structhelios_1_1ecs_1_1ResourceConflictInfo.html", "structhelios_1_1ecs_1_1ResourceConflictInfo" ],
        [ "ResourceInsertedMsg", "structhelios_1_1ecs_1_1ResourceInsertedMsg.html", "structhelios_1_1ecs_1_1ResourceInsertedMsg" ],
        [ "ResourceManager", "classhelios_1_1ecs_1_1ResourceManager.html", "classhelios_1_1ecs_1_1ResourceManager" ],
        [ "ResourceRemovedMsg", "structhelios_1_1ecs_1_1ResourceRemovedMsg.html", "structhelios_1_1ecs_1_1ResourceRemovedMsg" ],
        [ "RunConditionStorage", "structhelios_1_1ecs_1_1RunConditionStorage.html", "structhelios_1_1ecs_1_1RunConditionStorage" ],
        [ "Schedule", "classhelios_1_1ecs_1_1Schedule.html", "classhelios_1_1ecs_1_1Schedule" ],
        [ "ScheduleError", "structhelios_1_1ecs_1_1ScheduleError.html", "structhelios_1_1ecs_1_1ScheduleError" ],
        [ "ScheduleOrdering", "classhelios_1_1ecs_1_1ScheduleOrdering.html", "classhelios_1_1ecs_1_1ScheduleOrdering" ],
        [ "Scheduler", "classhelios_1_1ecs_1_1Scheduler.html", "classhelios_1_1ecs_1_1Scheduler" ],
        [ "ScheduleSettings", "structhelios_1_1ecs_1_1ScheduleSettings.html", "structhelios_1_1ecs_1_1ScheduleSettings" ],
        [ "ScheduleSystemId", "structhelios_1_1ecs_1_1ScheduleSystemId.html", "structhelios_1_1ecs_1_1ScheduleSystemId" ],
        [ "ScheduleSystemMetadata", "structhelios_1_1ecs_1_1ScheduleSystemMetadata.html", "structhelios_1_1ecs_1_1ScheduleSystemMetadata" ],
        [ "SingleThreadedExecutor", "classhelios_1_1ecs_1_1SingleThreadedExecutor.html", "classhelios_1_1ecs_1_1SingleThreadedExecutor" ],
        [ "SparseComponentStorage", "classhelios_1_1ecs_1_1SparseComponentStorage.html", "classhelios_1_1ecs_1_1SparseComponentStorage" ],
        [ "StageOrdering", "classhelios_1_1ecs_1_1StageOrdering.html", "classhelios_1_1ecs_1_1StageOrdering" ],
        [ "SystemHandle", "classhelios_1_1ecs_1_1SystemHandle.html", "classhelios_1_1ecs_1_1SystemHandle" ],
        [ "SystemId", "structhelios_1_1ecs_1_1SystemId.html", "structhelios_1_1ecs_1_1SystemId" ],
        [ "SystemLocalData", "structhelios_1_1ecs_1_1SystemLocalData.html", "structhelios_1_1ecs_1_1SystemLocalData" ],
        [ "SystemLocalDataOptions", "structhelios_1_1ecs_1_1SystemLocalDataOptions.html", "structhelios_1_1ecs_1_1SystemLocalDataOptions" ],
        [ "SystemParamTraits", "structhelios_1_1ecs_1_1SystemParamTraits.html", null ],
        [ "SystemParamTraits< AsyncMessageReader< T > >", "structhelios_1_1ecs_1_1SystemParamTraits_3_01AsyncMessageReader_3_01T_01_4_01_4.html", "structhelios_1_1ecs_1_1SystemParamTraits_3_01AsyncMessageReader_3_01T_01_4_01_4" ],
        [ "SystemParamTraits< AsyncMessageWriter< T > >", "structhelios_1_1ecs_1_1SystemParamTraits_3_01AsyncMessageWriter_3_01T_01_4_01_4.html", "structhelios_1_1ecs_1_1SystemParamTraits_3_01AsyncMessageWriter_3_01T_01_4_01_4" ],
        [ "SystemParamTraits< BasicMessageWriter< T, Allocator > >", "structhelios_1_1ecs_1_1SystemParamTraits_3_01BasicMessageWriter_3_01T_00_01Allocator_01_4_01_4.html", "structhelios_1_1ecs_1_1SystemParamTraits_3_01BasicMessageWriter_3_01T_00_01Allocator_01_4_01_4" ],
        [ "SystemParamTraits< Commands >", "structhelios_1_1ecs_1_1SystemParamTraits_3_01Commands_01_4.html", "structhelios_1_1ecs_1_1SystemParamTraits_3_01Commands_01_4" ],
        [ "SystemParamTraits< ConsumableMessageReader< T > >", "structhelios_1_1ecs_1_1SystemParamTraits_3_01ConsumableMessageReader_3_01T_01_4_01_4.html", "structhelios_1_1ecs_1_1SystemParamTraits_3_01ConsumableMessageReader_3_01T_01_4_01_4" ],
        [ "SystemParamTraits< Local< const T > >", "structhelios_1_1ecs_1_1SystemParamTraits_3_01Local_3_01const_01T_01_4_01_4.html", "structhelios_1_1ecs_1_1SystemParamTraits_3_01Local_3_01const_01T_01_4_01_4" ],
        [ "SystemParamTraits< Local< T > >", "structhelios_1_1ecs_1_1SystemParamTraits_3_01Local_3_01T_01_4_01_4.html", "structhelios_1_1ecs_1_1SystemParamTraits_3_01Local_3_01T_01_4_01_4" ],
        [ "SystemParamTraits< MessageReader< T > >", "structhelios_1_1ecs_1_1SystemParamTraits_3_01MessageReader_3_01T_01_4_01_4.html", "structhelios_1_1ecs_1_1SystemParamTraits_3_01MessageReader_3_01T_01_4_01_4" ],
        [ "SystemParamTraits< MessageWriter< T > >", "structhelios_1_1ecs_1_1SystemParamTraits_3_01MessageWriter_3_01T_01_4_01_4.html", "structhelios_1_1ecs_1_1SystemParamTraits_3_01MessageWriter_3_01T_01_4_01_4" ],
        [ "SystemParamTraits< Query< Args... > >", "structhelios_1_1ecs_1_1SystemParamTraits_3_01Query_3_01Args_8_8_8_01_4_01_4.html", "structhelios_1_1ecs_1_1SystemParamTraits_3_01Query_3_01Args_8_8_8_01_4_01_4" ],
        [ "SystemParamTraits< Res< const T > >", "structhelios_1_1ecs_1_1SystemParamTraits_3_01Res_3_01const_01T_01_4_01_4.html", "structhelios_1_1ecs_1_1SystemParamTraits_3_01Res_3_01const_01T_01_4_01_4" ],
        [ "SystemParamTraits< Res< T > >", "structhelios_1_1ecs_1_1SystemParamTraits_3_01Res_3_01T_01_4_01_4.html", "structhelios_1_1ecs_1_1SystemParamTraits_3_01Res_3_01T_01_4_01_4" ],
        [ "SystemParamTraits< std::optional< Local< const T > > >", "structhelios_1_1ecs_1_1SystemParamTraits_3_01std_1_1optional_3_01Local_3_01const_01T_01_4_01_4_01_4.html", "structhelios_1_1ecs_1_1SystemParamTraits_3_01std_1_1optional_3_01Local_3_01const_01T_01_4_01_4_01_4" ],
        [ "SystemParamTraits< std::optional< Local< T > > >", "structhelios_1_1ecs_1_1SystemParamTraits_3_01std_1_1optional_3_01Local_3_01T_01_4_01_4_01_4.html", "structhelios_1_1ecs_1_1SystemParamTraits_3_01std_1_1optional_3_01Local_3_01T_01_4_01_4_01_4" ],
        [ "SystemParamTraits< std::optional< Res< const T > > >", "structhelios_1_1ecs_1_1SystemParamTraits_3_01std_1_1optional_3_01Res_3_01const_01T_01_4_01_4_01_4.html", "structhelios_1_1ecs_1_1SystemParamTraits_3_01std_1_1optional_3_01Res_3_01const_01T_01_4_01_4_01_4" ],
        [ "SystemParamTraits< std::optional< Res< T > > >", "structhelios_1_1ecs_1_1SystemParamTraits_3_01std_1_1optional_3_01Res_3_01T_01_4_01_4_01_4.html", "structhelios_1_1ecs_1_1SystemParamTraits_3_01std_1_1optional_3_01Res_3_01T_01_4_01_4_01_4" ],
        [ "SystemParamTraits< WorldView >", "structhelios_1_1ecs_1_1SystemParamTraits_3_01WorldView_01_4.html", "structhelios_1_1ecs_1_1SystemParamTraits_3_01WorldView_01_4" ],
        [ "SystemSet", "classhelios_1_1ecs_1_1SystemSet.html", "classhelios_1_1ecs_1_1SystemSet" ],
        [ "SystemSetHandle", "classhelios_1_1ecs_1_1SystemSetHandle.html", "classhelios_1_1ecs_1_1SystemSetHandle" ],
        [ "SystemSetId", "structhelios_1_1ecs_1_1SystemSetId.html", "structhelios_1_1ecs_1_1SystemSetId" ],
        [ "SystemStorage", "structhelios_1_1ecs_1_1SystemStorage.html", "structhelios_1_1ecs_1_1SystemStorage" ],
        [ "TryAddComponentsCmd", "classhelios_1_1ecs_1_1TryAddComponentsCmd.html", "classhelios_1_1ecs_1_1TryAddComponentsCmd" ],
        [ "TryDestroyEntitiesCmd", "classhelios_1_1ecs_1_1TryDestroyEntitiesCmd.html", "classhelios_1_1ecs_1_1TryDestroyEntitiesCmd" ],
        [ "TryDestroyEntityCmd", "classhelios_1_1ecs_1_1TryDestroyEntityCmd.html", "classhelios_1_1ecs_1_1TryDestroyEntityCmd" ],
        [ "TryInsertResourceCmd", "classhelios_1_1ecs_1_1TryInsertResourceCmd.html", "classhelios_1_1ecs_1_1TryInsertResourceCmd" ],
        [ "TryRemoveComponentsCmd", "classhelios_1_1ecs_1_1TryRemoveComponentsCmd.html", "classhelios_1_1ecs_1_1TryRemoveComponentsCmd" ],
        [ "TryRemoveResourceCmd", "structhelios_1_1ecs_1_1TryRemoveResourceCmd.html", "structhelios_1_1ecs_1_1TryRemoveResourceCmd" ],
        [ "TypedAsyncMessageStorage", "classhelios_1_1ecs_1_1TypedAsyncMessageStorage.html", "classhelios_1_1ecs_1_1TypedAsyncMessageStorage" ],
        [ "World", "classhelios_1_1ecs_1_1World.html", "classhelios_1_1ecs_1_1World" ],
        [ "WorldCmdBuffer", "classhelios_1_1ecs_1_1WorldCmdBuffer.html", "classhelios_1_1ecs_1_1WorldCmdBuffer" ],
        [ "WorldView", "classhelios_1_1ecs_1_1WorldView.html", "classhelios_1_1ecs_1_1WorldView" ]
      ] ],
      [ "log", "namespacehelios_1_1log.html", [
        [ "Config", "structhelios_1_1log_1_1Config.html", "structhelios_1_1log_1_1Config" ],
        [ "DefaultLogger", "structhelios_1_1log_1_1DefaultLogger.html", "structhelios_1_1log_1_1DefaultLogger" ],
        [ "Logger", "classhelios_1_1log_1_1Logger.html", "classhelios_1_1log_1_1Logger" ]
      ] ],
      [ "mem", "namespacehelios_1_1mem.html", [
        [ "AllocatorStats", "structhelios_1_1mem_1_1AllocatorStats.html", "structhelios_1_1mem_1_1AllocatorStats" ],
        [ "ArcFromThis", "classhelios_1_1mem_1_1ArcFromThis.html", "classhelios_1_1mem_1_1ArcFromThis" ],
        [ "ArenaAllocator", "classhelios_1_1mem_1_1ArenaAllocator.html", "classhelios_1_1mem_1_1ArenaAllocator" ],
        [ "ArenaOptions", "structhelios_1_1mem_1_1ArenaOptions.html", "structhelios_1_1mem_1_1ArenaOptions" ],
        [ "AtomicRefCounted", "classhelios_1_1mem_1_1AtomicRefCounted.html", "classhelios_1_1mem_1_1AtomicRefCounted" ],
        [ "FrameAllocatorOptions", "structhelios_1_1mem_1_1FrameAllocatorOptions.html", "structhelios_1_1mem_1_1FrameAllocatorOptions" ],
        [ "FreeListAllocator", "classhelios_1_1mem_1_1FreeListAllocator.html", "classhelios_1_1mem_1_1FreeListAllocator" ],
        [ "FreeListAllocatorOptions", "structhelios_1_1mem_1_1FreeListAllocatorOptions.html", "structhelios_1_1mem_1_1FreeListAllocatorOptions" ],
        [ "GrowthPolicy", "structhelios_1_1mem_1_1GrowthPolicy.html", "structhelios_1_1mem_1_1GrowthPolicy" ],
        [ "NFrameAllocator", "classhelios_1_1mem_1_1NFrameAllocator.html", "classhelios_1_1mem_1_1NFrameAllocator" ],
        [ "PoolAllocator", "classhelios_1_1mem_1_1PoolAllocator.html", "classhelios_1_1mem_1_1PoolAllocator" ],
        [ "PoolAllocatorOptions", "structhelios_1_1mem_1_1PoolAllocatorOptions.html", "structhelios_1_1mem_1_1PoolAllocatorOptions" ],
        [ "RcFromThis", "classhelios_1_1mem_1_1RcFromThis.html", "classhelios_1_1mem_1_1RcFromThis" ],
        [ "RefCounted", "classhelios_1_1mem_1_1RefCounted.html", "classhelios_1_1mem_1_1RefCounted" ],
        [ "StackAllocator", "classhelios_1_1mem_1_1StackAllocator.html", "classhelios_1_1mem_1_1StackAllocator" ],
        [ "StackAllocatorOptions", "structhelios_1_1mem_1_1StackAllocatorOptions.html", "structhelios_1_1mem_1_1StackAllocatorOptions" ]
      ] ],
      [ "profile", "namespacehelios_1_1profile.html", [
        [ "Backend", "classhelios_1_1profile_1_1Backend.html", "classhelios_1_1profile_1_1Backend" ],
        [ "FlamegraphBackend", "classhelios_1_1profile_1_1FlamegraphBackend.html", "classhelios_1_1profile_1_1FlamegraphBackend" ],
        [ "FlamegraphBackendConfig", "structhelios_1_1profile_1_1FlamegraphBackendConfig.html", "structhelios_1_1profile_1_1FlamegraphBackendConfig" ],
        [ "Profiler", "classhelios_1_1profile_1_1Profiler.html", "classhelios_1_1profile_1_1Profiler" ],
        [ "ScopedZone", "classhelios_1_1profile_1_1ScopedZone.html", "classhelios_1_1profile_1_1ScopedZone" ],
        [ "TracyBackend", "classhelios_1_1profile_1_1TracyBackend.html", "classhelios_1_1profile_1_1TracyBackend" ],
        [ "ZoneSpec", "structhelios_1_1profile_1_1ZoneSpec.html", "structhelios_1_1profile_1_1ZoneSpec" ]
      ] ],
      [ "utils", "namespacehelios_1_1utils.html", [
        [ "details", "namespacehelios_1_1utils_1_1details.html", [
          [ "adapter_iterator_traits", "structhelios_1_1utils_1_1details_1_1adapter__iterator__traits.html", "structhelios_1_1utils_1_1details_1_1adapter__iterator__traits" ],
          [ "FixedString", "structhelios_1_1utils_1_1details_1_1FixedString.html", "structhelios_1_1utils_1_1details_1_1FixedString" ],
          [ "folder_apply_result", "structhelios_1_1utils_1_1details_1_1folder__apply__result.html", null ],
          [ "folder_apply_result< Folder, Accumulator, std::tuple< TupleArgs... > >", "structhelios_1_1utils_1_1details_1_1folder__apply__result_3_01Folder_00_01Accumulator_00_01std_1ce2978c0f27b507bfe0e6e04cc632169.html", "structhelios_1_1utils_1_1details_1_1folder__apply__result_3_01Folder_00_01Accumulator_00_01std_1ce2978c0f27b507bfe0e6e04cc632169" ],
          [ "is_folder_applicable_impl", "structhelios_1_1utils_1_1details_1_1is__folder__applicable__impl.html", null ],
          [ "is_folder_applicable_impl< Folder, Accumulator, std::tuple< TupleArgs... > >", "structhelios_1_1utils_1_1details_1_1is__folder__applicable__impl_3_01Folder_00_01Accumulator_00_5474f6b3ac109ab26feda2bd4f995a76.html", null ],
          [ "UniqueTypesHelper", "structhelios_1_1utils_1_1details_1_1UniqueTypesHelper.html", null ],
          [ "UniqueTypesHelper< T, Rest... >", "structhelios_1_1utils_1_1details_1_1UniqueTypesHelper_3_01T_00_01Rest_8_8_8_01_4.html", null ]
        ] ],
        [ "ChainAdapter", "classhelios_1_1utils_1_1ChainAdapter.html", "classhelios_1_1utils_1_1ChainAdapter" ],
        [ "Defer", "classhelios_1_1utils_1_1Defer.html", "classhelios_1_1utils_1_1Defer" ],
        [ "DynamicLibrary", "classhelios_1_1utils_1_1DynamicLibrary.html", "classhelios_1_1utils_1_1DynamicLibrary" ],
        [ "EnumerateAdapter", "classhelios_1_1utils_1_1EnumerateAdapter.html", "classhelios_1_1utils_1_1EnumerateAdapter" ],
        [ "FastPimpl", "classhelios_1_1utils_1_1FastPimpl.html", "classhelios_1_1utils_1_1FastPimpl" ],
        [ "FilterAdapter", "classhelios_1_1utils_1_1FilterAdapter.html", "classhelios_1_1utils_1_1FilterAdapter" ],
        [ "FunctionalAdapterBase", "classhelios_1_1utils_1_1FunctionalAdapterBase.html", "classhelios_1_1utils_1_1FunctionalAdapterBase" ],
        [ "InspectAdapter", "classhelios_1_1utils_1_1InspectAdapter.html", "classhelios_1_1utils_1_1InspectAdapter" ],
        [ "JoinAdapter", "classhelios_1_1utils_1_1JoinAdapter.html", null ],
        [ "MapAdapter", "classhelios_1_1utils_1_1MapAdapter.html", "classhelios_1_1utils_1_1MapAdapter" ],
        [ "RandomGenerator", "classhelios_1_1utils_1_1RandomGenerator.html", "classhelios_1_1utils_1_1RandomGenerator" ],
        [ "ReverseAdapter", "classhelios_1_1utils_1_1ReverseAdapter.html", "classhelios_1_1utils_1_1ReverseAdapter" ],
        [ "SkipAdapter", "classhelios_1_1utils_1_1SkipAdapter.html", "classhelios_1_1utils_1_1SkipAdapter" ],
        [ "SkipWhileAdapter", "classhelios_1_1utils_1_1SkipWhileAdapter.html", "classhelios_1_1utils_1_1SkipWhileAdapter" ],
        [ "SlideAdapter", "classhelios_1_1utils_1_1SlideAdapter.html", "classhelios_1_1utils_1_1SlideAdapter" ],
        [ "SlideView", "classhelios_1_1utils_1_1SlideView.html", "classhelios_1_1utils_1_1SlideView" ],
        [ "StepByAdapter", "classhelios_1_1utils_1_1StepByAdapter.html", "classhelios_1_1utils_1_1StepByAdapter" ],
        [ "StrideAdapter", "classhelios_1_1utils_1_1StrideAdapter.html", "classhelios_1_1utils_1_1StrideAdapter" ],
        [ "StringEqual", "structhelios_1_1utils_1_1StringEqual.html", "structhelios_1_1utils_1_1StringEqual" ],
        [ "StringHash", "structhelios_1_1utils_1_1StringHash.html", "structhelios_1_1utils_1_1StringHash" ],
        [ "TakeAdapter", "classhelios_1_1utils_1_1TakeAdapter.html", "classhelios_1_1utils_1_1TakeAdapter" ],
        [ "TakeWhileAdapter", "classhelios_1_1utils_1_1TakeWhileAdapter.html", "classhelios_1_1utils_1_1TakeWhileAdapter" ],
        [ "Timer", "classhelios_1_1utils_1_1Timer.html", "classhelios_1_1utils_1_1Timer" ],
        [ "TypeId", "classhelios_1_1utils_1_1TypeId.html", "classhelios_1_1utils_1_1TypeId" ],
        [ "TypeIndex", "classhelios_1_1utils_1_1TypeIndex.html", "classhelios_1_1utils_1_1TypeIndex" ],
        [ "ZipAdapter", "classhelios_1_1utils_1_1ZipAdapter.html", "classhelios_1_1utils_1_1ZipAdapter" ]
      ] ],
      [ "BasicCStringView", "classhelios_1_1BasicCStringView.html", "classhelios_1_1BasicCStringView" ],
      [ "Delegate", "classhelios_1_1Delegate.html", null ],
      [ "Delegate< ReturnType(Args...)>", "classhelios_1_1Delegate_3_01ReturnType_07Args_8_8_8_08_4.html", "classhelios_1_1Delegate_3_01ReturnType_07Args_8_8_8_08_4" ],
      [ "Stacktrace", "classhelios_1_1Stacktrace.html", "classhelios_1_1Stacktrace" ],
      [ "StacktraceConfig", "structhelios_1_1StacktraceConfig.html", "structhelios_1_1StacktraceConfig" ],
      [ "Uuid", "classhelios_1_1Uuid.html", "classhelios_1_1Uuid" ],
      [ "UuidGenerator", "classhelios_1_1UuidGenerator.html", "classhelios_1_1UuidGenerator" ]
    ] ],
    [ "std", "namespacestd.html", [
      [ "hash< helios::ecs::SystemId >", "structstd_1_1hash_3_01helios_1_1ecs_1_1SystemId_01_4.html", "structstd_1_1hash_3_01helios_1_1ecs_1_1SystemId_01_4" ]
    ] ]
];