var annotated_dup =
[
    [ "anonymous_namespace{logger.cpp}", "namespaceanonymous__namespace_02logger_8cpp_03.html", [
      [ "SourceLocationFormatterFlag", "classanonymous__namespace_02logger_8cpp_03_1_1SourceLocationFormatterFlag.html", "classanonymous__namespace_02logger_8cpp_03_1_1SourceLocationFormatterFlag" ]
    ] ],
    [ "helios", "namespacehelios.html", [
      [ "app", "namespacehelios_1_1app.html", [
        [ "details", "namespacehelios_1_1app_1_1details.html", [
          [ "ComponentTypeInfo", "structhelios_1_1app_1_1details_1_1ComponentTypeInfo.html", "structhelios_1_1app_1_1details_1_1ComponentTypeInfo" ],
          [ "QueryDescriptor", "structhelios_1_1app_1_1details_1_1QueryDescriptor.html", "structhelios_1_1app_1_1details_1_1QueryDescriptor" ],
          [ "ResourceTypeInfo", "structhelios_1_1app_1_1details_1_1ResourceTypeInfo.html", "structhelios_1_1app_1_1details_1_1ResourceTypeInfo" ],
          [ "ScheduleExecutor", "classhelios_1_1app_1_1details_1_1ScheduleExecutor.html", "classhelios_1_1app_1_1details_1_1ScheduleExecutor" ],
          [ "ScheduleOrdering", "structhelios_1_1app_1_1details_1_1ScheduleOrdering.html", "structhelios_1_1app_1_1details_1_1ScheduleOrdering" ],
          [ "Scheduler", "classhelios_1_1app_1_1details_1_1Scheduler.html", "classhelios_1_1app_1_1details_1_1Scheduler" ],
          [ "SystemDiagnostics", "classhelios_1_1app_1_1details_1_1SystemDiagnostics.html", "classhelios_1_1app_1_1details_1_1SystemDiagnostics" ],
          [ "SystemInfo", "structhelios_1_1app_1_1details_1_1SystemInfo.html", "structhelios_1_1app_1_1details_1_1SystemInfo" ],
          [ "SystemOrdering", "structhelios_1_1app_1_1details_1_1SystemOrdering.html", "structhelios_1_1app_1_1details_1_1SystemOrdering" ],
          [ "SystemSetInfo", "structhelios_1_1app_1_1details_1_1SystemSetInfo.html", "structhelios_1_1app_1_1details_1_1SystemSetInfo" ],
          [ "SystemStorage", "structhelios_1_1app_1_1details_1_1SystemStorage.html", "structhelios_1_1app_1_1details_1_1SystemStorage" ],
          [ "TrackedFuture", "structhelios_1_1app_1_1details_1_1TrackedFuture.html", "structhelios_1_1app_1_1details_1_1TrackedFuture" ]
        ] ],
        [ "AccessPolicy", "classhelios_1_1app_1_1AccessPolicy.html", "classhelios_1_1app_1_1AccessPolicy" ],
        [ "App", "classhelios_1_1app_1_1App.html", "classhelios_1_1app_1_1App" ],
        [ "CleanUp", "structhelios_1_1app_1_1CleanUp.html", "structhelios_1_1app_1_1CleanUp" ],
        [ "CleanUpStage", "structhelios_1_1app_1_1CleanUpStage.html", "structhelios_1_1app_1_1CleanUpStage" ],
        [ "DefaultRunnerConfig", "structhelios_1_1app_1_1DefaultRunnerConfig.html", "structhelios_1_1app_1_1DefaultRunnerConfig" ],
        [ "DynamicModule", "classhelios_1_1app_1_1DynamicModule.html", "classhelios_1_1app_1_1DynamicModule" ],
        [ "DynamicModuleConfig", "structhelios_1_1app_1_1DynamicModuleConfig.html", "structhelios_1_1app_1_1DynamicModuleConfig" ],
        [ "First", "structhelios_1_1app_1_1First.html", "structhelios_1_1app_1_1First" ],
        [ "FixedTimestepRunnerConfig", "structhelios_1_1app_1_1FixedTimestepRunnerConfig.html", "structhelios_1_1app_1_1FixedTimestepRunnerConfig" ],
        [ "FrameAllocatorResource", "classhelios_1_1app_1_1FrameAllocatorResource.html", "classhelios_1_1app_1_1FrameAllocatorResource" ],
        [ "FrameLimitedRunnerConfig", "structhelios_1_1app_1_1FrameLimitedRunnerConfig.html", "structhelios_1_1app_1_1FrameLimitedRunnerConfig" ],
        [ "FreeListAllocatorResource", "classhelios_1_1app_1_1FreeListAllocatorResource.html", "classhelios_1_1app_1_1FreeListAllocatorResource" ],
        [ "Last", "structhelios_1_1app_1_1Last.html", "structhelios_1_1app_1_1Last" ],
        [ "Main", "structhelios_1_1app_1_1Main.html", "structhelios_1_1app_1_1Main" ],
        [ "MainStage", "structhelios_1_1app_1_1MainStage.html", "structhelios_1_1app_1_1MainStage" ],
        [ "Module", "classhelios_1_1app_1_1Module.html", "classhelios_1_1app_1_1Module" ],
        [ "OnceRunnerConfig", "structhelios_1_1app_1_1OnceRunnerConfig.html", "structhelios_1_1app_1_1OnceRunnerConfig" ],
        [ "PoolAllocatorResource", "classhelios_1_1app_1_1PoolAllocatorResource.html", "classhelios_1_1app_1_1PoolAllocatorResource" ],
        [ "PostCleanUp", "structhelios_1_1app_1_1PostCleanUp.html", "structhelios_1_1app_1_1PostCleanUp" ],
        [ "PostStartup", "structhelios_1_1app_1_1PostStartup.html", "structhelios_1_1app_1_1PostStartup" ],
        [ "PostUpdate", "structhelios_1_1app_1_1PostUpdate.html", "structhelios_1_1app_1_1PostUpdate" ],
        [ "PreCleanUp", "structhelios_1_1app_1_1PreCleanUp.html", "structhelios_1_1app_1_1PreCleanUp" ],
        [ "PreStartup", "structhelios_1_1app_1_1PreStartup.html", "structhelios_1_1app_1_1PreStartup" ],
        [ "PreUpdate", "structhelios_1_1app_1_1PreUpdate.html", "structhelios_1_1app_1_1PreUpdate" ],
        [ "StackAllocatorResource", "classhelios_1_1app_1_1StackAllocatorResource.html", "classhelios_1_1app_1_1StackAllocatorResource" ],
        [ "Startup", "structhelios_1_1app_1_1Startup.html", "structhelios_1_1app_1_1Startup" ],
        [ "StartUpStage", "structhelios_1_1app_1_1StartUpStage.html", "structhelios_1_1app_1_1StartUpStage" ],
        [ "SubApp", "classhelios_1_1app_1_1SubApp.html", "classhelios_1_1app_1_1SubApp" ],
        [ "SystemConfig", "classhelios_1_1app_1_1SystemConfig.html", "classhelios_1_1app_1_1SystemConfig" ],
        [ "SystemContext", "classhelios_1_1app_1_1SystemContext.html", "classhelios_1_1app_1_1SystemContext" ],
        [ "SystemSetConfig", "classhelios_1_1app_1_1SystemSetConfig.html", "classhelios_1_1app_1_1SystemSetConfig" ],
        [ "Time", "classhelios_1_1app_1_1Time.html", "classhelios_1_1app_1_1Time" ],
        [ "TimedRunnerConfig", "structhelios_1_1app_1_1TimedRunnerConfig.html", "structhelios_1_1app_1_1TimedRunnerConfig" ],
        [ "Update", "structhelios_1_1app_1_1Update.html", "structhelios_1_1app_1_1Update" ],
        [ "UpdateStage", "structhelios_1_1app_1_1UpdateStage.html", "structhelios_1_1app_1_1UpdateStage" ]
      ] ],
      [ "async", "namespacehelios_1_1async.html", [
        [ "AsyncTask", "classhelios_1_1async_1_1AsyncTask.html", "classhelios_1_1async_1_1AsyncTask" ],
        [ "Executor", "classhelios_1_1async_1_1Executor.html", "classhelios_1_1async_1_1Executor" ],
        [ "Future", "classhelios_1_1async_1_1Future.html", "classhelios_1_1async_1_1Future" ],
        [ "SubTaskGraph", "classhelios_1_1async_1_1SubTaskGraph.html", "classhelios_1_1async_1_1SubTaskGraph" ],
        [ "Task", "classhelios_1_1async_1_1Task.html", "classhelios_1_1async_1_1Task" ],
        [ "TaskGraph", "classhelios_1_1async_1_1TaskGraph.html", "classhelios_1_1async_1_1TaskGraph" ]
      ] ],
      [ "container", "namespacehelios_1_1container.html", [
        [ "BasicStaticString", "classhelios_1_1container_1_1BasicStaticString.html", "classhelios_1_1container_1_1BasicStaticString" ],
        [ "SparseSet", "classhelios_1_1container_1_1SparseSet.html", "classhelios_1_1container_1_1SparseSet" ]
      ] ],
      [ "details", "namespacehelios_1_1details.html", [
        [ "FreeFunctionTraits", "structhelios_1_1details_1_1FreeFunctionTraits.html", null ],
        [ "FreeFunctionTraits< R(*)(Args...)>", "structhelios_1_1details_1_1FreeFunctionTraits_3_01R_07_5_08_07Args_8_8_8_08_4.html", "structhelios_1_1details_1_1FreeFunctionTraits_3_01R_07_5_08_07Args_8_8_8_08_4" ],
        [ "MemberFunctionTraits", "structhelios_1_1details_1_1MemberFunctionTraits.html", null ],
        [ "MemberFunctionTraits< R(C::*)(Args...) const >", "structhelios_1_1details_1_1MemberFunctionTraits_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01const_01_4.html", "structhelios_1_1details_1_1MemberFunctionTraits_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01const_01_4" ],
        [ "MemberFunctionTraits< R(C::*)(Args...)>", "structhelios_1_1details_1_1MemberFunctionTraits_3_01R_07C_1_1_5_08_07Args_8_8_8_08_4.html", "structhelios_1_1details_1_1MemberFunctionTraits_3_01R_07C_1_1_5_08_07Args_8_8_8_08_4" ],
        [ "TupleToFunctionSignature", "structhelios_1_1details_1_1TupleToFunctionSignature.html", null ],
        [ "TupleToFunctionSignature< std::tuple< R, Args... > >", "structhelios_1_1details_1_1TupleToFunctionSignature_3_01std_1_1tuple_3_01R_00_01Args_8_8_8_01_4_01_4.html", "structhelios_1_1details_1_1TupleToFunctionSignature_3_01std_1_1tuple_3_01R_00_01Args_8_8_8_01_4_01_4" ]
      ] ],
      [ "ecs", "namespacehelios_1_1ecs.html", [
        [ "details", "namespacehelios_1_1ecs_1_1details.html", [
          [ "AddComponentCmd", "classhelios_1_1ecs_1_1details_1_1AddComponentCmd.html", "classhelios_1_1ecs_1_1details_1_1AddComponentCmd" ],
          [ "AddComponentsCmd", "classhelios_1_1ecs_1_1details_1_1AddComponentsCmd.html", "classhelios_1_1ecs_1_1details_1_1AddComponentsCmd" ],
          [ "Archetype", "classhelios_1_1ecs_1_1details_1_1Archetype.html", "classhelios_1_1ecs_1_1details_1_1Archetype" ],
          [ "ArchetypeEdgeKey", "structhelios_1_1ecs_1_1details_1_1ArchetypeEdgeKey.html", "structhelios_1_1ecs_1_1details_1_1ArchetypeEdgeKey" ],
          [ "ArchetypeEdgeKeyHash", "structhelios_1_1ecs_1_1details_1_1ArchetypeEdgeKeyHash.html", "structhelios_1_1ecs_1_1details_1_1ArchetypeEdgeKeyHash" ],
          [ "Archetypes", "classhelios_1_1ecs_1_1details_1_1Archetypes.html", "classhelios_1_1ecs_1_1details_1_1Archetypes" ],
          [ "ClearAllEventsCmd", "classhelios_1_1ecs_1_1details_1_1ClearAllEventsCmd.html", "classhelios_1_1ecs_1_1details_1_1ClearAllEventsCmd" ],
          [ "ClearComponentsCmd", "classhelios_1_1ecs_1_1details_1_1ClearComponentsCmd.html", "classhelios_1_1ecs_1_1details_1_1ClearComponentsCmd" ],
          [ "ClearEventsCmd", "classhelios_1_1ecs_1_1details_1_1ClearEventsCmd.html", "classhelios_1_1ecs_1_1details_1_1ClearEventsCmd" ],
          [ "CmdBuffer", "classhelios_1_1ecs_1_1details_1_1CmdBuffer.html", "classhelios_1_1ecs_1_1details_1_1CmdBuffer" ],
          [ "CmdQueue", "classhelios_1_1ecs_1_1details_1_1CmdQueue.html", "classhelios_1_1ecs_1_1details_1_1CmdQueue" ],
          [ "Components", "classhelios_1_1ecs_1_1details_1_1Components.html", "classhelios_1_1ecs_1_1details_1_1Components" ],
          [ "ComponentStorage", "classhelios_1_1ecs_1_1details_1_1ComponentStorage.html", "classhelios_1_1ecs_1_1details_1_1ComponentStorage" ],
          [ "ComponentStorageBase", "classhelios_1_1ecs_1_1details_1_1ComponentStorageBase.html", "classhelios_1_1ecs_1_1details_1_1ComponentStorageBase" ],
          [ "ComponentTypeExtractor", "structhelios_1_1ecs_1_1details_1_1ComponentTypeExtractor.html", "structhelios_1_1ecs_1_1details_1_1ComponentTypeExtractor" ],
          [ "DestroyEntitiesCmd", "classhelios_1_1ecs_1_1details_1_1DestroyEntitiesCmd.html", "classhelios_1_1ecs_1_1details_1_1DestroyEntitiesCmd" ],
          [ "DestroyEntityCmd", "classhelios_1_1ecs_1_1details_1_1DestroyEntityCmd.html", "classhelios_1_1ecs_1_1details_1_1DestroyEntityCmd" ],
          [ "Entities", "classhelios_1_1ecs_1_1details_1_1Entities.html", "classhelios_1_1ecs_1_1details_1_1Entities" ],
          [ "EventManager", "classhelios_1_1ecs_1_1details_1_1EventManager.html", "classhelios_1_1ecs_1_1details_1_1EventManager" ],
          [ "EventMetadata", "structhelios_1_1ecs_1_1details_1_1EventMetadata.html", "structhelios_1_1ecs_1_1details_1_1EventMetadata" ],
          [ "EventQueue", "classhelios_1_1ecs_1_1details_1_1EventQueue.html", "classhelios_1_1ecs_1_1details_1_1EventQueue" ],
          [ "EventStorage", "classhelios_1_1ecs_1_1details_1_1EventStorage.html", "classhelios_1_1ecs_1_1details_1_1EventStorage" ],
          [ "FunctionCmd", "classhelios_1_1ecs_1_1details_1_1FunctionCmd.html", "classhelios_1_1ecs_1_1details_1_1FunctionCmd" ],
          [ "InsertResourceCmd", "classhelios_1_1ecs_1_1details_1_1InsertResourceCmd.html", "classhelios_1_1ecs_1_1details_1_1InsertResourceCmd" ],
          [ "QueryCacheManager", "classhelios_1_1ecs_1_1details_1_1QueryCacheManager.html", "classhelios_1_1ecs_1_1details_1_1QueryCacheManager" ],
          [ "QueryCacheStats", "structhelios_1_1ecs_1_1details_1_1QueryCacheStats.html", "structhelios_1_1ecs_1_1details_1_1QueryCacheStats" ],
          [ "QueryIterator", "classhelios_1_1ecs_1_1details_1_1QueryIterator.html", "classhelios_1_1ecs_1_1details_1_1QueryIterator" ],
          [ "QueryState", "structhelios_1_1ecs_1_1details_1_1QueryState.html", "structhelios_1_1ecs_1_1details_1_1QueryState" ],
          [ "QueryWithEntityIterator", "classhelios_1_1ecs_1_1details_1_1QueryWithEntityIterator.html", "classhelios_1_1ecs_1_1details_1_1QueryWithEntityIterator" ],
          [ "RemoveComponentCmd", "classhelios_1_1ecs_1_1details_1_1RemoveComponentCmd.html", "classhelios_1_1ecs_1_1details_1_1RemoveComponentCmd" ],
          [ "RemoveComponentsCmd", "classhelios_1_1ecs_1_1details_1_1RemoveComponentsCmd.html", "classhelios_1_1ecs_1_1details_1_1RemoveComponentsCmd" ],
          [ "RemoveResourceCmd", "classhelios_1_1ecs_1_1details_1_1RemoveResourceCmd.html", "classhelios_1_1ecs_1_1details_1_1RemoveResourceCmd" ],
          [ "Resources", "classhelios_1_1ecs_1_1details_1_1Resources.html", "classhelios_1_1ecs_1_1details_1_1Resources" ],
          [ "ResourceStorage", "classhelios_1_1ecs_1_1details_1_1ResourceStorage.html", "classhelios_1_1ecs_1_1details_1_1ResourceStorage" ],
          [ "ResourceStorageBase", "classhelios_1_1ecs_1_1details_1_1ResourceStorageBase.html", "classhelios_1_1ecs_1_1details_1_1ResourceStorageBase" ],
          [ "SystemLocalStorage", "classhelios_1_1ecs_1_1details_1_1SystemLocalStorage.html", "classhelios_1_1ecs_1_1details_1_1SystemLocalStorage" ],
          [ "TryAddComponentCmd", "classhelios_1_1ecs_1_1details_1_1TryAddComponentCmd.html", "classhelios_1_1ecs_1_1details_1_1TryAddComponentCmd" ],
          [ "TryAddComponentsCmd", "classhelios_1_1ecs_1_1details_1_1TryAddComponentsCmd.html", "classhelios_1_1ecs_1_1details_1_1TryAddComponentsCmd" ],
          [ "TryDestroyEntitiesCmd", "classhelios_1_1ecs_1_1details_1_1TryDestroyEntitiesCmd.html", "classhelios_1_1ecs_1_1details_1_1TryDestroyEntitiesCmd" ],
          [ "TryDestroyEntityCmd", "classhelios_1_1ecs_1_1details_1_1TryDestroyEntityCmd.html", "classhelios_1_1ecs_1_1details_1_1TryDestroyEntityCmd" ],
          [ "TryInsertResourceCmd", "classhelios_1_1ecs_1_1details_1_1TryInsertResourceCmd.html", "classhelios_1_1ecs_1_1details_1_1TryInsertResourceCmd" ],
          [ "TryRemoveComponentCmd", "classhelios_1_1ecs_1_1details_1_1TryRemoveComponentCmd.html", "classhelios_1_1ecs_1_1details_1_1TryRemoveComponentCmd" ],
          [ "TryRemoveComponentsCmd", "classhelios_1_1ecs_1_1details_1_1TryRemoveComponentsCmd.html", "classhelios_1_1ecs_1_1details_1_1TryRemoveComponentsCmd" ],
          [ "TryRemoveResourceCmd", "classhelios_1_1ecs_1_1details_1_1TryRemoveResourceCmd.html", "classhelios_1_1ecs_1_1details_1_1TryRemoveResourceCmd" ]
        ] ],
        [ "BasicQuery", "classhelios_1_1ecs_1_1BasicQuery.html", "classhelios_1_1ecs_1_1BasicQuery" ],
        [ "BasicQueryBuilder", "classhelios_1_1ecs_1_1BasicQueryBuilder.html", "classhelios_1_1ecs_1_1BasicQueryBuilder" ],
        [ "BasicQueryWithEntity", "classhelios_1_1ecs_1_1BasicQueryWithEntity.html", "classhelios_1_1ecs_1_1BasicQueryWithEntity" ],
        [ "Command", "classhelios_1_1ecs_1_1Command.html", "classhelios_1_1ecs_1_1Command" ],
        [ "ComponentTraits", "structhelios_1_1ecs_1_1ComponentTraits.html", "structhelios_1_1ecs_1_1ComponentTraits" ],
        [ "ComponentTypeInfo", "classhelios_1_1ecs_1_1ComponentTypeInfo.html", "classhelios_1_1ecs_1_1ComponentTypeInfo" ],
        [ "Entity", "classhelios_1_1ecs_1_1Entity.html", "classhelios_1_1ecs_1_1Entity" ],
        [ "EntityCmdBuffer", "classhelios_1_1ecs_1_1EntityCmdBuffer.html", "classhelios_1_1ecs_1_1EntityCmdBuffer" ],
        [ "EntityDestroyedEvent", "structhelios_1_1ecs_1_1EntityDestroyedEvent.html", "structhelios_1_1ecs_1_1EntityDestroyedEvent" ],
        [ "EntitySpawnedEvent", "structhelios_1_1ecs_1_1EntitySpawnedEvent.html", "structhelios_1_1ecs_1_1EntitySpawnedEvent" ],
        [ "EventIterator", "classhelios_1_1ecs_1_1EventIterator.html", "classhelios_1_1ecs_1_1EventIterator" ],
        [ "EventReader", "classhelios_1_1ecs_1_1EventReader.html", "classhelios_1_1ecs_1_1EventReader" ],
        [ "EventSimpleIterator", "classhelios_1_1ecs_1_1EventSimpleIterator.html", "classhelios_1_1ecs_1_1EventSimpleIterator" ],
        [ "EventWriter", "classhelios_1_1ecs_1_1EventWriter.html", "classhelios_1_1ecs_1_1EventWriter" ],
        [ "IsConstComponent", "structhelios_1_1ecs_1_1IsConstComponent.html", null ],
        [ "IsConstComponent< const T >", "structhelios_1_1ecs_1_1IsConstComponent_3_01const_01T_01_4.html", null ],
        [ "ShutdownEvent", "structhelios_1_1ecs_1_1ShutdownEvent.html", "structhelios_1_1ecs_1_1ShutdownEvent" ],
        [ "System", "classhelios_1_1ecs_1_1System.html", "classhelios_1_1ecs_1_1System" ],
        [ "World", "classhelios_1_1ecs_1_1World.html", "classhelios_1_1ecs_1_1World" ],
        [ "WorldCmdBuffer", "classhelios_1_1ecs_1_1WorldCmdBuffer.html", "classhelios_1_1ecs_1_1WorldCmdBuffer" ]
      ] ],
      [ "example", "namespacehelios_1_1example.html", [
        [ "ExampleComponent", "structhelios_1_1example_1_1ExampleComponent.html", "structhelios_1_1example_1_1ExampleComponent" ],
        [ "ExampleModule", "structhelios_1_1example_1_1ExampleModule.html", "structhelios_1_1example_1_1ExampleModule" ],
        [ "ExampleResource", "structhelios_1_1example_1_1ExampleResource.html", "structhelios_1_1example_1_1ExampleResource" ],
        [ "ExampleSystem", "structhelios_1_1example_1_1ExampleSystem.html", "structhelios_1_1example_1_1ExampleSystem" ]
      ] ],
      [ "memory", "namespacehelios_1_1memory.html", [
        [ "AllocationResult", "structhelios_1_1memory_1_1AllocationResult.html", "structhelios_1_1memory_1_1AllocationResult" ],
        [ "AllocatorStats", "structhelios_1_1memory_1_1AllocatorStats.html", "structhelios_1_1memory_1_1AllocatorStats" ],
        [ "ArenaAllocator", "classhelios_1_1memory_1_1ArenaAllocator.html", "classhelios_1_1memory_1_1ArenaAllocator" ],
        [ "DoubleFrameAllocator", "classhelios_1_1memory_1_1DoubleFrameAllocator.html", "classhelios_1_1memory_1_1DoubleFrameAllocator" ],
        [ "FrameAllocator", "classhelios_1_1memory_1_1FrameAllocator.html", "classhelios_1_1memory_1_1FrameAllocator" ],
        [ "FreeListAllocator", "classhelios_1_1memory_1_1FreeListAllocator.html", "classhelios_1_1memory_1_1FreeListAllocator" ],
        [ "GrowableAllocator", "classhelios_1_1memory_1_1GrowableAllocator.html", "classhelios_1_1memory_1_1GrowableAllocator" ],
        [ "NFrameAllocator", "classhelios_1_1memory_1_1NFrameAllocator.html", "classhelios_1_1memory_1_1NFrameAllocator" ],
        [ "PoolAllocator", "classhelios_1_1memory_1_1PoolAllocator.html", "classhelios_1_1memory_1_1PoolAllocator" ],
        [ "StackAllocator", "classhelios_1_1memory_1_1StackAllocator.html", "classhelios_1_1memory_1_1StackAllocator" ],
        [ "STLAllocatorAdapter", "classhelios_1_1memory_1_1STLAllocatorAdapter.html", "classhelios_1_1memory_1_1STLAllocatorAdapter" ]
      ] ],
      [ "utils", "namespacehelios_1_1utils.html", [
        [ "details", "namespacehelios_1_1utils_1_1details.html", [
          [ "folder_apply_result", "structhelios_1_1utils_1_1details_1_1folder__apply__result.html", null ],
          [ "folder_apply_result< Folder, Accumulator, std::tuple< TupleArgs... > >", "structhelios_1_1utils_1_1details_1_1folder__apply__result_3_01Folder_00_01Accumulator_00_01std_1ce2978c0f27b507bfe0e6e04cc632169.html", "structhelios_1_1utils_1_1details_1_1folder__apply__result_3_01Folder_00_01Accumulator_00_01std_1ce2978c0f27b507bfe0e6e04cc632169" ],
          [ "is_folder_applicable_impl", "structhelios_1_1utils_1_1details_1_1is__folder__applicable__impl.html", null ],
          [ "is_folder_applicable_impl< Folder, Accumulator, std::tuple< TupleArgs... > >", "structhelios_1_1utils_1_1details_1_1is__folder__applicable__impl_3_01Folder_00_01Accumulator_00_5474f6b3ac109ab26feda2bd4f995a76.html", null ],
          [ "UniqueTypesHelper", "structhelios_1_1utils_1_1details_1_1UniqueTypesHelper.html", null ],
          [ "UniqueTypesHelper< T, Rest... >", "structhelios_1_1utils_1_1details_1_1UniqueTypesHelper_3_01T_00_01Rest_8_8_8_01_4.html", null ]
        ] ],
        [ "ChainAdapter", "classhelios_1_1utils_1_1ChainAdapter.html", "classhelios_1_1utils_1_1ChainAdapter" ],
        [ "Defer", "classhelios_1_1utils_1_1Defer.html", "classhelios_1_1utils_1_1Defer" ],
        [ "DynamicLibrary", "classhelios_1_1utils_1_1DynamicLibrary.html", "classhelios_1_1utils_1_1DynamicLibrary" ],
        [ "EnumerateAdapter", "classhelios_1_1utils_1_1EnumerateAdapter.html", "classhelios_1_1utils_1_1EnumerateAdapter" ],
        [ "FastPimpl", "classhelios_1_1utils_1_1FastPimpl.html", "classhelios_1_1utils_1_1FastPimpl" ],
        [ "FilterAdapter", "classhelios_1_1utils_1_1FilterAdapter.html", "classhelios_1_1utils_1_1FilterAdapter" ],
        [ "FunctionalAdapterBase", "classhelios_1_1utils_1_1FunctionalAdapterBase.html", null ],
        [ "InspectAdapter", "classhelios_1_1utils_1_1InspectAdapter.html", "classhelios_1_1utils_1_1InspectAdapter" ],
        [ "JoinAdapter", "classhelios_1_1utils_1_1JoinAdapter.html", null ],
        [ "MapAdapter", "classhelios_1_1utils_1_1MapAdapter.html", "classhelios_1_1utils_1_1MapAdapter" ],
        [ "ReverseAdapter", "classhelios_1_1utils_1_1ReverseAdapter.html", "classhelios_1_1utils_1_1ReverseAdapter" ],
        [ "SkipAdapter", "classhelios_1_1utils_1_1SkipAdapter.html", "classhelios_1_1utils_1_1SkipAdapter" ],
        [ "SkipWhileAdapter", "classhelios_1_1utils_1_1SkipWhileAdapter.html", "classhelios_1_1utils_1_1SkipWhileAdapter" ],
        [ "SlideAdapter", "classhelios_1_1utils_1_1SlideAdapter.html", null ],
        [ "StepByAdapter", "classhelios_1_1utils_1_1StepByAdapter.html", "classhelios_1_1utils_1_1StepByAdapter" ],
        [ "StrideAdapter", "classhelios_1_1utils_1_1StrideAdapter.html", null ],
        [ "StringEqual", "structhelios_1_1utils_1_1StringEqual.html", "structhelios_1_1utils_1_1StringEqual" ],
        [ "StringHash", "structhelios_1_1utils_1_1StringHash.html", "structhelios_1_1utils_1_1StringHash" ],
        [ "TakeAdapter", "classhelios_1_1utils_1_1TakeAdapter.html", "classhelios_1_1utils_1_1TakeAdapter" ],
        [ "TakeWhileAdapter", "classhelios_1_1utils_1_1TakeWhileAdapter.html", "classhelios_1_1utils_1_1TakeWhileAdapter" ],
        [ "ZipAdapter", "classhelios_1_1utils_1_1ZipAdapter.html", null ]
      ] ],
      [ "DefaultLogger", "structhelios_1_1DefaultLogger.html", "structhelios_1_1DefaultLogger" ],
      [ "Delegate", "classhelios_1_1Delegate.html", null ],
      [ "Delegate< ReturnType(Args...)>", "classhelios_1_1Delegate_3_01ReturnType_07Args_8_8_8_08_4.html", "classhelios_1_1Delegate_3_01ReturnType_07Args_8_8_8_08_4" ],
      [ "Logger", "classhelios_1_1Logger.html", "classhelios_1_1Logger" ],
      [ "LoggerConfig", "structhelios_1_1LoggerConfig.html", "structhelios_1_1LoggerConfig" ],
      [ "RandomGenerator", "classhelios_1_1RandomGenerator.html", "classhelios_1_1RandomGenerator" ],
      [ "Timer", "classhelios_1_1Timer.html", "classhelios_1_1Timer" ],
      [ "Timestep", "classhelios_1_1Timestep.html", "classhelios_1_1Timestep" ],
      [ "Uuid", "classhelios_1_1Uuid.html", "classhelios_1_1Uuid" ],
      [ "UuidGenerator", "classhelios_1_1UuidGenerator.html", "classhelios_1_1UuidGenerator" ]
    ] ],
    [ "std", "namespacestd.html", [
      [ "hash< helios::ecs::ComponentTypeInfo >", "structstd_1_1hash_3_01helios_1_1ecs_1_1ComponentTypeInfo_01_4.html", "structstd_1_1hash_3_01helios_1_1ecs_1_1ComponentTypeInfo_01_4" ],
      [ "hash< helios::ecs::Entity >", "structstd_1_1hash_3_01helios_1_1ecs_1_1Entity_01_4.html", "structstd_1_1hash_3_01helios_1_1ecs_1_1Entity_01_4" ],
      [ "hash< helios::Uuid >", "structstd_1_1hash_3_01helios_1_1Uuid_01_4.html", "structstd_1_1hash_3_01helios_1_1Uuid_01_4" ]
    ] ]
];