#pragma once

#include <helios/config.hpp>

#if HELIOS_MODULE_HEADER_IMPORT
import helios.ecs;
#define HELIOS_MODULE_CONSUMER_SHIM
#endif

#ifndef HELIOS_MODULE_CONSUMER_SHIM
#include <helios/ecs/builtin_commands.hpp>
#include <helios/ecs/builtin_messages.hpp>
#include <helios/ecs/command/command.hpp>
#include <helios/ecs/command/commands.hpp>
#include <helios/ecs/command/entity_buffer.hpp>
#include <helios/ecs/command/queue.hpp>
#include <helios/ecs/command/world_buffer.hpp>
#include <helios/ecs/component/archetype.hpp>
#include <helios/ecs/component/archetype_id.hpp>
#include <helios/ecs/component/bundle.hpp>
#include <helios/ecs/component/component.hpp>
#include <helios/ecs/component/manager.hpp>
#include <helios/ecs/component/sparse_storage.hpp>
#include <helios/ecs/entity/entity.hpp>
#include <helios/ecs/entity/manager.hpp>
#include <helios/ecs/message/async_queue.hpp>
#include <helios/ecs/message/async_reader.hpp>
#include <helios/ecs/message/async_wrapper.hpp>
#include <helios/ecs/message/async_writer.hpp>
#include <helios/ecs/message/consumed_registry.hpp>
#include <helios/ecs/message/cursor.hpp>
#include <helios/ecs/message/id.hpp>
#include <helios/ecs/message/manager.hpp>
#include <helios/ecs/message/message.hpp>
#include <helios/ecs/message/params.hpp>
#include <helios/ecs/message/queue.hpp>
#include <helios/ecs/message/reader.hpp>
#include <helios/ecs/message/wrapper.hpp>
#include <helios/ecs/message/writer.hpp>
#include <helios/ecs/query/args.hpp>
#include <helios/ecs/query/details/traits.hpp>
#include <helios/ecs/query/iterator.hpp>
#include <helios/ecs/query/params.hpp>
#include <helios/ecs/query/query.hpp>
#include <helios/ecs/resource/manager.hpp>
#include <helios/ecs/resource/params.hpp>
#include <helios/ecs/resource/resource.hpp>
#include <helios/ecs/schedule/dag.hpp>
#include <helios/ecs/schedule/executor/executor.hpp>
#include <helios/ecs/schedule/executor/main_thread.hpp>
#include <helios/ecs/schedule/executor/multi_threaded.hpp>
#include <helios/ecs/schedule/executor/single_threaded.hpp>
#include <helios/ecs/schedule/local_arena.hpp>
#include <helios/ecs/schedule/run_condition.hpp>
#include <helios/ecs/schedule/run_scope.hpp>
#include <helios/ecs/schedule/run_stage_options.hpp>
#include <helios/ecs/schedule/schedule.hpp>
#include <helios/ecs/schedule/scheduler.hpp>
#include <helios/ecs/schedule/stage.hpp>
#include <helios/ecs/schedule/stage_settings.hpp>
#include <helios/ecs/schedule/system_group_handle.hpp>
#include <helios/ecs/schedule/system_handle.hpp>
#include <helios/ecs/schedule/system_local_data.hpp>
#include <helios/ecs/schedule/system_set.hpp>
#include <helios/ecs/schedule/system_set_handle.hpp>
#include <helios/ecs/schedule/system_storage.hpp>
#include <helios/ecs/system/access_decl.hpp>
#include <helios/ecs/system/access_policy.hpp>
#include <helios/ecs/system/composite_param.hpp>
#include <helios/ecs/system/param.hpp>
#include <helios/ecs/system/param_policy.hpp>
#include <helios/ecs/system/system.hpp>
#include <helios/ecs/world.hpp>
#include <helios/ecs/world_view.hpp>
#endif  // HELIOS_MODULE_CONSUMER_SHIM
