#pragma once

#if defined(HELIOS_ECS_ENABLE_PROFILE) && \
    defined(HELIOS_MODULE_PROFILE_AVAILABLE)
#define HELIOS_ENABLE_PROFILE
#include <helios/profile/macros.hpp>

#define HELIOS_ECS_PROFILE_SCOPE() HELIOS_PROFILE_SCOPE()
#define HELIOS_ECS_PROFILE_SCOPE_N(name) HELIOS_PROFILE_SCOPE_N(name)
#define HELIOS_ECS_PROFILE_SCOPE_IF(name, active) \
  HELIOS_PROFILE_SCOPE_IF(name, active)
#define HELIOS_ECS_PROFILE_ZONE_VALUE(value) HELIOS_PROFILE_ZONE_VALUE(value)
#define HELIOS_ECS_PROFILE_ZONE_NAME(name) HELIOS_PROFILE_ZONE_NAME(name)
#define HELIOS_ECS_PROFILE_ZONE_TEXT(text) HELIOS_PROFILE_ZONE_TEXT(text)

#undef HELIOS_ENABLE_PROFILE

#else

#define HELIOS_ECS_PROFILE_SCOPE()
#define HELIOS_ECS_PROFILE_SCOPE_N(name)
#define HELIOS_ECS_PROFILE_SCOPE_IF(name, active)
#define HELIOS_ECS_PROFILE_ZONE_VALUE(value)
#define HELIOS_ECS_PROFILE_ZONE_NAME(name)
#define HELIOS_ECS_PROFILE_ZONE_TEXT(text)

#endif
