#pragma once

#if defined(HELIOS_APP_ENABLE_PROFILE) && \
    defined(HELIOS_MODULE_PROFILE_AVAILABLE)
#define HELIOS_ENABLE_PROFILE
#include <helios/profile/macros.hpp>
#include <helios/profile/tracy/lock.hpp>

#define HELIOS_APP_PROFILE_SCOPE() HELIOS_PROFILE_SCOPE()
#define HELIOS_APP_PROFILE_SCOPE_N(name) HELIOS_PROFILE_SCOPE_N(name)
#define HELIOS_APP_PROFILE_SCOPE_IF(name, active) \
  HELIOS_PROFILE_SCOPE_IF(name, active)
#define HELIOS_APP_PROFILE_ZONE_VALUE(value) HELIOS_PROFILE_ZONE_VALUE(value)
#define HELIOS_APP_PROFILE_ZONE_NAME(name) HELIOS_PROFILE_ZONE_NAME(name)
#define HELIOS_APP_PROFILE_ZONE_TEXT(text) HELIOS_PROFILE_ZONE_TEXT(text)
#define HELIOS_APP_PROFILE_FRAME() HELIOS_PROFILE_FRAME()
#define HELIOS_APP_PROFILE_FRAME_START(name) HELIOS_PROFILE_FRAME_START(name)
#define HELIOS_APP_PROFILE_FRAME_END(name) HELIOS_PROFILE_FRAME_END(name)

#undef HELIOS_ENABLE_PROFILE

#else

#define HELIOS_APP_PROFILE_SCOPE()
#define HELIOS_APP_PROFILE_SCOPE_N(name)
#define HELIOS_APP_PROFILE_SCOPE_IF(name, active)
#define HELIOS_APP_PROFILE_ZONE_VALUE(value)
#define HELIOS_APP_PROFILE_ZONE_NAME(name)
#define HELIOS_APP_PROFILE_ZONE_TEXT(text)
#define HELIOS_APP_PROFILE_FRAME_START(name)
#define HELIOS_APP_PROFILE_FRAME_END(name)

#endif
