# Configure-time evaluation of generator expressions.
#
# helios_module() consumes DEPENDS while CMake is still configuring, so a
# generator expression stored for the native build tool never affects the
# module graph. This evaluates the subset that is already known: boolean
# constants and nesting of those constants. Expressions that depend on the
# build configuration or the compiler are returned unchanged.

include_guard(GLOBAL)

function(_helios_genex_depth STRING OUT)
  set(_depth 0)
  set(_index 0)
  string(LENGTH "${STRING}" _length)
  while(_index LESS _length)
    string(SUBSTRING "${STRING}" ${_index} 2 _pair)
    if(_pair STREQUAL "$<")
      math(EXPR _depth "${_depth} + 1")
      math(EXPR _index "${_index} + 2")
    else()
      string(SUBSTRING "${STRING}" ${_index} 1 _char)
      if(_char STREQUAL ">")
        math(EXPR _depth "${_depth} - 1")
      endif()
      math(EXPR _index "${_index} + 1")
    endif()
  endwhile()
  set(${OUT} "${_depth}" PARENT_SCOPE)
endfunction()

function(_helios_genex_end STRING OPEN OUT_END)
  set(_depth 1)
  math(EXPR _index "${OPEN} + 2")
  string(LENGTH "${STRING}" _length)
  while(_depth GREATER 0 AND _index LESS _length)
    string(SUBSTRING "${STRING}" ${_index} 2 _pair)
    if(_pair STREQUAL "$<")
      math(EXPR _depth "${_depth} + 1")
      math(EXPR _index "${_index} + 2")
    else()
      string(SUBSTRING "${STRING}" ${_index} 1 _char)
      if(_char STREQUAL ">")
        math(EXPR _depth "${_depth} - 1")
      endif()
      math(EXPR _index "${_index} + 1")
    endif()
  endwhile()
  if(NOT _depth EQUAL 0)
    message(FATAL_ERROR
        "helios_expand_configure_genex: unclosed generator expression in '${STRING}'")
  endif()
  set(${OUT_END} "${_index}" PARENT_SCOPE)
endfunction()

# Splits STRING on the first SEPARATOR that is not nested inside $<...>.
function(_helios_genex_split_first STRING SEPARATOR OUT_LEFT OUT_RIGHT OUT_FOUND)
  set(_left "")
  set(_depth 0)
  set(_index 0)
  set(_found FALSE)
  string(LENGTH "${STRING}" _length)
  while(_index LESS _length)
    string(SUBSTRING "${STRING}" ${_index} 2 _pair)
    if(_pair STREQUAL "$<")
      string(APPEND _left "$<")
      math(EXPR _depth "${_depth} + 1")
      math(EXPR _index "${_index} + 2")
    else()
      string(SUBSTRING "${STRING}" ${_index} 1 _char)
      if(_char STREQUAL ">" AND _depth GREATER 0)
        math(EXPR _depth "${_depth} - 1")
        string(APPEND _left "${_char}")
        math(EXPR _index "${_index} + 1")
      elseif(_char STREQUAL SEPARATOR AND _depth EQUAL 0)
        set(_found TRUE)
        math(EXPR _index "${_index} + 1")
        break()
      else()
        string(APPEND _left "${_char}")
        math(EXPR _index "${_index} + 1")
      endif()
    endif()
  endwhile()
  if(_found)
    string(SUBSTRING "${STRING}" ${_index} -1 _right)
  else()
    set(_right "")
  endif()
  set(${OUT_LEFT} "${_left}" PARENT_SCOPE)
  set(${OUT_RIGHT} "${_right}" PARENT_SCOPE)
  set(${OUT_FOUND} "${_found}" PARENT_SCOPE)
endfunction()

function(_helios_genex_split_all STRING SEPARATOR OUT_PARTS)
  set(_parts)
  set(_current "")
  set(_depth 0)
  set(_index 0)
  string(LENGTH "${STRING}" _length)
  while(_index LESS _length)
    string(SUBSTRING "${STRING}" ${_index} 2 _pair)
    if(_pair STREQUAL "$<")
      string(APPEND _current "$<")
      math(EXPR _depth "${_depth} + 1")
      math(EXPR _index "${_index} + 2")
    else()
      string(SUBSTRING "${STRING}" ${_index} 1 _char)
      if(_char STREQUAL ">" AND _depth GREATER 0)
        math(EXPR _depth "${_depth} - 1")
        string(APPEND _current "${_char}")
        math(EXPR _index "${_index} + 1")
      elseif(_char STREQUAL SEPARATOR AND _depth EQUAL 0)
        list(APPEND _parts "${_current}")
        set(_current "")
        math(EXPR _index "${_index} + 1")
      else()
        string(APPEND _current "${_char}")
        math(EXPR _index "${_index} + 1")
      endif()
    endif()
  endwhile()
  list(APPEND _parts "${_current}")
  set(${OUT_PARTS} "${_parts}" PARENT_SCOPE)
endfunction()

# CMake $<BOOL:string> constants. Any other string stays deferred so the
# generator applies the same rule later; in particular $<BOOL:SOME_NAME>
# is not a variable lookup.
function(_helios_bool_constant TEXT OUT_VALUE OUT_IS)
  if(TEXT STREQUAL "" OR TEXT MATCHES "-NOTFOUND$")
    set(${OUT_VALUE} "0" PARENT_SCOPE)
    set(${OUT_IS} TRUE PARENT_SCOPE)
    return()
  endif()
  string(TOUPPER "${TEXT}" _upper)
  set(_false 0 FALSE OFF N NO IGNORE NOTFOUND)
  set(_true 1 TRUE ON Y YES)
  if(_upper IN_LIST _false OR TEXT MATCHES "^0+$")
    set(${OUT_VALUE} "0" PARENT_SCOPE)
    set(${OUT_IS} TRUE PARENT_SCOPE)
  elseif(_upper IN_LIST _true OR TEXT MATCHES "^[1-9][0-9]*$")
    set(${OUT_VALUE} "1" PARENT_SCOPE)
    set(${OUT_IS} TRUE PARENT_SCOPE)
  else()
    set(${OUT_VALUE} "" PARENT_SCOPE)
    set(${OUT_IS} FALSE PARENT_SCOPE)
  endif()
endfunction()

macro(_helios_genex_defer ORIGINAL)
  set(${OUT_TEXT} "${ORIGINAL}" PARENT_SCOPE)
  set(${OUT_MODE} "DEFERRED" PARENT_SCOPE)
  return()
endmacro()

macro(_helios_genex_static VALUE)
  set(${OUT_TEXT} "${VALUE}" PARENT_SCOPE)
  set(${OUT_MODE} "STATIC" PARENT_SCOPE)
  return()
endmacro()

function(_helios_eval_genex_expr EXPR OUT_TEXT OUT_MODE)
  set(_result "")
  set(_index 0)
  string(LENGTH "${EXPR}" _length)
  while(_index LESS _length)
    string(SUBSTRING "${EXPR}" ${_index} 2 _pair)
    if(_pair STREQUAL "$<")
      _helios_genex_end("${EXPR}" ${_index} _end)
      math(EXPR _genex_length "${_end} - ${_index}")
      string(SUBSTRING "${EXPR}" ${_index} ${_genex_length} _genex)
      _helios_eval_one_genex("${_genex}" _piece _piece_mode)
      if(_piece_mode STREQUAL "DEFERRED")
        _helios_genex_defer("${EXPR}")
      endif()
      string(APPEND _result "${_piece}")
      set(_index "${_end}")
    else()
      string(SUBSTRING "${EXPR}" ${_index} 1 _char)
      string(APPEND _result "${_char}")
      math(EXPR _index "${_index} + 1")
    endif()
  endwhile()
  _helios_genex_static("${_result}")
endfunction()

function(_helios_eval_one_genex GENEX OUT_TEXT OUT_MODE)
  string(LENGTH "${GENEX}" _length)
  math(EXPR _inner_length "${_length} - 3")
  if(_inner_length LESS 0)
    _helios_genex_defer("${GENEX}")
  endif()
  string(SUBSTRING "${GENEX}" 2 ${_inner_length} _inner)
  _helios_genex_split_first("${_inner}" ":" _key _rest _has_colon)
  if(NOT _has_colon)
    _helios_genex_defer("${GENEX}")
  endif()

  if(_key STREQUAL "0")
    _helios_genex_static("")
  elseif(_key STREQUAL "1")
    _helios_eval_genex_expr("${_rest}" _text _mode)
    if(_mode STREQUAL "DEFERRED")
      _helios_genex_defer("${GENEX}")
    endif()
    _helios_genex_static("${_text}")
  elseif(_key STREQUAL "BOOL")
    _helios_eval_genex_expr("${_rest}" _text _mode)
    if(NOT _mode STREQUAL "STATIC")
      _helios_genex_defer("${GENEX}")
    endif()
    _helios_bool_constant("${_text}" _bit _is_constant)
    if(NOT _is_constant)
      _helios_genex_defer("${GENEX}")
    endif()
    _helios_genex_static("${_bit}")
  elseif(_key STREQUAL "AND" OR _key STREQUAL "OR")
    _helios_genex_split_all("${_rest}" "," _parts)
    set(_saw_true FALSE)
    set(_saw_false FALSE)
    set(_saw_other FALSE)
    foreach(_part IN LISTS _parts)
      _helios_eval_genex_expr("${_part}" _part_text _part_mode)
      if(NOT _part_mode STREQUAL "STATIC")
        set(_saw_other TRUE)
        continue()
      endif()
      _helios_bool_constant("${_part_text}" _bit _is_constant)
      if(NOT _is_constant)
        set(_saw_other TRUE)
      elseif(_bit STREQUAL "1")
        set(_saw_true TRUE)
      else()
        set(_saw_false TRUE)
      endif()
    endforeach()
    if(_key STREQUAL "AND")
      if(_saw_false)
        _helios_genex_static("0")
      elseif(_saw_other)
        _helios_genex_defer("${GENEX}")
      else()
        _helios_genex_static("1")
      endif()
    elseif(_saw_true)
      _helios_genex_static("1")
    elseif(_saw_other)
      _helios_genex_defer("${GENEX}")
    else()
      _helios_genex_static("0")
    endif()
  elseif(_key STREQUAL "NOT")
    _helios_genex_split_all("${_rest}" "," _parts)
    list(LENGTH _parts _count)
    if(NOT _count EQUAL 1)
      message(FATAL_ERROR
          "helios_expand_configure_genex: $<NOT:...> expects one condition in '${GENEX}'")
    endif()
    list(GET _parts 0 _part)
    _helios_eval_genex_expr("${_part}" _part_text _part_mode)
    if(NOT _part_mode STREQUAL "STATIC")
      _helios_genex_defer("${GENEX}")
    endif()
    _helios_bool_constant("${_part_text}" _bit _is_constant)
    if(NOT _is_constant)
      _helios_genex_defer("${GENEX}")
    elseif(_bit STREQUAL "1")
      _helios_genex_static("0")
    else()
      _helios_genex_static("1")
    endif()
  elseif(_key STREQUAL "IF")
    _helios_genex_split_all("${_rest}" "," _parts)
    list(LENGTH _parts _count)
    if(NOT _count EQUAL 3)
      message(FATAL_ERROR
          "helios_expand_configure_genex: $<IF:cond,true,false> expected in '${GENEX}'")
    endif()
    list(GET _parts 0 _cond_expr)
    list(GET _parts 1 _true_expr)
    list(GET _parts 2 _false_expr)
    _helios_eval_genex_expr("${_cond_expr}" _cond_text _cond_mode)
    if(NOT _cond_mode STREQUAL "STATIC")
      _helios_genex_defer("${GENEX}")
    endif()
    _helios_bool_constant("${_cond_text}" _bit _is_constant)
    if(NOT _is_constant)
      _helios_genex_defer("${GENEX}")
    elseif(_bit STREQUAL "1")
      set(_chosen "${_true_expr}")
    else()
      set(_chosen "${_false_expr}")
    endif()
    _helios_eval_genex_expr("${_chosen}" _text _mode)
    if(_mode STREQUAL "DEFERRED")
      _helios_genex_defer("${GENEX}")
    endif()
    _helios_genex_static("${_text}")
  else()
    string(SUBSTRING "${_key}" 0 2 _key_prefix)
    if(NOT _key_prefix STREQUAL "$<")
      _helios_genex_defer("${GENEX}")
    endif()
    _helios_eval_genex_expr("${_key}" _cond_text _cond_mode)
    if(NOT _cond_mode STREQUAL "STATIC")
      _helios_genex_defer("${GENEX}")
    endif()
    _helios_bool_constant("${_cond_text}" _bit _is_constant)
    if(NOT _is_constant)
      _helios_genex_defer("${GENEX}")
    elseif(_bit STREQUAL "0")
      _helios_genex_static("")
    endif()
    _helios_eval_genex_expr("${_rest}" _text _mode)
    if(_mode STREQUAL "DEFERRED")
      _helios_genex_defer("${GENEX}")
    endif()
    _helios_genex_static("${_text}")
  endif()
endfunction()

#[[
    helios_expand_configure_genex(
        INPUT <items...>
        OUTPUT <out-var>
    )

    Joins generator expressions that CMake split on whitespace, then folds
    conditions known at configure time.

    `$<$<BOOL:${SOME_OPTION}>:PUBLIC module>` becomes `PUBLIC;module` when
    SOME_OPTION is a true constant and disappears when it is false. `$<BOOL>`
    does not read variables: `${SOME_OPTION}` must supply `ON` or `OFF`.
    `$<CONFIG:...>`, `$<COMPILE_LANGUAGE:...>`, and `$<BOOL:literal_name>`
    are preserved for the generator.

    Example:
        helios_expand_configure_genex(
            INPUT "$<$<BOOL:ON>:PUBLIC" "module>" PUBLIC helios_core
            OUTPUT expanded
        )
]]
function(helios_expand_configure_genex)
  set(options "")
  set(oneValueArgs OUTPUT)
  set(multiValueArgs INPUT)
  cmake_parse_arguments(ARG "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

  if(NOT ARG_OUTPUT)
    message(FATAL_ERROR "helios_expand_configure_genex: OUTPUT is required")
  endif()
  if(NOT ARG_INPUT)
    set(${ARG_OUTPUT} "" PARENT_SCOPE)
    return()
  endif()

  set(_joined)
  set(_pending "")
  set(_depth 0)
  foreach(_item IN LISTS ARG_INPUT)
    if(_depth GREATER 0)
      set(_pending "${_pending} ${_item}")
    else()
      set(_pending "${_item}")
    endif()
    _helios_genex_depth("${_pending}" _depth)
    if(_depth EQUAL 0)
      list(APPEND _joined "${_pending}")
      set(_pending "")
    elseif(_depth LESS 0)
      message(FATAL_ERROR
          "helios_expand_configure_genex: unmatched '>' in '${_pending}'")
    endif()
  endforeach()
  if(_depth GREATER 0)
    message(FATAL_ERROR
        "helios_expand_configure_genex: unclosed generator expression in '${_pending}'")
  endif()

  set(_expanded)
  foreach(_item IN LISTS _joined)
    _helios_eval_genex_expr("${_item}" _text _mode)
    if(_mode STREQUAL "DEFERRED")
      list(APPEND _expanded "${_item}")
    elseif(NOT _text STREQUAL "")
      separate_arguments(_tokens UNIX_COMMAND "${_text}")
      list(APPEND _expanded ${_tokens})
    endif()
  endforeach()
  set(${ARG_OUTPUT} "${_expanded}" PARENT_SCOPE)
endfunction()
