[module]
name = "helios_ecs"
version = "0.1.0"
description = "Entity Component System module"
languages = ["cpp"]
default = true
implements = []
c_api = true

[build]
system = "cmake"

[dependencies]
public = ["helios_async", "helios_compiler", "helios_container", "helios_core", "helios_log", "helios_memory", "helios_platform", "helios_utils"]
private = []

[dependencies.optional]
public = ["helios_profile"]
private = []

[features.enable_profile]
default = true
abi = false
description = "Enable profiling in the helios_ecs module if helios_profile module is available"
