var hierarchy =
[
    [ "helios::ecs::AccessPolicy", "classhelios_1_1ecs_1_1AccessPolicy.html", null ],
    [ "helios::ecs::AccessPolicyBuilder", "classhelios_1_1ecs_1_1AccessPolicyBuilder.html", null ],
    [ "helios::utils::details::adapter_iterator_traits&lt; Iter &gt;", "structhelios_1_1utils_1_1details_1_1adapter__iterator__traits.html", null ],
    [ "helios::ecs::AddBundleCmd&lt; B &gt;", "classhelios_1_1ecs_1_1AddBundleCmd.html", null ],
    [ "helios::ecs::AddComponentsCmd&lt; Ts &gt;", "classhelios_1_1ecs_1_1AddComponentsCmd.html", null ],
    [ "anonymous_namespace{free_list_allocator.cpp}::AllocationHeader", "structanonymous__namespace_02free__list__allocator_8cpp_03_1_1AllocationHeader.html", null ],
    [ "helios::mem::AllocatorStats", "structhelios_1_1mem_1_1AllocatorStats.html", null ],
    [ "helios::ecs::AnyMessageId", "structhelios_1_1ecs_1_1AnyMessageId.html", null ],
    [ "helios::app::App", "classhelios_1_1app_1_1App.html", null ],
    [ "helios::window::AppearanceMessages", "structhelios_1_1window_1_1AppearanceMessages.html", null ],
    [ "helios::window::AppearanceWriters", "structhelios_1_1window_1_1AppearanceWriters.html", null ],
    [ "helios::app::AppExit", "structhelios_1_1app_1_1AppExit.html", null ],
    [ "helios::glfw::ApplyChanges", "structhelios_1_1glfw_1_1ApplyChanges.html", null ],
    [ "helios::sdl3::window::ApplyChanges", "structhelios_1_1sdl3_1_1window_1_1ApplyChanges.html", null ],
    [ "helios::sdl3::input::ApplyCursors", "structhelios_1_1sdl3_1_1input_1_1ApplyCursors.html", null ],
    [ "helios::sdl3::input::ApplyGamepadMappings", "structhelios_1_1sdl3_1_1input_1_1ApplyGamepadMappings.html", null ],
    [ "helios::sdl3::input::ApplyGamepadOutputs", "structhelios_1_1sdl3_1_1input_1_1ApplyGamepadOutputs.html", null ],
    [ "helios::sdl3::input::ApplyRawMouseMotion", "structhelios_1_1sdl3_1_1input_1_1ApplyRawMouseMotion.html", null ],
    [ "helios::sdl3::input::ApplySet", "structhelios_1_1sdl3_1_1input_1_1ApplySet.html", null ],
    [ "helios::sdl3::window::ApplySet", "structhelios_1_1sdl3_1_1window_1_1ApplySet.html", null ],
    [ "helios::mem::ArcFromThis&lt; Derived &gt;", "classhelios_1_1mem_1_1ArcFromThis.html", null ],
    [ "helios::ecs::Archetype", "classhelios_1_1ecs_1_1Archetype.html", null ],
    [ "helios::ecs::ArchetypeId", "classhelios_1_1ecs_1_1ArchetypeId.html", null ],
    [ "helios::mem::ArenaOptions", "structhelios_1_1mem_1_1ArenaOptions.html", null ],
    [ "helios::ecs::AsyncMessageQueue", "classhelios_1_1ecs_1_1AsyncMessageQueue.html", null ],
    [ "helios::ecs::AsyncMessageReader&lt; T &gt;", "classhelios_1_1ecs_1_1AsyncMessageReader.html", null ],
    [ "helios::ecs::details::AsyncMessageStorage", "classhelios_1_1ecs_1_1details_1_1AsyncMessageStorage.html", [
      [ "helios::ecs::TypedAsyncMessageStorage< T >", "classhelios_1_1ecs_1_1TypedAsyncMessageStorage.html", null ]
    ] ],
    [ "helios::ecs::AsyncMessageWrapper&lt; T &gt;", "classhelios_1_1ecs_1_1AsyncMessageWrapper.html", null ],
    [ "helios::ecs::AsyncMessageWriter&lt; T &gt;", "classhelios_1_1ecs_1_1AsyncMessageWriter.html", null ],
    [ "helios::async::AsyncTask", "classhelios_1_1async_1_1AsyncTask.html", null ],
    [ "helios::mem::AtomicRefCounted&lt; Derived &gt;", "classhelios_1_1mem_1_1AtomicRefCounted.html", null ],
    [ "helios::input::Axis&lt; T &gt;", "classhelios_1_1input_1_1Axis.html", null ],
    [ "helios::input::AxisFilter", "structhelios_1_1input_1_1AxisFilter.html", null ],
    [ "helios::profile::Backend", "classhelios_1_1profile_1_1Backend.html", [
      [ "helios::profile::FlamegraphBackend", "classhelios_1_1profile_1_1FlamegraphBackend.html", null ],
      [ "helios::profile::TracyBackend", "classhelios_1_1profile_1_1TracyBackend.html", null ]
    ] ],
    [ "helios::BasicCStringView&lt; CharT, Traits &gt;", "classhelios_1_1BasicCStringView.html", null ],
    [ "helios::ecs::BasicMessageWriter&lt; T &gt;", "classhelios_1_1ecs_1_1BasicMessageWriter.html", null ],
    [ "helios::ecs::BasicQuery&lt; WorldT, Args &gt;", "classhelios_1_1ecs_1_1BasicQuery.html", null ],
    [ "helios::ecs::BasicQueryWithEntity&lt; WorldT, Args &gt;", "classhelios_1_1ecs_1_1BasicQueryWithEntity.html", null ],
    [ "helios::container::BasicStaticString&lt; StrCapacity, CharT, Traits &gt;", "classhelios_1_1container_1_1BasicStaticString.html", null ],
    [ "std::bool_constant", null, [
      [ "helios::ecs::details::IsStructComponentBundle< T, true >", "structhelios_1_1ecs_1_1details_1_1IsStructComponentBundle_3_01T_00_01true_01_4.html", null ],
      [ "helios::utils::details::UniqueTypesHelper< T, Rest... >", "structhelios_1_1utils_1_1details_1_1UniqueTypesHelper_3_01T_00_01Rest_8_8_8_01_4.html", null ],
      [ "helios::utils::details::is_folder_applicable_impl< Folder, Accumulator, std::tuple< TupleArgs... > >", "structhelios_1_1utils_1_1details_1_1is__folder__applicable__impl_3_01Folder_00_01Accumulator_00_5474f6b3ac109ab26feda2bd4f995a76.html", null ]
    ] ],
    [ "helios::ecs::details::BundleTypeListImpl&lt; Bundle &gt;", "structhelios_1_1ecs_1_1details_1_1BundleTypeListImpl.html", null ],
    [ "helios::ecs::details::BundleTypeListImpl&lt; ComponentBundleTypes&lt; Ts... &gt; &gt;", "structhelios_1_1ecs_1_1details_1_1BundleTypeListImpl_3_01ComponentBundleTypes_3_01Ts_8_8_8_01_4_01_4.html", null ],
    [ "helios::ecs::details::BundleTypeListImpl&lt; T &gt;", "structhelios_1_1ecs_1_1details_1_1BundleTypeListImpl_3_01T_01_4.html", null ],
    [ "helios::input::ButtonInput&lt; T &gt;", "classhelios_1_1input_1_1ButtonInput.html", null ],
    [ "helios::container::CallableBuffer&lt; Signatures &gt;", "classhelios_1_1container_1_1CallableBuffer.html", null ],
    [ "helios::container::CallableBufferArray&lt; Signatures &gt;", "classhelios_1_1container_1_1CallableBufferArray.html", null ],
    [ "helios::details::CallableTraits&lt; Callable &gt;", "structhelios_1_1details_1_1CallableTraits.html", null ],
    [ "helios::glfw::anonymous_namespace{callbacks.cpp}::CallbackContext", "structhelios_1_1glfw_1_1anonymous__namespace_02callbacks_8cpp_03_1_1CallbackContext.html", null ],
    [ "anonymous_namespace{stacktrace.cpp}::CapturedFramesResult", "structanonymous__namespace_02stacktrace_8cpp_03_1_1CapturedFramesResult.html", null ],
    [ "helios::utils::ChunkView&lt; Iter &gt;", "classhelios_1_1utils_1_1ChunkView.html", null ],
    [ "helios::ecs::ClearAllMessagesCmd", "structhelios_1_1ecs_1_1ClearAllMessagesCmd.html", null ],
    [ "helios::ecs::ClearComponentsCmd", "classhelios_1_1ecs_1_1ClearComponentsCmd.html", null ],
    [ "helios::input::ClearInputState", "structhelios_1_1input_1_1ClearInputState.html", null ],
    [ "helios::ecs::ClearMessagesCmd&lt; T &gt;", "structhelios_1_1ecs_1_1ClearMessagesCmd.html", null ],
    [ "helios::window::ClientResizedMsg", "structhelios_1_1window_1_1ClientResizedMsg.html", null ],
    [ "helios::window::Clipboard", "structhelios_1_1window_1_1Clipboard.html", null ],
    [ "helios::window::ClipboardChangedMsg", "structhelios_1_1window_1_1ClipboardChangedMsg.html", null ],
    [ "helios::window::ClosedMsg", "structhelios_1_1window_1_1ClosedMsg.html", null ],
    [ "helios::window::CloseRequestedMsg", "structhelios_1_1window_1_1CloseRequestedMsg.html", null ],
    [ "helios::ecs::CmdQueue", "classhelios_1_1ecs_1_1CmdQueue.html", null ],
    [ "helios::ecs::Commands", "classhelios_1_1ecs_1_1Commands.html", null ],
    [ "helios::ecs::ComponentAddedMsg&lt; T &gt;", "classhelios_1_1ecs_1_1ComponentAddedMsg.html", null ],
    [ "helios::ecs::details::ComponentBundleElementTypes&lt; T, IsNested &gt;", "structhelios_1_1ecs_1_1details_1_1ComponentBundleElementTypes.html", null ],
    [ "helios::ecs::details::ComponentBundleElementTypes&lt; ComponentBundleTypes&lt; Ts... &gt;, true &gt;", "structhelios_1_1ecs_1_1details_1_1ComponentBundleElementTypes_3_01ComponentBundleTypes_3_01Ts_8_8_8_01_4_00_01true_01_4.html", null ],
    [ "helios::ecs::details::ComponentBundleElementTypes&lt; T, false &gt;", "structhelios_1_1ecs_1_1details_1_1ComponentBundleElementTypes_3_01T_00_01false_01_4.html", null ],
    [ "helios::ecs::details::ComponentBundleElementTypes&lt; T, true &gt;", "structhelios_1_1ecs_1_1details_1_1ComponentBundleElementTypes_3_01T_00_01true_01_4.html", null ],
    [ "helios::ecs::details::ComponentBundleTypeInfo&lt; T &gt;", "structhelios_1_1ecs_1_1details_1_1ComponentBundleTypeInfo.html", null ],
    [ "helios::ecs::details::ComponentBundleTypeInfo&lt; ComponentBundleTypes&lt; Ts... &gt; &gt;", "structhelios_1_1ecs_1_1details_1_1ComponentBundleTypeInfo_3_01ComponentBundleTypes_3_01Ts_8_8_8_01_4_01_4.html", null ],
    [ "helios::ecs::ComponentBundleTypes&lt; Ts &gt;", "structhelios_1_1ecs_1_1ComponentBundleTypes.html", null ],
    [ "helios::ecs::ComponentConflictInfo", "structhelios_1_1ecs_1_1ComponentConflictInfo.html", null ],
    [ "helios::ecs::ComponentManager", "classhelios_1_1ecs_1_1ComponentManager.html", null ],
    [ "helios::ecs::ComponentMetadata", "structhelios_1_1ecs_1_1ComponentMetadata.html", null ],
    [ "helios::ecs::ComponentRemovedMsg&lt; T &gt;", "classhelios_1_1ecs_1_1ComponentRemovedMsg.html", null ],
    [ "helios::ecs::ComponentsClearedMsg", "classhelios_1_1ecs_1_1ComponentsClearedMsg.html", null ],
    [ "helios::ecs::ComponentTraits&lt; T &gt;", "structhelios_1_1ecs_1_1ComponentTraits.html", null ],
    [ "helios::ecs::ComponentTypeInfo", "classhelios_1_1ecs_1_1ComponentTypeInfo.html", null ],
    [ "helios::ecs::CompositeSystemParam&lt; Param, Fields &gt;", "structhelios_1_1ecs_1_1CompositeSystemParam.html", null ],
    [ "helios::ecs::CompositeSystemParam&lt; input::GamepadMessages, MessageReader&lt; input::GamepadConnectionMsg &gt;, MessageReader&lt; input::GamepadButtonInputMsg &gt;, MessageReader&lt; input::GamepadAxisChangedMsg &gt;, MessageReader&lt; input::GamepadRemappedMsg &gt;, MessageReader&lt; input::GamepadPowerChangedMsg &gt;, MessageReader&lt; input::GamepadSensorUpdateMsg &gt;, MessageReader&lt; input::GamepadTouchpadMsg &gt; &gt;", "structhelios_1_1ecs_1_1CompositeSystemParam.html", [
      [ "helios::ecs::SystemParamTraits< input::GamepadMessages >", "structhelios_1_1ecs_1_1SystemParamTraits_3_01input_1_1GamepadMessages_01_4.html", null ]
    ] ],
    [ "helios::ecs::CompositeSystemParam&lt; input::GamepadWriters, MessageWriter&lt; input::GamepadConnectionMsg &gt;, MessageWriter&lt; input::GamepadButtonInputMsg &gt;, MessageWriter&lt; input::GamepadAxisChangedMsg &gt;, MessageWriter&lt; input::GamepadRemappedMsg &gt;, MessageWriter&lt; input::GamepadPowerChangedMsg &gt;, MessageWriter&lt; input::GamepadSensorUpdateMsg &gt;, MessageWriter&lt; input::GamepadTouchpadMsg &gt; &gt;", "structhelios_1_1ecs_1_1CompositeSystemParam.html", [
      [ "helios::ecs::SystemParamTraits< input::GamepadWriters >", "structhelios_1_1ecs_1_1SystemParamTraits_3_01input_1_1GamepadWriters_01_4.html", null ]
    ] ],
    [ "helios::ecs::CompositeSystemParam&lt; input::JoystickMessages, MessageReader&lt; input::JoystickConnectionMsg &gt;, MessageReader&lt; input::JoystickButtonInputMsg &gt;, MessageReader&lt; input::JoystickAxisChangedMsg &gt;, MessageReader&lt; input::JoystickHatChangedMsg &gt; &gt;", "structhelios_1_1ecs_1_1CompositeSystemParam.html", [
      [ "helios::ecs::SystemParamTraits< input::JoystickMessages >", "structhelios_1_1ecs_1_1SystemParamTraits_3_01input_1_1JoystickMessages_01_4.html", null ]
    ] ],
    [ "helios::ecs::CompositeSystemParam&lt; input::JoystickWriters, MessageWriter&lt; input::JoystickConnectionMsg &gt;, MessageWriter&lt; input::JoystickButtonInputMsg &gt;, MessageWriter&lt; input::JoystickAxisChangedMsg &gt;, MessageWriter&lt; input::JoystickHatChangedMsg &gt; &gt;", "structhelios_1_1ecs_1_1CompositeSystemParam.html", [
      [ "helios::ecs::SystemParamTraits< input::JoystickWriters >", "structhelios_1_1ecs_1_1SystemParamTraits_3_01input_1_1JoystickWriters_01_4.html", null ]
    ] ],
    [ "helios::ecs::CompositeSystemParam&lt; input::KeyboardMessages, MessageReader&lt; input::KeyboardInputMsg &gt;, MessageReader&lt; input::TextInputMsg &gt; &gt;", "structhelios_1_1ecs_1_1CompositeSystemParam.html", [
      [ "helios::ecs::SystemParamTraits< input::KeyboardMessages >", "structhelios_1_1ecs_1_1SystemParamTraits_3_01input_1_1KeyboardMessages_01_4.html", null ]
    ] ],
    [ "helios::ecs::CompositeSystemParam&lt; input::KeyboardWriters, MessageWriter&lt; input::KeyboardInputMsg &gt;, MessageWriter&lt; input::TextInputMsg &gt; &gt;", "structhelios_1_1ecs_1_1CompositeSystemParam.html", [
      [ "helios::ecs::SystemParamTraits< input::KeyboardWriters >", "structhelios_1_1ecs_1_1SystemParamTraits_3_01input_1_1KeyboardWriters_01_4.html", null ]
    ] ],
    [ "helios::ecs::CompositeSystemParam&lt; input::Messages, input::KeyboardMessages, input::MouseMessages, input::GamepadMessages, input::JoystickMessages, input::PenMessages &gt;", "structhelios_1_1ecs_1_1CompositeSystemParam.html", [
      [ "helios::ecs::SystemParamTraits< input::Messages >", "structhelios_1_1ecs_1_1SystemParamTraits_3_01input_1_1Messages_01_4.html", null ]
    ] ],
    [ "helios::ecs::CompositeSystemParam&lt; input::MouseMessages, MessageReader&lt; input::MouseButtonInputMsg &gt;, MessageReader&lt; input::CursorMovedMsg &gt;, MessageReader&lt; input::MouseMotionMsg &gt;, MessageReader&lt; input::MouseWheelMsg &gt; &gt;", "structhelios_1_1ecs_1_1CompositeSystemParam.html", [
      [ "helios::ecs::SystemParamTraits< input::MouseMessages >", "structhelios_1_1ecs_1_1SystemParamTraits_3_01input_1_1MouseMessages_01_4.html", null ]
    ] ],
    [ "helios::ecs::CompositeSystemParam&lt; input::MouseWriters, MessageWriter&lt; input::MouseButtonInputMsg &gt;, MessageWriter&lt; input::CursorMovedMsg &gt;, MessageWriter&lt; input::MouseMotionMsg &gt;, MessageWriter&lt; input::MouseWheelMsg &gt; &gt;", "structhelios_1_1ecs_1_1CompositeSystemParam.html", [
      [ "helios::ecs::SystemParamTraits< input::MouseWriters >", "structhelios_1_1ecs_1_1SystemParamTraits_3_01input_1_1MouseWriters_01_4.html", null ]
    ] ],
    [ "helios::ecs::CompositeSystemParam&lt; input::PenMessages, MessageReader&lt; input::PenProximityMsg &gt;, MessageReader&lt; input::PenTouchMsg &gt;, MessageReader&lt; input::PenButtonInputMsg &gt;, MessageReader&lt; input::PenMovedMsg &gt;, MessageReader&lt; input::PenAxisChangedMsg &gt; &gt;", "structhelios_1_1ecs_1_1CompositeSystemParam.html", [
      [ "helios::ecs::SystemParamTraits< input::PenMessages >", "structhelios_1_1ecs_1_1SystemParamTraits_3_01input_1_1PenMessages_01_4.html", null ]
    ] ],
    [ "helios::ecs::CompositeSystemParam&lt; input::PenWriters, MessageWriter&lt; input::PenProximityMsg &gt;, MessageWriter&lt; input::PenTouchMsg &gt;, MessageWriter&lt; input::PenButtonInputMsg &gt;, MessageWriter&lt; input::PenMovedMsg &gt;, MessageWriter&lt; input::PenAxisChangedMsg &gt; &gt;", "structhelios_1_1ecs_1_1CompositeSystemParam.html", [
      [ "helios::ecs::SystemParamTraits< input::PenWriters >", "structhelios_1_1ecs_1_1SystemParamTraits_3_01input_1_1PenWriters_01_4.html", null ]
    ] ],
    [ "helios::ecs::CompositeSystemParam&lt; input::State, Res&lt; input::Keyboard &gt;, Res&lt; input::Mouse &gt;, Res&lt; input::Gamepads &gt;, Res&lt; input::Joysticks &gt;, Res&lt; input::Pens &gt; &gt;", "structhelios_1_1ecs_1_1CompositeSystemParam.html", [
      [ "helios::ecs::SystemParamTraits< input::State >", "structhelios_1_1ecs_1_1SystemParamTraits_3_01input_1_1State_01_4.html", null ]
    ] ],
    [ "helios::ecs::CompositeSystemParam&lt; input::StateView, Res&lt; const input::Keyboard &gt;, Res&lt; const input::Mouse &gt;, Res&lt; const input::Gamepads &gt;, Res&lt; const input::Joysticks &gt;, Res&lt; const input::Pens &gt; &gt;", "structhelios_1_1ecs_1_1CompositeSystemParam.html", [
      [ "helios::ecs::SystemParamTraits< input::StateView >", "structhelios_1_1ecs_1_1SystemParamTraits_3_01input_1_1StateView_01_4.html", null ]
    ] ],
    [ "helios::ecs::CompositeSystemParam&lt; input::Writers, input::KeyboardWriters, input::MouseWriters, input::GamepadWriters, input::JoystickWriters, input::PenWriters &gt;", "structhelios_1_1ecs_1_1CompositeSystemParam.html", [
      [ "helios::ecs::SystemParamTraits< input::Writers >", "structhelios_1_1ecs_1_1SystemParamTraits_3_01input_1_1Writers_01_4.html", null ]
    ] ],
    [ "helios::ecs::CompositeSystemParam&lt; window::AppearanceMessages, MessageReader&lt; window::ModeChangedMsg &gt;, MessageReader&lt; window::CursorModeChangedMsg &gt;, MessageReader&lt; window::VisibilityChangedMsg &gt;, MessageReader&lt; window::FocusChangedMsg &gt;, MessageReader&lt; window::MaximizedChangedMsg &gt;, MessageReader&lt; window::IconChangedMsg &gt;, MessageReader&lt; window::ResizableChangedMsg &gt;, MessageReader&lt; window::DecoratedChangedMsg &gt;, MessageReader&lt; window::OpacityChangedMsg &gt;, MessageReader&lt; window::FloatingChangedMsg &gt;, MessageReader&lt; window::HoverChangedMsg &gt;, MessageReader&lt; window::MousePassthroughChangedMsg &gt; &gt;", "structhelios_1_1ecs_1_1CompositeSystemParam.html", [
      [ "helios::ecs::SystemParamTraits< window::AppearanceMessages >", "structhelios_1_1ecs_1_1SystemParamTraits_3_01window_1_1AppearanceMessages_01_4.html", null ]
    ] ],
    [ "helios::ecs::CompositeSystemParam&lt; window::AppearanceWriters, MessageWriter&lt; window::ModeChangedMsg &gt;, MessageWriter&lt; window::CursorModeChangedMsg &gt;, MessageWriter&lt; window::VisibilityChangedMsg &gt;, MessageWriter&lt; window::FocusChangedMsg &gt;, MessageWriter&lt; window::MaximizedChangedMsg &gt;, MessageWriter&lt; window::IconChangedMsg &gt;, MessageWriter&lt; window::ResizableChangedMsg &gt;, MessageWriter&lt; window::DecoratedChangedMsg &gt;, MessageWriter&lt; window::OpacityChangedMsg &gt;, MessageWriter&lt; window::FloatingChangedMsg &gt;, MessageWriter&lt; window::HoverChangedMsg &gt;, MessageWriter&lt; window::MousePassthroughChangedMsg &gt; &gt;", "structhelios_1_1ecs_1_1CompositeSystemParam.html", [
      [ "helios::ecs::SystemParamTraits< window::AppearanceWriters >", "structhelios_1_1ecs_1_1SystemParamTraits_3_01window_1_1AppearanceWriters_01_4.html", null ]
    ] ],
    [ "helios::ecs::CompositeSystemParam&lt; window::CreationWriters, MessageWriter&lt; window::CreatedMsg &gt;, MessageWriter&lt; window::ContentScaleChangedMsg &gt;, MessageWriter&lt; window::CreationFailedMsg &gt; &gt;", "structhelios_1_1ecs_1_1CompositeSystemParam.html", [
      [ "helios::ecs::SystemParamTraits< window::CreationWriters >", "structhelios_1_1ecs_1_1SystemParamTraits_3_01window_1_1CreationWriters_01_4.html", null ]
    ] ],
    [ "helios::ecs::CompositeSystemParam&lt; window::GeometryMessages, MessageReader&lt; window::ResizedMsg &gt;, MessageReader&lt; window::ClientResizedMsg &gt;, MessageReader&lt; window::ContentScaleChangedMsg &gt;, MessageReader&lt; window::PosChangedMsg &gt; &gt;", "structhelios_1_1ecs_1_1CompositeSystemParam.html", [
      [ "helios::ecs::SystemParamTraits< window::GeometryMessages >", "structhelios_1_1ecs_1_1SystemParamTraits_3_01window_1_1GeometryMessages_01_4.html", null ]
    ] ],
    [ "helios::ecs::CompositeSystemParam&lt; window::GeometryWriters, MessageWriter&lt; window::ResizedMsg &gt;, MessageWriter&lt; window::ClientResizedMsg &gt;, MessageWriter&lt; window::ContentScaleChangedMsg &gt;, MessageWriter&lt; window::PosChangedMsg &gt; &gt;", "structhelios_1_1ecs_1_1CompositeSystemParam.html", [
      [ "helios::ecs::SystemParamTraits< window::GeometryWriters >", "structhelios_1_1ecs_1_1SystemParamTraits_3_01window_1_1GeometryWriters_01_4.html", null ]
    ] ],
    [ "helios::ecs::CompositeSystemParam&lt; window::LifecycleMessages, MessageReader&lt; window::CreatedMsg &gt;, MessageReader&lt; window::ClosedMsg &gt;, MessageReader&lt; window::CloseRequestedMsg &gt;, MessageReader&lt; window::CreationFailedMsg &gt; &gt;", "structhelios_1_1ecs_1_1CompositeSystemParam.html", [
      [ "helios::ecs::SystemParamTraits< window::LifecycleMessages >", "structhelios_1_1ecs_1_1SystemParamTraits_3_01window_1_1LifecycleMessages_01_4.html", null ]
    ] ],
    [ "helios::ecs::CompositeSystemParam&lt; window::LifecycleWriters, MessageWriter&lt; window::CreatedMsg &gt;, MessageWriter&lt; window::ClosedMsg &gt;, MessageWriter&lt; window::CloseRequestedMsg &gt;, MessageWriter&lt; window::CreationFailedMsg &gt; &gt;", "structhelios_1_1ecs_1_1CompositeSystemParam.html", [
      [ "helios::ecs::SystemParamTraits< window::LifecycleWriters >", "structhelios_1_1ecs_1_1SystemParamTraits_3_01window_1_1LifecycleWriters_01_4.html", null ]
    ] ],
    [ "helios::ecs::CompositeSystemParam&lt; window::Messages, window::LifecycleMessages, window::GeometryMessages, window::AppearanceMessages, window::PlatformMessages &gt;", "structhelios_1_1ecs_1_1CompositeSystemParam.html", [
      [ "helios::ecs::SystemParamTraits< window::Messages >", "structhelios_1_1ecs_1_1SystemParamTraits_3_01window_1_1Messages_01_4.html", null ]
    ] ],
    [ "helios::ecs::CompositeSystemParam&lt; window::PlatformMessages, MessageReader&lt; window::ClipboardChangedMsg &gt;, MessageReader&lt; window::DroppedFilesMsg &gt;, MessageReader&lt; window::MonitorConnectedMsg &gt;, MessageReader&lt; window::MonitorDisconnectedMsg &gt; &gt;", "structhelios_1_1ecs_1_1CompositeSystemParam.html", [
      [ "helios::ecs::SystemParamTraits< window::PlatformMessages >", "structhelios_1_1ecs_1_1SystemParamTraits_3_01window_1_1PlatformMessages_01_4.html", null ]
    ] ],
    [ "helios::ecs::CompositeSystemParam&lt; window::PlatformWriters, MessageWriter&lt; window::ClipboardChangedMsg &gt;, MessageWriter&lt; window::DroppedFilesMsg &gt;, MessageWriter&lt; window::MonitorConnectedMsg &gt;, MessageWriter&lt; window::MonitorDisconnectedMsg &gt; &gt;", "structhelios_1_1ecs_1_1CompositeSystemParam.html", [
      [ "helios::ecs::SystemParamTraits< window::PlatformWriters >", "structhelios_1_1ecs_1_1SystemParamTraits_3_01window_1_1PlatformWriters_01_4.html", null ]
    ] ],
    [ "helios::ecs::CompositeSystemParam&lt; window::PrimaryWindows, Query&lt; window::Window &amp;, With&lt; window::Primary &gt; &gt; &gt;", "structhelios_1_1ecs_1_1CompositeSystemParam.html", [
      [ "helios::ecs::SystemParamTraits< window::PrimaryWindows >", "structhelios_1_1ecs_1_1SystemParamTraits_3_01window_1_1PrimaryWindows_01_4.html", null ]
    ] ],
    [ "helios::ecs::CompositeSystemParam&lt; window::PrimaryWindowsView, Query&lt; const window::Window &amp;, With&lt; window::Primary &gt; &gt; &gt;", "structhelios_1_1ecs_1_1CompositeSystemParam.html", [
      [ "helios::ecs::SystemParamTraits< window::PrimaryWindowsView >", "structhelios_1_1ecs_1_1SystemParamTraits_3_01window_1_1PrimaryWindowsView_01_4.html", null ]
    ] ],
    [ "helios::ecs::CompositeSystemParam&lt; window::Windows, Query&lt; window::Window &amp; &gt; &gt;", "structhelios_1_1ecs_1_1CompositeSystemParam.html", [
      [ "helios::ecs::SystemParamTraits< window::Windows >", "structhelios_1_1ecs_1_1SystemParamTraits_3_01window_1_1Windows_01_4.html", null ]
    ] ],
    [ "helios::ecs::CompositeSystemParam&lt; window::WindowsView, Query&lt; const window::Window &amp; &gt; &gt;", "structhelios_1_1ecs_1_1CompositeSystemParam.html", [
      [ "helios::ecs::SystemParamTraits< window::WindowsView >", "structhelios_1_1ecs_1_1SystemParamTraits_3_01window_1_1WindowsView_01_4.html", null ]
    ] ],
    [ "helios::ecs::CompositeSystemParam&lt; window::Writers, window::LifecycleWriters, window::GeometryWriters, window::AppearanceWriters, window::PlatformWriters &gt;", "structhelios_1_1ecs_1_1CompositeSystemParam.html", [
      [ "helios::ecs::SystemParamTraits< window::Writers >", "structhelios_1_1ecs_1_1SystemParamTraits_3_01window_1_1Writers_01_4.html", null ]
    ] ],
    [ "helios::ecs::details::ConcatComponentBundleTypes&lt; Lists &gt;", "structhelios_1_1ecs_1_1details_1_1ConcatComponentBundleTypes.html", null ],
    [ "helios::ecs::details::ConcatComponentBundleTypes&lt; ComponentBundleTypes&lt; Ts... &gt; &gt;", "structhelios_1_1ecs_1_1details_1_1ConcatComponentBundleTypes_3_01ComponentBundleTypes_3_01Ts_8_8_8_01_4_01_4.html", null ],
    [ "helios::ecs::details::ConcatComponentBundleTypes&lt; ComponentBundleTypes&lt; Ts..., Us... &gt;, Rest... &gt;", "structhelios_1_1ecs_1_1details_1_1ConcatComponentBundleTypes.html", [
      [ "helios::ecs::details::ConcatComponentBundleTypes< ComponentBundleTypes< Ts... >, ComponentBundleTypes< Us... >, Rest... >", "structhelios_1_1ecs_1_1details_1_1ConcatComponentBundleTypes_3_01ComponentBundleTypes_3_01Ts_8_856cabb7cd9f34ca60a6c1a7e71e0b3d6.html", null ]
    ] ],
    [ "helios::ecs::details::ConcatComponentBundleTypes&lt;&gt;", "structhelios_1_1ecs_1_1details_1_1ConcatComponentBundleTypes_3_4.html", null ],
    [ "helios::log::Config", "structhelios_1_1log_1_1Config.html", null ],
    [ "helios::ecs::ConsumableMessageWrapper&lt; T &gt;", "classhelios_1_1ecs_1_1ConsumableMessageWrapper.html", null ],
    [ "helios::ecs::ConsumedMessagesRegistry", "classhelios_1_1ecs_1_1ConsumedMessagesRegistry.html", null ],
    [ "helios::window::ContentScaleChangedMsg", "structhelios_1_1window_1_1ContentScaleChangedMsg.html", null ],
    [ "helios::app::CountFrame", "structhelios_1_1app_1_1CountFrame.html", null ],
    [ "helios::window::CreatedMsg", "structhelios_1_1window_1_1CreatedMsg.html", null ],
    [ "helios::glfw::CreateNativeWindows", "structhelios_1_1glfw_1_1CreateNativeWindows.html", null ],
    [ "helios::sdl3::window::CreateNativeWindows", "structhelios_1_1sdl3_1_1window_1_1CreateNativeWindows.html", null ],
    [ "helios::sdl3::window::CreateSet", "structhelios_1_1sdl3_1_1window_1_1CreateSet.html", null ],
    [ "helios::window::CreationFailed", "structhelios_1_1window_1_1CreationFailed.html", null ],
    [ "helios::window::CreationFailedMsg", "structhelios_1_1window_1_1CreationFailedMsg.html", null ],
    [ "helios::window::CreationWriters", "structhelios_1_1window_1_1CreationWriters.html", null ],
    [ "helios::input::Cursor", "structhelios_1_1input_1_1Cursor.html", null ],
    [ "helios::input::CursorImage", "structhelios_1_1input_1_1CursorImage.html", null ],
    [ "helios::window::CursorModeChangedMsg", "structhelios_1_1window_1_1CursorModeChangedMsg.html", null ],
    [ "helios::input::CursorMovedMsg", "structhelios_1_1input_1_1CursorMovedMsg.html", null ],
    [ "helios::ecs::Dag", "classhelios_1_1ecs_1_1Dag.html", null ],
    [ "helios::ecs::DagError", "structhelios_1_1ecs_1_1DagError.html", null ],
    [ "helios::window::DecoratedChangedMsg", "structhelios_1_1window_1_1DecoratedChangedMsg.html", null ],
    [ "helios::container::DefaultCompare&lt; Key &gt;", "structhelios_1_1container_1_1DefaultCompare.html", null ],
    [ "helios::container::DefaultCompare&lt; const char * &gt;", "structhelios_1_1container_1_1DefaultCompare_3_01const_01char_01_5_01_4.html", null ],
    [ "helios::container::DefaultCompare&lt; std::string &gt;", "structhelios_1_1container_1_1DefaultCompare_3_01std_1_1string_01_4.html", null ],
    [ "helios::container::DefaultCompare&lt; std::string_view &gt;", "structhelios_1_1container_1_1DefaultCompare_3_01std_1_1string__view_01_4.html", null ],
    [ "helios::container::DefaultHash&lt; Key &gt;", "structhelios_1_1container_1_1DefaultHash.html", null ],
    [ "helios::container::DefaultHash&lt; const char * &gt;", "structhelios_1_1container_1_1DefaultHash_3_01const_01char_01_5_01_4.html", null ],
    [ "helios::container::DefaultHash&lt; std::string &gt;", "structhelios_1_1container_1_1DefaultHash_3_01std_1_1string_01_4.html", null ],
    [ "helios::container::DefaultHash&lt; std::string_view &gt;", "structhelios_1_1container_1_1DefaultHash_3_01std_1_1string__view_01_4.html", null ],
    [ "helios::log::DefaultLogger", "structhelios_1_1log_1_1DefaultLogger.html", null ],
    [ "helios::utils::Defer&lt; F &gt;", "classhelios_1_1utils_1_1Defer.html", null ],
    [ "helios::utils::details::DeferHelper", "structhelios_1_1utils_1_1details_1_1DeferHelper.html", null ],
    [ "helios::Delegate&lt; FunctionSignature &gt;", "classhelios_1_1Delegate.html", null ],
    [ "helios::Delegate&lt; ReturnType(Args...)&gt;", "classhelios_1_1Delegate_3_01ReturnType_07Args_8_8_8_08_4.html", null ],
    [ "helios::glfw::DestroyClosedWindows", "structhelios_1_1glfw_1_1DestroyClosedWindows.html", null ],
    [ "helios::sdl3::window::DestroyClosedWindows", "structhelios_1_1sdl3_1_1window_1_1DestroyClosedWindows.html", null ],
    [ "helios::ecs::DestroyEntitiesCmd", "classhelios_1_1ecs_1_1DestroyEntitiesCmd.html", null ],
    [ "helios::ecs::DestroyEntityCmd", "classhelios_1_1ecs_1_1DestroyEntityCmd.html", null ],
    [ "helios::window::DroppedFilesMsg", "structhelios_1_1window_1_1DroppedFilesMsg.html", null ],
    [ "helios::utils::DynamicLibrary", "classhelios_1_1utils_1_1DynamicLibrary.html", null ],
    [ "helios::app::DynamicPlugin", "classhelios_1_1app_1_1DynamicPlugin.html", null ],
    [ "helios::app::DynamicPluginConfig", "structhelios_1_1app_1_1DynamicPluginConfig.html", null ],
    [ "helios::ecs::Entity", "classhelios_1_1ecs_1_1Entity.html", null ],
    [ "helios::ecs::EntityAddedMsg", "classhelios_1_1ecs_1_1EntityAddedMsg.html", null ],
    [ "helios::ecs::EntityCmdBuffer", "classhelios_1_1ecs_1_1EntityCmdBuffer.html", null ],
    [ "helios::ecs::EntityDestroyedMsg", "classhelios_1_1ecs_1_1EntityDestroyedMsg.html", null ],
    [ "helios::ecs::EntityManager", "classhelios_1_1ecs_1_1EntityManager.html", null ],
    [ "helios::sdl3::EventPumpSet", "structhelios_1_1sdl3_1_1EventPumpSet.html", null ],
    [ "helios::window::Events", "structhelios_1_1window_1_1Events.html", null ],
    [ "helios::window::ExclusiveVideoMode", "structhelios_1_1window_1_1ExclusiveVideoMode.html", null ],
    [ "helios::app::Executor", "structhelios_1_1app_1_1Executor.html", null ],
    [ "helios::async::Executor", "classhelios_1_1async_1_1Executor.html", null ],
    [ "helios::ecs::Executor", "classhelios_1_1ecs_1_1Executor.html", [
      [ "helios::ecs::MainThreadExecutor", "classhelios_1_1ecs_1_1MainThreadExecutor.html", null ],
      [ "helios::ecs::MultiThreadedExecutor", "classhelios_1_1ecs_1_1MultiThreadedExecutor.html", null ],
      [ "helios::ecs::SingleThreadedExecutor", "classhelios_1_1ecs_1_1SingleThreadedExecutor.html", null ]
    ] ],
    [ "helios::app::Extract", "structhelios_1_1app_1_1Extract.html", null ],
    [ "helios::app::ExtractStage", "structhelios_1_1app_1_1ExtractStage.html", null ],
    [ "std::false_type", null, [
      [ "helios::ecs::details::HasStructBundleBuild< T >", "structhelios_1_1ecs_1_1details_1_1HasStructBundleBuild_3_01T_01_4.html", null ],
      [ "helios::ecs::details::IsComponentBundle< ComponentBundleTypes< Ts... > >", "structhelios_1_1ecs_1_1details_1_1IsComponentBundle_3_01ComponentBundleTypes_3_01Ts_8_8_8_01_4_01_4.html", null ],
      [ "helios::ecs::details::IsComponentBundle< T >", "structhelios_1_1ecs_1_1details_1_1IsComponentBundle_3_01T_01_4.html", null ],
      [ "helios::ecs::details::IsComponentBundleTypes< ComponentBundleTypes< Ts... > >", "structhelios_1_1ecs_1_1details_1_1IsComponentBundleTypes_3_01ComponentBundleTypes_3_01Ts_8_8_8_01_4_01_4.html", null ],
      [ "helios::ecs::details::IsStructComponentBundle< std::remove_cvref_t< T > >", "structhelios_1_1ecs_1_1details_1_1IsStructComponentBundle.html", [
        [ "helios::ecs::details::IsComponentBundle< T >", "structhelios_1_1ecs_1_1details_1_1IsComponentBundle_3_01T_01_4.html", null ]
      ] ],
      [ "helios::ecs::details::IsStructComponentBundle< T, true >", "structhelios_1_1ecs_1_1details_1_1IsStructComponentBundle_3_01T_00_01true_01_4.html", null ],
      [ "helios::utils::details::is_folder_applicable_impl< Folder, Accumulator, std::tuple< TupleArgs... > >", "structhelios_1_1utils_1_1details_1_1is__folder__applicable__impl_3_01Folder_00_01Accumulator_00_5474f6b3ac109ab26feda2bd4f995a76.html", null ],
      [ "helios::ecs::details::HasStructBundleBuild< T >", "structhelios_1_1ecs_1_1details_1_1HasStructBundleBuild.html", null ],
      [ "helios::ecs::details::IsComponentBundle< T >", "structhelios_1_1ecs_1_1details_1_1IsComponentBundle.html", null ],
      [ "helios::ecs::details::IsComponentBundleTypes< T >", "structhelios_1_1ecs_1_1details_1_1IsComponentBundleTypes.html", null ],
      [ "helios::ecs::details::IsStructComponentBundle< T, HasBuild >", "structhelios_1_1ecs_1_1details_1_1IsStructComponentBundle.html", null ],
      [ "helios::utils::details::is_folder_applicable_impl< Folder, Accumulator, Tuple >", "structhelios_1_1utils_1_1details_1_1is__folder__applicable__impl.html", null ]
    ] ],
    [ "helios::utils::FastPimpl&lt; T, Size, Alignment, RequireStrictMatch &gt;", "classhelios_1_1utils_1_1FastPimpl.html", null ],
    [ "helios::app::First", "structhelios_1_1app_1_1First.html", null ],
    [ "helios::mem::FixedPoolAllocatorOptions", "structhelios_1_1mem_1_1FixedPoolAllocatorOptions.html", null ],
    [ "helios::app::FixedRunnerConfig", "structhelios_1_1app_1_1FixedRunnerConfig.html", null ],
    [ "helios::utils::details::FixedString&lt; N &gt;", "structhelios_1_1utils_1_1details_1_1FixedString.html", null ],
    [ "helios::profile::FlamegraphBackendConfig", "structhelios_1_1profile_1_1FlamegraphBackendConfig.html", null ],
    [ "helios::container::FlatMap&lt; Key, Value, Compare, Hash &gt;", "classhelios_1_1container_1_1FlatMap.html", null ],
    [ "helios::window::FloatingChangedMsg", "structhelios_1_1window_1_1FloatingChangedMsg.html", null ],
    [ "helios::window::FocusChangedMsg", "structhelios_1_1window_1_1FocusChangedMsg.html", null ],
    [ "helios::utils::details::folder_apply_result&lt; Folder, Accumulator, Tuple &gt;", "structhelios_1_1utils_1_1details_1_1folder__apply__result.html", null ],
    [ "helios::utils::details::folder_apply_result&lt; Folder, Accumulator, std::tuple&lt; TupleArgs... &gt; &gt;", "structhelios_1_1utils_1_1details_1_1folder__apply__result_3_01Folder_00_01Accumulator_00_01std_1ce2978c0f27b507bfe0e6e04cc632169.html", null ],
    [ "formatter", null, [
      [ "std::formatter< helios::BasicCStringView< CharT, Traits > >", "structstd_1_1formatter_3_01helios_1_1BasicCStringView_3_01CharT_00_01Traits_01_4_01_4.html", null ],
      [ "std::formatter< helios::container::BasicStaticString< StrCapacity, CharT, Traits > >", "structstd_1_1formatter_3_01helios_1_1container_1_1BasicStaticString_3_01StrCapacity_00_01CharT_00_01Traits_01_4_01_4.html", null ]
    ] ],
    [ "std::formatter&lt; helios::ecs::ComponentAddedMsg&lt; T &gt; &gt;", "structstd_1_1formatter_3_01helios_1_1ecs_1_1ComponentAddedMsg_3_01T_01_4_01_4.html", null ],
    [ "std::formatter&lt; helios::ecs::ComponentRemovedMsg&lt; T &gt; &gt;", "structstd_1_1formatter_3_01helios_1_1ecs_1_1ComponentRemovedMsg_3_01T_01_4_01_4.html", null ],
    [ "std::formatter&lt; helios::ecs::ComponentsClearedMsg &gt;", "structstd_1_1formatter_3_01helios_1_1ecs_1_1ComponentsClearedMsg_01_4.html", null ],
    [ "std::formatter&lt; helios::ecs::Entity &gt;", "structstd_1_1formatter_3_01helios_1_1ecs_1_1Entity_01_4.html", null ],
    [ "std::formatter&lt; helios::ecs::EntityAddedMsg &gt;", "structstd_1_1formatter_3_01helios_1_1ecs_1_1EntityAddedMsg_01_4.html", null ],
    [ "std::formatter&lt; helios::ecs::EntityDestroyedMsg &gt;", "structstd_1_1formatter_3_01helios_1_1ecs_1_1EntityDestroyedMsg_01_4.html", null ],
    [ "std::formatter&lt; helios::ecs::ResourceInsertedMsg&lt; T &gt; &gt;", "structstd_1_1formatter_3_01helios_1_1ecs_1_1ResourceInsertedMsg_3_01T_01_4_01_4.html", null ],
    [ "std::formatter&lt; helios::ecs::ResourceRemovedMsg&lt; T &gt; &gt;", "structstd_1_1formatter_3_01helios_1_1ecs_1_1ResourceRemovedMsg_3_01T_01_4_01_4.html", null ],
    [ "std::formatter&lt; helios::input::AxisFilter &gt;", "structstd_1_1formatter_3_01helios_1_1input_1_1AxisFilter_01_4.html", null ],
    [ "std::formatter&lt; helios::input::ButtonState &gt;", "structstd_1_1formatter_3_01helios_1_1input_1_1ButtonState_01_4.html", null ],
    [ "std::formatter&lt; helios::input::Cursor &gt;", "structstd_1_1formatter_3_01helios_1_1input_1_1Cursor_01_4.html", null ],
    [ "std::formatter&lt; helios::input::CursorIcon &gt;", "structstd_1_1formatter_3_01helios_1_1input_1_1CursorIcon_01_4.html", null ],
    [ "std::formatter&lt; helios::input::CursorImage &gt;", "structstd_1_1formatter_3_01helios_1_1input_1_1CursorImage_01_4.html", null ],
    [ "std::formatter&lt; helios::input::CursorMovedMsg &gt;", "structstd_1_1formatter_3_01helios_1_1input_1_1CursorMovedMsg_01_4.html", null ],
    [ "std::formatter&lt; helios::input::Gamepad &gt;", "structstd_1_1formatter_3_01helios_1_1input_1_1Gamepad_01_4.html", null ],
    [ "std::formatter&lt; helios::input::GamepadAxis &gt;", "structstd_1_1formatter_3_01helios_1_1input_1_1GamepadAxis_01_4.html", null ],
    [ "std::formatter&lt; helios::input::GamepadAxisChangedMsg &gt;", "structstd_1_1formatter_3_01helios_1_1input_1_1GamepadAxisChangedMsg_01_4.html", null ],
    [ "std::formatter&lt; helios::input::GamepadButton &gt;", "structstd_1_1formatter_3_01helios_1_1input_1_1GamepadButton_01_4.html", null ],
    [ "std::formatter&lt; helios::input::GamepadButtonInputMsg &gt;", "structstd_1_1formatter_3_01helios_1_1input_1_1GamepadButtonInputMsg_01_4.html", null ],
    [ "std::formatter&lt; helios::input::GamepadConnectionMsg &gt;", "structstd_1_1formatter_3_01helios_1_1input_1_1GamepadConnectionMsg_01_4.html", null ],
    [ "std::formatter&lt; helios::input::GamepadDirtyFlags &gt;", "structstd_1_1formatter_3_01helios_1_1input_1_1GamepadDirtyFlags_01_4.html", null ],
    [ "std::formatter&lt; helios::input::GamepadMappings &gt;", "structstd_1_1formatter_3_01helios_1_1input_1_1GamepadMappings_01_4.html", null ],
    [ "std::formatter&lt; helios::input::GamepadPower &gt;", "structstd_1_1formatter_3_01helios_1_1input_1_1GamepadPower_01_4.html", null ],
    [ "std::formatter&lt; helios::input::GamepadPowerChangedMsg &gt;", "structstd_1_1formatter_3_01helios_1_1input_1_1GamepadPowerChangedMsg_01_4.html", null ],
    [ "std::formatter&lt; helios::input::GamepadPowerState &gt;", "structstd_1_1formatter_3_01helios_1_1input_1_1GamepadPowerState_01_4.html", null ],
    [ "std::formatter&lt; helios::input::GamepadRemappedMsg &gt;", "structstd_1_1formatter_3_01helios_1_1input_1_1GamepadRemappedMsg_01_4.html", null ],
    [ "std::formatter&lt; helios::input::Gamepads &gt;", "structstd_1_1formatter_3_01helios_1_1input_1_1Gamepads_01_4.html", null ],
    [ "std::formatter&lt; helios::input::GamepadSensor &gt;", "structstd_1_1formatter_3_01helios_1_1input_1_1GamepadSensor_01_4.html", null ],
    [ "std::formatter&lt; helios::input::GamepadSensorUpdateMsg &gt;", "structstd_1_1formatter_3_01helios_1_1input_1_1GamepadSensorUpdateMsg_01_4.html", null ],
    [ "std::formatter&lt; helios::input::GamepadTouchpadFinger &gt;", "structstd_1_1formatter_3_01helios_1_1input_1_1GamepadTouchpadFinger_01_4.html", null ],
    [ "std::formatter&lt; helios::input::GamepadTouchpadMsg &gt;", "structstd_1_1formatter_3_01helios_1_1input_1_1GamepadTouchpadMsg_01_4.html", null ],
    [ "std::formatter&lt; helios::input::Joystick &gt;", "structstd_1_1formatter_3_01helios_1_1input_1_1Joystick_01_4.html", null ],
    [ "std::formatter&lt; helios::input::JoystickAxisChangedMsg &gt;", "structstd_1_1formatter_3_01helios_1_1input_1_1JoystickAxisChangedMsg_01_4.html", null ],
    [ "std::formatter&lt; helios::input::JoystickButtonInputMsg &gt;", "structstd_1_1formatter_3_01helios_1_1input_1_1JoystickButtonInputMsg_01_4.html", null ],
    [ "std::formatter&lt; helios::input::JoystickConnectionMsg &gt;", "structstd_1_1formatter_3_01helios_1_1input_1_1JoystickConnectionMsg_01_4.html", null ],
    [ "std::formatter&lt; helios::input::JoystickHat &gt;", "structstd_1_1formatter_3_01helios_1_1input_1_1JoystickHat_01_4.html", null ],
    [ "std::formatter&lt; helios::input::JoystickHatChangedMsg &gt;", "structstd_1_1formatter_3_01helios_1_1input_1_1JoystickHatChangedMsg_01_4.html", null ],
    [ "std::formatter&lt; helios::input::Joysticks &gt;", "structstd_1_1formatter_3_01helios_1_1input_1_1Joysticks_01_4.html", null ],
    [ "std::formatter&lt; helios::input::Key &gt;", "structstd_1_1formatter_3_01helios_1_1input_1_1Key_01_4.html", null ],
    [ "std::formatter&lt; helios::input::Keyboard &gt;", "structstd_1_1formatter_3_01helios_1_1input_1_1Keyboard_01_4.html", null ],
    [ "std::formatter&lt; helios::input::KeyboardInputMsg &gt;", "structstd_1_1formatter_3_01helios_1_1input_1_1KeyboardInputMsg_01_4.html", null ],
    [ "std::formatter&lt; helios::input::Modifiers &gt;", "structstd_1_1formatter_3_01helios_1_1input_1_1Modifiers_01_4.html", null ],
    [ "std::formatter&lt; helios::input::Mouse &gt;", "structstd_1_1formatter_3_01helios_1_1input_1_1Mouse_01_4.html", null ],
    [ "std::formatter&lt; helios::input::MouseButton &gt;", "structstd_1_1formatter_3_01helios_1_1input_1_1MouseButton_01_4.html", null ],
    [ "std::formatter&lt; helios::input::MouseButtonInputMsg &gt;", "structstd_1_1formatter_3_01helios_1_1input_1_1MouseButtonInputMsg_01_4.html", null ],
    [ "std::formatter&lt; helios::input::MouseMotionMsg &gt;", "structstd_1_1formatter_3_01helios_1_1input_1_1MouseMotionMsg_01_4.html", null ],
    [ "std::formatter&lt; helios::input::MouseWheelMsg &gt;", "structstd_1_1formatter_3_01helios_1_1input_1_1MouseWheelMsg_01_4.html", null ],
    [ "std::formatter&lt; helios::input::Pen &gt;", "structstd_1_1formatter_3_01helios_1_1input_1_1Pen_01_4.html", null ],
    [ "std::formatter&lt; helios::input::PenAxis &gt;", "structstd_1_1formatter_3_01helios_1_1input_1_1PenAxis_01_4.html", null ],
    [ "std::formatter&lt; helios::input::PenAxisChangedMsg &gt;", "structstd_1_1formatter_3_01helios_1_1input_1_1PenAxisChangedMsg_01_4.html", null ],
    [ "std::formatter&lt; helios::input::PenButton &gt;", "structstd_1_1formatter_3_01helios_1_1input_1_1PenButton_01_4.html", null ],
    [ "std::formatter&lt; helios::input::PenButtonInputMsg &gt;", "structstd_1_1formatter_3_01helios_1_1input_1_1PenButtonInputMsg_01_4.html", null ],
    [ "std::formatter&lt; helios::input::PenDeviceType &gt;", "structstd_1_1formatter_3_01helios_1_1input_1_1PenDeviceType_01_4.html", null ],
    [ "std::formatter&lt; helios::input::PenMovedMsg &gt;", "structstd_1_1formatter_3_01helios_1_1input_1_1PenMovedMsg_01_4.html", null ],
    [ "std::formatter&lt; helios::input::PenProximityMsg &gt;", "structstd_1_1formatter_3_01helios_1_1input_1_1PenProximityMsg_01_4.html", null ],
    [ "std::formatter&lt; helios::input::Pens &gt;", "structstd_1_1formatter_3_01helios_1_1input_1_1Pens_01_4.html", null ],
    [ "std::formatter&lt; helios::input::PenTouchMsg &gt;", "structstd_1_1formatter_3_01helios_1_1input_1_1PenTouchMsg_01_4.html", null ],
    [ "std::formatter&lt; helios::input::Settings &gt;", "structstd_1_1formatter_3_01helios_1_1input_1_1Settings_01_4.html", null ],
    [ "std::formatter&lt; helios::input::TextInputMsg &gt;", "structstd_1_1formatter_3_01helios_1_1input_1_1TextInputMsg_01_4.html", null ],
    [ "std::formatter&lt; helios::window::ClientApi &gt;", "structstd_1_1formatter_3_01helios_1_1window_1_1ClientApi_01_4.html", null ],
    [ "std::formatter&lt; helios::window::ClientResizedMsg &gt;", "structstd_1_1formatter_3_01helios_1_1window_1_1ClientResizedMsg_01_4.html", null ],
    [ "std::formatter&lt; helios::window::Clipboard &gt;", "structstd_1_1formatter_3_01helios_1_1window_1_1Clipboard_01_4.html", null ],
    [ "std::formatter&lt; helios::window::ClipboardChangedMsg &gt;", "structstd_1_1formatter_3_01helios_1_1window_1_1ClipboardChangedMsg_01_4.html", null ],
    [ "std::formatter&lt; helios::window::ClosedMsg &gt;", "structstd_1_1formatter_3_01helios_1_1window_1_1ClosedMsg_01_4.html", null ],
    [ "std::formatter&lt; helios::window::CloseRequestedMsg &gt;", "structstd_1_1formatter_3_01helios_1_1window_1_1CloseRequestedMsg_01_4.html", null ],
    [ "std::formatter&lt; helios::window::ContentScaleChangedMsg &gt;", "structstd_1_1formatter_3_01helios_1_1window_1_1ContentScaleChangedMsg_01_4.html", null ],
    [ "std::formatter&lt; helios::window::CreatedMsg &gt;", "structstd_1_1formatter_3_01helios_1_1window_1_1CreatedMsg_01_4.html", null ],
    [ "std::formatter&lt; helios::window::CreationFailedMsg &gt;", "structstd_1_1formatter_3_01helios_1_1window_1_1CreationFailedMsg_01_4.html", null ],
    [ "std::formatter&lt; helios::window::CursorMode &gt;", "structstd_1_1formatter_3_01helios_1_1window_1_1CursorMode_01_4.html", null ],
    [ "std::formatter&lt; helios::window::CursorModeChangedMsg &gt;", "structstd_1_1formatter_3_01helios_1_1window_1_1CursorModeChangedMsg_01_4.html", null ],
    [ "std::formatter&lt; helios::window::DecoratedChangedMsg &gt;", "structstd_1_1formatter_3_01helios_1_1window_1_1DecoratedChangedMsg_01_4.html", null ],
    [ "std::formatter&lt; helios::window::DirtyFlag &gt;", "structstd_1_1formatter_3_01helios_1_1window_1_1DirtyFlag_01_4.html", null ],
    [ "std::formatter&lt; helios::window::DroppedFilesMsg &gt;", "structstd_1_1formatter_3_01helios_1_1window_1_1DroppedFilesMsg_01_4.html", null ],
    [ "std::formatter&lt; helios::window::EventMode &gt;", "structstd_1_1formatter_3_01helios_1_1window_1_1EventMode_01_4.html", null ],
    [ "std::formatter&lt; helios::window::ExclusiveVideoMode &gt;", "structstd_1_1formatter_3_01helios_1_1window_1_1ExclusiveVideoMode_01_4.html", null ],
    [ "std::formatter&lt; helios::window::ExitTrigger &gt;", "structstd_1_1formatter_3_01helios_1_1window_1_1ExitTrigger_01_4.html", null ],
    [ "std::formatter&lt; helios::window::FloatingChangedMsg &gt;", "structstd_1_1formatter_3_01helios_1_1window_1_1FloatingChangedMsg_01_4.html", null ],
    [ "std::formatter&lt; helios::window::FocusChangedMsg &gt;", "structstd_1_1formatter_3_01helios_1_1window_1_1FocusChangedMsg_01_4.html", null ],
    [ "std::formatter&lt; helios::window::HoverChangedMsg &gt;", "structstd_1_1formatter_3_01helios_1_1window_1_1HoverChangedMsg_01_4.html", null ],
    [ "std::formatter&lt; helios::window::IconChangedMsg &gt;", "structstd_1_1formatter_3_01helios_1_1window_1_1IconChangedMsg_01_4.html", null ],
    [ "std::formatter&lt; helios::window::IconImage &gt;", "structstd_1_1formatter_3_01helios_1_1window_1_1IconImage_01_4.html", null ],
    [ "std::formatter&lt; helios::window::MaximizedChangedMsg &gt;", "structstd_1_1formatter_3_01helios_1_1window_1_1MaximizedChangedMsg_01_4.html", null ],
    [ "std::formatter&lt; helios::window::Mode &gt;", "structstd_1_1formatter_3_01helios_1_1window_1_1Mode_01_4.html", null ],
    [ "std::formatter&lt; helios::window::ModeChangedMsg &gt;", "structstd_1_1formatter_3_01helios_1_1window_1_1ModeChangedMsg_01_4.html", null ],
    [ "std::formatter&lt; helios::window::Monitor &gt;", "structstd_1_1formatter_3_01helios_1_1window_1_1Monitor_01_4.html", null ],
    [ "std::formatter&lt; helios::window::MonitorConnectedMsg &gt;", "structstd_1_1formatter_3_01helios_1_1window_1_1MonitorConnectedMsg_01_4.html", null ],
    [ "std::formatter&lt; helios::window::MonitorDisconnectedMsg &gt;", "structstd_1_1formatter_3_01helios_1_1window_1_1MonitorDisconnectedMsg_01_4.html", null ],
    [ "std::formatter&lt; helios::window::MonitorEvent &gt;", "structstd_1_1formatter_3_01helios_1_1window_1_1MonitorEvent_01_4.html", null ],
    [ "std::formatter&lt; helios::window::Monitors &gt;", "structstd_1_1formatter_3_01helios_1_1window_1_1Monitors_01_4.html", null ],
    [ "std::formatter&lt; helios::window::MousePassthroughChangedMsg &gt;", "structstd_1_1formatter_3_01helios_1_1window_1_1MousePassthroughChangedMsg_01_4.html", null ],
    [ "std::formatter&lt; helios::window::NativeHandle &gt;", "structstd_1_1formatter_3_01helios_1_1window_1_1NativeHandle_01_4.html", null ],
    [ "std::formatter&lt; helios::window::NativeHandleComponent &gt;", "structstd_1_1formatter_3_01helios_1_1window_1_1NativeHandleComponent_01_4.html", null ],
    [ "std::formatter&lt; helios::window::OpacityChangedMsg &gt;", "structstd_1_1formatter_3_01helios_1_1window_1_1OpacityChangedMsg_01_4.html", null ],
    [ "std::formatter&lt; helios::window::PosChangedMsg &gt;", "structstd_1_1formatter_3_01helios_1_1window_1_1PosChangedMsg_01_4.html", null ],
    [ "std::formatter&lt; helios::window::Properties &gt;", "structstd_1_1formatter_3_01helios_1_1window_1_1Properties_01_4.html", null ],
    [ "std::formatter&lt; helios::window::ResizableChangedMsg &gt;", "structstd_1_1formatter_3_01helios_1_1window_1_1ResizableChangedMsg_01_4.html", null ],
    [ "std::formatter&lt; helios::window::ResizedMsg &gt;", "structstd_1_1formatter_3_01helios_1_1window_1_1ResizedMsg_01_4.html", null ],
    [ "std::formatter&lt; helios::window::Settings &gt;", "structstd_1_1formatter_3_01helios_1_1window_1_1Settings_01_4.html", null ],
    [ "std::formatter&lt; helios::window::VideoMode &gt;", "structstd_1_1formatter_3_01helios_1_1window_1_1VideoMode_01_4.html", null ],
    [ "std::formatter&lt; helios::window::VisibilityChangedMsg &gt;", "structstd_1_1formatter_3_01helios_1_1window_1_1VisibilityChangedMsg_01_4.html", null ],
    [ "std::formatter&lt; helios::window::Window &gt;", "structstd_1_1formatter_3_01helios_1_1window_1_1Window_01_4.html", null ],
    [ "helios::mem::FrameAllocatorOptions", "structhelios_1_1mem_1_1FrameAllocatorOptions.html", null ],
    [ "helios::app::FrameCount", "structhelios_1_1app_1_1FrameCount.html", null ],
    [ "helios::app::FrameLimiter", "classhelios_1_1app_1_1FrameLimiter.html", null ],
    [ "helios::app::FrameLimiterSettings", "structhelios_1_1app_1_1FrameLimiterSettings.html", null ],
    [ "helios::app::FrameOrder", "classhelios_1_1app_1_1FrameOrder.html", [
      [ "helios::app::FramePumpOrder", "structhelios_1_1app_1_1FramePumpOrder.html", null ],
      [ "helios::app::MainFrameOrder", "structhelios_1_1app_1_1MainFrameOrder.html", null ]
    ] ],
    [ "helios::app::FramePace", "structhelios_1_1app_1_1FramePace.html", null ],
    [ "helios::app::FramePaceStage", "structhelios_1_1app_1_1FramePaceStage.html", null ],
    [ "helios::ecs::details::FreeFunctionSystemImpl&lt; Fn, FnType &gt;", "structhelios_1_1ecs_1_1details_1_1FreeFunctionSystemImpl.html", null ],
    [ "helios::ecs::details::FreeFunctionSystemImpl&lt; Fn, decltype(Fn)&gt;", "structhelios_1_1ecs_1_1details_1_1FreeFunctionSystemImpl.html", [
      [ "helios::ecs::FreeFunctionSystem< Fn >", "structhelios_1_1ecs_1_1FreeFunctionSystem.html", null ]
    ] ],
    [ "helios::ecs::details::FreeFunctionSystemImpl&lt; Fn, R(Args...) noexcept &gt;", "structhelios_1_1ecs_1_1details_1_1FreeFunctionSystemImpl_3_01Fn_00_01R_07Args_8_8_8_08_01noexcept_01_4.html", [
      [ "helios::ecs::details::FreeFunctionSystemImpl< Fn, R(*)(Args...) noexcept >", "structhelios_1_1ecs_1_1details_1_1FreeFunctionSystemImpl_3_01Fn_00_01R_07_5_08_07Args_8_8_8_08_01noexcept_01_4.html", null ]
    ] ],
    [ "helios::ecs::details::FreeFunctionSystemImpl&lt; Fn, R(Args...)&gt;", "structhelios_1_1ecs_1_1details_1_1FreeFunctionSystemImpl_3_01Fn_00_01R_07Args_8_8_8_08_4.html", [
      [ "helios::ecs::details::FreeFunctionSystemImpl< Fn, R(*)(Args...)>", "structhelios_1_1ecs_1_1details_1_1FreeFunctionSystemImpl_3_01Fn_00_01R_07_5_08_07Args_8_8_8_08_4.html", null ]
    ] ],
    [ "helios::details::FreeFunctionTraits&lt; FunctionSignature &gt;", "structhelios_1_1details_1_1FreeFunctionTraits.html", null ],
    [ "helios::details::FreeFunctionTraits&lt; R(*)(Args...)&gt;", "structhelios_1_1details_1_1FreeFunctionTraits_3_01R_07_5_08_07Args_8_8_8_08_4.html", null ],
    [ "helios::mem::FreeListAllocatorOptions", "structhelios_1_1mem_1_1FreeListAllocatorOptions.html", null ],
    [ "helios::utils::FunctionalAdapterBase&lt; Derived &gt;", "classhelios_1_1utils_1_1FunctionalAdapterBase.html", null ],
    [ "helios::utils::FunctionalAdapterBase&lt; BasicQueryIter&lt; IsConst, Components... &gt; &gt;", "classhelios_1_1utils_1_1FunctionalAdapterBase.html", [
      [ "helios::ecs::BasicQueryIter< false, Components... >", "classhelios_1_1ecs_1_1BasicQueryIter.html", null ],
      [ "helios::ecs::BasicQueryIter< true, Components... >", "classhelios_1_1ecs_1_1BasicQueryIter.html", null ],
      [ "helios::ecs::BasicQueryIter< IsConst, Components >", "classhelios_1_1ecs_1_1BasicQueryIter.html", null ]
    ] ],
    [ "helios::utils::FunctionalAdapterBase&lt; BasicQueryWithEntityIter&lt; IsConst, Components... &gt; &gt;", "classhelios_1_1utils_1_1FunctionalAdapterBase.html", [
      [ "helios::ecs::BasicQueryWithEntityIter< false, Components... >", "classhelios_1_1ecs_1_1BasicQueryWithEntityIter.html", null ],
      [ "helios::ecs::BasicQueryWithEntityIter< true, Components... >", "classhelios_1_1ecs_1_1BasicQueryWithEntityIter.html", null ],
      [ "helios::ecs::BasicQueryWithEntityIter< IsConst, Components >", "classhelios_1_1ecs_1_1BasicQueryWithEntityIter.html", null ]
    ] ],
    [ "helios::utils::FunctionalAdapterBase&lt; ChainAdapter&lt; Iter1, Iter2 &gt; &gt;", "classhelios_1_1utils_1_1FunctionalAdapterBase.html", [
      [ "helios::utils::ChainAdapter< Iter1, Iter2 >", "classhelios_1_1utils_1_1ChainAdapter.html", null ]
    ] ],
    [ "helios::utils::FunctionalAdapterBase&lt; ChunkAdapter&lt; Iter &gt; &gt;", "classhelios_1_1utils_1_1FunctionalAdapterBase.html", [
      [ "helios::utils::ChunkAdapter< Iter >", "classhelios_1_1utils_1_1ChunkAdapter.html", null ]
    ] ],
    [ "helios::utils::FunctionalAdapterBase&lt; ConsumableMessageWrapperIter&lt; T &gt; &gt;", "classhelios_1_1utils_1_1FunctionalAdapterBase.html", [
      [ "helios::ecs::ConsumableMessageWrapperIter< T >", "classhelios_1_1ecs_1_1ConsumableMessageWrapperIter.html", null ]
    ] ],
    [ "helios::utils::FunctionalAdapterBase&lt; EnumerateAdapter&lt; Iter &gt; &gt;", "classhelios_1_1utils_1_1FunctionalAdapterBase.html", [
      [ "helios::utils::EnumerateAdapter< Iter >", "classhelios_1_1utils_1_1EnumerateAdapter.html", null ]
    ] ],
    [ "helios::utils::FunctionalAdapterBase&lt; FilterAdapter&lt; Iter, Pred &gt; &gt;", "classhelios_1_1utils_1_1FunctionalAdapterBase.html", [
      [ "helios::utils::FilterAdapter< Iter, Pred >", "classhelios_1_1utils_1_1FilterAdapter.html", null ]
    ] ],
    [ "helios::utils::FunctionalAdapterBase&lt; InspectAdapter&lt; Iter, Func &gt; &gt;", "classhelios_1_1utils_1_1FunctionalAdapterBase.html", [
      [ "helios::utils::InspectAdapter< Iter, Func >", "classhelios_1_1utils_1_1InspectAdapter.html", null ]
    ] ],
    [ "helios::utils::FunctionalAdapterBase&lt; MapAdapter&lt; Iter, Func &gt; &gt;", "classhelios_1_1utils_1_1FunctionalAdapterBase.html", [
      [ "helios::utils::MapAdapter< Iter, Func >", "classhelios_1_1utils_1_1MapAdapter.html", null ]
    ] ],
    [ "helios::utils::FunctionalAdapterBase&lt; MessageWrapperIter&lt; T &gt; &gt;", "classhelios_1_1utils_1_1FunctionalAdapterBase.html", [
      [ "helios::ecs::MessageWrapperIter< T >", "classhelios_1_1ecs_1_1MessageWrapperIter.html", null ]
    ] ],
    [ "helios::utils::FunctionalAdapterBase&lt; ReverseAdapter&lt; Iter &gt; &gt;", "classhelios_1_1utils_1_1FunctionalAdapterBase.html", [
      [ "helios::utils::ReverseAdapter< Iter >", "classhelios_1_1utils_1_1ReverseAdapter.html", null ]
    ] ],
    [ "helios::utils::FunctionalAdapterBase&lt; SkipAdapter&lt; Iter &gt; &gt;", "classhelios_1_1utils_1_1FunctionalAdapterBase.html", [
      [ "helios::utils::SkipAdapter< Iter >", "classhelios_1_1utils_1_1SkipAdapter.html", null ]
    ] ],
    [ "helios::utils::FunctionalAdapterBase&lt; SkipWhileAdapter&lt; Iter, Pred &gt; &gt;", "classhelios_1_1utils_1_1FunctionalAdapterBase.html", [
      [ "helios::utils::SkipWhileAdapter< Iter, Pred >", "classhelios_1_1utils_1_1SkipWhileAdapter.html", null ]
    ] ],
    [ "helios::utils::FunctionalAdapterBase&lt; SlideAdapter&lt; Iter &gt; &gt;", "classhelios_1_1utils_1_1FunctionalAdapterBase.html", [
      [ "helios::utils::SlideAdapter< Iter >", "classhelios_1_1utils_1_1SlideAdapter.html", null ]
    ] ],
    [ "helios::utils::FunctionalAdapterBase&lt; StepByAdapter&lt; Iter &gt; &gt;", "classhelios_1_1utils_1_1FunctionalAdapterBase.html", [
      [ "helios::utils::StepByAdapter< Iter >", "classhelios_1_1utils_1_1StepByAdapter.html", null ]
    ] ],
    [ "helios::utils::FunctionalAdapterBase&lt; StrideAdapter&lt; Iter &gt; &gt;", "classhelios_1_1utils_1_1FunctionalAdapterBase.html", [
      [ "helios::utils::StrideAdapter< Iter >", "classhelios_1_1utils_1_1StrideAdapter.html", null ]
    ] ],
    [ "helios::utils::FunctionalAdapterBase&lt; TakeAdapter&lt; Iter &gt; &gt;", "classhelios_1_1utils_1_1FunctionalAdapterBase.html", [
      [ "helios::utils::TakeAdapter< Iter >", "classhelios_1_1utils_1_1TakeAdapter.html", null ]
    ] ],
    [ "helios::utils::FunctionalAdapterBase&lt; TakeWhileAdapter&lt; Iter, Pred &gt; &gt;", "classhelios_1_1utils_1_1FunctionalAdapterBase.html", [
      [ "helios::utils::TakeWhileAdapter< Iter, Pred >", "classhelios_1_1utils_1_1TakeWhileAdapter.html", null ]
    ] ],
    [ "helios::utils::FunctionalAdapterBase&lt; ZipAdapter&lt; Iter1, Iter2 &gt; &gt;", "classhelios_1_1utils_1_1FunctionalAdapterBase.html", [
      [ "helios::utils::ZipAdapter< Iter1, Iter2 >", "classhelios_1_1utils_1_1ZipAdapter.html", null ]
    ] ],
    [ "helios::ecs::FunctionCmd&lt; F &gt;", "classhelios_1_1ecs_1_1FunctionCmd.html", null ],
    [ "helios::async::Future&lt; T &gt;", "classhelios_1_1async_1_1Future.html", null ],
    [ "helios::input::Gamepad", "structhelios_1_1input_1_1Gamepad.html", null ],
    [ "helios::input::GamepadAxisChangedMsg", "structhelios_1_1input_1_1GamepadAxisChangedMsg.html", null ],
    [ "helios::input::GamepadAxisFilter", "structhelios_1_1input_1_1GamepadAxisFilter.html", null ],
    [ "helios::input::GamepadButtonInputMsg", "structhelios_1_1input_1_1GamepadButtonInputMsg.html", null ],
    [ "helios::sdl3::input::GamepadCache", "structhelios_1_1sdl3_1_1input_1_1GamepadCache.html", null ],
    [ "helios::input::GamepadConnectionMsg", "structhelios_1_1input_1_1GamepadConnectionMsg.html", null ],
    [ "helios::input::GamepadMappings", "structhelios_1_1input_1_1GamepadMappings.html", null ],
    [ "helios::input::GamepadMessages", "structhelios_1_1input_1_1GamepadMessages.html", null ],
    [ "helios::input::GamepadPower", "structhelios_1_1input_1_1GamepadPower.html", null ],
    [ "helios::input::GamepadPowerChangedMsg", "structhelios_1_1input_1_1GamepadPowerChangedMsg.html", null ],
    [ "helios::input::GamepadRemappedMsg", "structhelios_1_1input_1_1GamepadRemappedMsg.html", null ],
    [ "helios::input::Gamepads", "structhelios_1_1input_1_1Gamepads.html", null ],
    [ "helios::input::GamepadSensorUpdateMsg", "structhelios_1_1input_1_1GamepadSensorUpdateMsg.html", null ],
    [ "helios::sdl3::input::GamepadSlotCache", "structhelios_1_1sdl3_1_1input_1_1GamepadSlotCache.html", null ],
    [ "helios::input::GamepadTouchpadFinger", "structhelios_1_1input_1_1GamepadTouchpadFinger.html", null ],
    [ "helios::input::GamepadTouchpadMsg", "structhelios_1_1input_1_1GamepadTouchpadMsg.html", null ],
    [ "helios::input::GamepadWriters", "structhelios_1_1input_1_1GamepadWriters.html", null ],
    [ "helios::window::GeometryMessages", "structhelios_1_1window_1_1GeometryMessages.html", null ],
    [ "helios::window::GeometryWriters", "structhelios_1_1window_1_1GeometryWriters.html", null ],
    [ "helios::mem::GrowthPolicy", "structhelios_1_1mem_1_1GrowthPolicy.html", null ],
    [ "std::hash&lt; helios::BasicCStringView&lt; CharT, Traits &gt; &gt;", "structstd_1_1hash_3_01helios_1_1BasicCStringView_3_01CharT_00_01Traits_01_4_01_4.html", null ],
    [ "std::hash&lt; helios::container::BasicStaticString&lt; StrCapacity, CharT, Traits &gt; &gt;", "structstd_1_1hash_3_01helios_1_1container_1_1BasicStaticString_3_01StrCapacity_00_01CharT_00_01Traits_01_4_01_4.html", null ],
    [ "std::hash&lt; helios::ecs::ArchetypeId &gt;", "structstd_1_1hash_3_01helios_1_1ecs_1_1ArchetypeId_01_4.html", null ],
    [ "std::hash&lt; helios::ecs::ComponentTypeInfo &gt;", "structstd_1_1hash_3_01helios_1_1ecs_1_1ComponentTypeInfo_01_4.html", null ],
    [ "std::hash&lt; helios::ecs::Entity &gt;", "structstd_1_1hash_3_01helios_1_1ecs_1_1Entity_01_4.html", null ],
    [ "std::hash&lt; helios::ecs::SystemId &gt;", "structstd_1_1hash_3_01helios_1_1ecs_1_1SystemId_01_4.html", null ],
    [ "std::hash&lt; helios::utils::TypeId &gt;", "structstd_1_1hash_3_01helios_1_1utils_1_1TypeId_01_4.html", null ],
    [ "std::hash&lt; helios::utils::TypeIndex &gt;", "structstd_1_1hash_3_01helios_1_1utils_1_1TypeIndex_01_4.html", null ],
    [ "std::hash&lt; helios::Uuid &gt;", "structstd_1_1hash_3_01helios_1_1Uuid_01_4.html", null ],
    [ "helios::ecs::details::HasSystemParamCallOperatorHelper&lt; T &gt;", "structhelios_1_1ecs_1_1details_1_1HasSystemParamCallOperatorHelper.html", null ],
    [ "helios::window::HoverChangedMsg", "structhelios_1_1window_1_1HoverChangedMsg.html", null ],
    [ "helios::window::IconChangedMsg", "structhelios_1_1window_1_1IconChangedMsg.html", null ],
    [ "helios::window::IconImage", "structhelios_1_1window_1_1IconImage.html", null ],
    [ "helios::input::IndexedButtonInput&lt; N &gt;", "classhelios_1_1input_1_1IndexedButtonInput.html", null ],
    [ "helios::glfw::Init", "structhelios_1_1glfw_1_1Init.html", null ],
    [ "helios::sdl3::Init", "structhelios_1_1sdl3_1_1Init.html", null ],
    [ "helios::sdl3::input::Init", "structhelios_1_1sdl3_1_1input_1_1Init.html", null ],
    [ "helios::sdl3::window::Init", "structhelios_1_1sdl3_1_1window_1_1Init.html", null ],
    [ "helios::ecs::InsertResourceCmd&lt; T &gt;", "classhelios_1_1ecs_1_1InsertResourceCmd.html", null ],
    [ "helios::utils::JoinAdapter&lt; Iter &gt;", "classhelios_1_1utils_1_1JoinAdapter.html", null ],
    [ "helios::input::Joystick", "structhelios_1_1input_1_1Joystick.html", null ],
    [ "helios::input::JoystickAxisChangedMsg", "structhelios_1_1input_1_1JoystickAxisChangedMsg.html", null ],
    [ "helios::input::JoystickButtonInputMsg", "structhelios_1_1input_1_1JoystickButtonInputMsg.html", null ],
    [ "helios::input::JoystickConnectionMsg", "structhelios_1_1input_1_1JoystickConnectionMsg.html", null ],
    [ "helios::input::JoystickHatChangedMsg", "structhelios_1_1input_1_1JoystickHatChangedMsg.html", null ],
    [ "helios::input::JoystickMessages", "structhelios_1_1input_1_1JoystickMessages.html", null ],
    [ "helios::input::Joysticks", "structhelios_1_1input_1_1Joysticks.html", null ],
    [ "helios::input::JoystickWriters", "structhelios_1_1input_1_1JoystickWriters.html", null ],
    [ "helios::input::Keyboard", "structhelios_1_1input_1_1Keyboard.html", null ],
    [ "helios::input::KeyboardInputMsg", "structhelios_1_1input_1_1KeyboardInputMsg.html", null ],
    [ "helios::input::KeyboardMessages", "structhelios_1_1input_1_1KeyboardMessages.html", null ],
    [ "helios::input::KeyboardWriters", "structhelios_1_1input_1_1KeyboardWriters.html", null ],
    [ "helios::app::Last", "structhelios_1_1app_1_1Last.html", null ],
    [ "helios::window::LifecycleMessages", "structhelios_1_1window_1_1LifecycleMessages.html", null ],
    [ "helios::window::LifecycleWriters", "structhelios_1_1window_1_1LifecycleWriters.html", null ],
    [ "helios::app::LimitFrameRate", "structhelios_1_1app_1_1LimitFrameRate.html", null ],
    [ "helios::ecs::Local&lt; T &gt;", "classhelios_1_1ecs_1_1Local.html", null ],
    [ "helios::ecs::LocalArena", "structhelios_1_1ecs_1_1LocalArena.html", null ],
    [ "helios::log::Logger", "classhelios_1_1log_1_1Logger.html", null ],
    [ "helios::app::MainStartup", "structhelios_1_1app_1_1MainStartup.html", null ],
    [ "helios::ecs::ManagedMessageWriter&lt; T &gt;", "classhelios_1_1ecs_1_1ManagedMessageWriter.html", null ],
    [ "helios::mem::FixedStackAllocator::Marker", "structhelios_1_1mem_1_1FixedStackAllocator_1_1Marker.html", null ],
    [ "helios::mem::StackAllocator::Marker", "structhelios_1_1mem_1_1StackAllocator_1_1Marker.html", null ],
    [ "helios::window::MaximizedChangedMsg", "structhelios_1_1window_1_1MaximizedChangedMsg.html", null ],
    [ "helios::ecs::details::MemberFnArgs&lt; F &gt;", "structhelios_1_1ecs_1_1details_1_1MemberFnArgs.html", null ],
    [ "helios::ecs::details::MemberFnArgs&lt; R(*)(Args...) noexcept &gt;", "structhelios_1_1ecs_1_1details_1_1MemberFnArgs_3_01R_07_5_08_07Args_8_8_8_08_01noexcept_01_4.html", null ],
    [ "helios::ecs::details::MemberFnArgs&lt; R(*)(Args...)&gt;", "structhelios_1_1ecs_1_1details_1_1MemberFnArgs_3_01R_07_5_08_07Args_8_8_8_08_4.html", null ],
    [ "helios::ecs::details::MemberFnArgs&lt; R(Args...) noexcept &gt;", "structhelios_1_1ecs_1_1details_1_1MemberFnArgs_3_01R_07Args_8_8_8_08_01noexcept_01_4.html", null ],
    [ "helios::ecs::details::MemberFnArgs&lt; R(Args...)&gt;", "structhelios_1_1ecs_1_1details_1_1MemberFnArgs_3_01R_07Args_8_8_8_08_4.html", null ],
    [ "helios::ecs::details::MemberFnArgs&lt; R(C::*)(Args...) const &gt;", "structhelios_1_1ecs_1_1details_1_1MemberFnArgs_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01const_01_4.html", null ],
    [ "helios::ecs::details::MemberFnArgs&lt; R(C::*)(Args...) const noexcept &gt;", "structhelios_1_1ecs_1_1details_1_1MemberFnArgs_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01const_01noexcept_01_4.html", null ],
    [ "helios::ecs::details::MemberFnArgs&lt; R(C::*)(Args...) noexcept &gt;", "structhelios_1_1ecs_1_1details_1_1MemberFnArgs_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01noexcept_01_4.html", null ],
    [ "helios::ecs::details::MemberFnArgs&lt; R(C::*)(Args...)&gt;", "structhelios_1_1ecs_1_1details_1_1MemberFnArgs_3_01R_07C_1_1_5_08_07Args_8_8_8_08_4.html", null ],
    [ "helios::details::MemberFnPtrTraits&lt; MemberFnPtr &gt;", "structhelios_1_1details_1_1MemberFnPtrTraits.html", null ],
    [ "helios::details::MemberFnPtrTraits&lt; decltype(&amp;Callable::operator())&gt;", "structhelios_1_1details_1_1MemberFnPtrTraits.html", [
      [ "helios::details::CallableTraits< Callable >", "structhelios_1_1details_1_1CallableTraits_3_01Callable_01_4.html", null ]
    ] ],
    [ "helios::details::MemberFnPtrTraits&lt; R(C::*)(Args...) const &gt;", "structhelios_1_1details_1_1MemberFnPtrTraits_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01const_01_4.html", null ],
    [ "helios::details::MemberFnPtrTraits&lt; R(C::*)(Args...) const noexcept &gt;", "structhelios_1_1details_1_1MemberFnPtrTraits_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01const_01noexcept_01_4.html", null ],
    [ "helios::details::MemberFnPtrTraits&lt; R(C::*)(Args...) noexcept &gt;", "structhelios_1_1details_1_1MemberFnPtrTraits_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01noexcept_01_4.html", null ],
    [ "helios::details::MemberFnPtrTraits&lt; R(C::*)(Args...)&gt;", "structhelios_1_1details_1_1MemberFnPtrTraits_3_01R_07C_1_1_5_08_07Args_8_8_8_08_4.html", null ],
    [ "helios::details::MemberFunctionTraits&lt; FunctionSignature &gt;", "structhelios_1_1details_1_1MemberFunctionTraits.html", null ],
    [ "helios::details::MemberFunctionTraits&lt; R(C::*)(Args...) const &gt;", "structhelios_1_1details_1_1MemberFunctionTraits_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01const_01_4.html", null ],
    [ "helios::details::MemberFunctionTraits&lt; R(C::*)(Args...)&gt;", "structhelios_1_1details_1_1MemberFunctionTraits_3_01R_07C_1_1_5_08_07Args_8_8_8_08_4.html", null ],
    [ "std::pmr::memory_resource", null, [
      [ "helios::mem::ArenaAllocator", "classhelios_1_1mem_1_1ArenaAllocator.html", null ],
      [ "helios::mem::FixedArenaAllocator", "classhelios_1_1mem_1_1FixedArenaAllocator.html", null ],
      [ "helios::mem::FixedFreeListAllocator", "classhelios_1_1mem_1_1FixedFreeListAllocator.html", null ],
      [ "helios::mem::FixedPoolAllocator", "classhelios_1_1mem_1_1FixedPoolAllocator.html", null ],
      [ "helios::mem::FixedStackAllocator", "classhelios_1_1mem_1_1FixedStackAllocator.html", null ],
      [ "helios::mem::FrameAllocator< N >", "classhelios_1_1mem_1_1FrameAllocator.html", null ],
      [ "helios::mem::FreeListAllocator", "classhelios_1_1mem_1_1FreeListAllocator.html", null ],
      [ "helios::mem::PoolAllocator", "classhelios_1_1mem_1_1PoolAllocator.html", null ],
      [ "helios::mem::StackAllocator", "classhelios_1_1mem_1_1StackAllocator.html", null ],
      [ "helios::mem::TemporaryStorage", "classhelios_1_1mem_1_1TemporaryStorage.html", null ]
    ] ],
    [ "helios::ecs::MessageCursor&lt; T &gt;", "structhelios_1_1ecs_1_1MessageCursor.html", null ],
    [ "helios::ecs::MessageId&lt; T &gt;", "structhelios_1_1ecs_1_1MessageId.html", null ],
    [ "helios::ecs::MessageManager", "classhelios_1_1ecs_1_1MessageManager.html", null ],
    [ "helios::ecs::MessageMetadata", "structhelios_1_1ecs_1_1MessageMetadata.html", null ],
    [ "helios::ecs::MessageQueue", "classhelios_1_1ecs_1_1MessageQueue.html", null ],
    [ "helios::ecs::MessageReaderBase&lt; Derived, T, IterType &gt;", "classhelios_1_1ecs_1_1MessageReaderBase.html", null ],
    [ "helios::ecs::MessageReaderBase&lt; ConsumableMessageReader&lt; T &gt;, T, ConsumableMessageWrapperIter&lt; T &gt; &gt;", "classhelios_1_1ecs_1_1MessageReaderBase.html", [
      [ "helios::ecs::ConsumableMessageReader< T >", "classhelios_1_1ecs_1_1ConsumableMessageReader.html", null ]
    ] ],
    [ "helios::ecs::MessageReaderBase&lt; MessageReader&lt; T &gt;, T, MessageWrapperIter&lt; T &gt; &gt;", "classhelios_1_1ecs_1_1MessageReaderBase.html", [
      [ "helios::ecs::MessageReader< helios::input::GamepadConnectionMsg >", "classhelios_1_1ecs_1_1MessageReader.html", null ],
      [ "helios::ecs::MessageReader< helios::input::GamepadButtonInputMsg >", "classhelios_1_1ecs_1_1MessageReader.html", null ],
      [ "helios::ecs::MessageReader< helios::input::GamepadAxisChangedMsg >", "classhelios_1_1ecs_1_1MessageReader.html", null ],
      [ "helios::ecs::MessageReader< helios::input::GamepadRemappedMsg >", "classhelios_1_1ecs_1_1MessageReader.html", null ],
      [ "helios::ecs::MessageReader< helios::input::GamepadPowerChangedMsg >", "classhelios_1_1ecs_1_1MessageReader.html", null ],
      [ "helios::ecs::MessageReader< helios::input::GamepadSensorUpdateMsg >", "classhelios_1_1ecs_1_1MessageReader.html", null ],
      [ "helios::ecs::MessageReader< helios::input::GamepadTouchpadMsg >", "classhelios_1_1ecs_1_1MessageReader.html", null ],
      [ "helios::ecs::MessageReader< helios::input::JoystickConnectionMsg >", "classhelios_1_1ecs_1_1MessageReader.html", null ],
      [ "helios::ecs::MessageReader< helios::input::JoystickButtonInputMsg >", "classhelios_1_1ecs_1_1MessageReader.html", null ],
      [ "helios::ecs::MessageReader< helios::input::JoystickAxisChangedMsg >", "classhelios_1_1ecs_1_1MessageReader.html", null ],
      [ "helios::ecs::MessageReader< helios::input::JoystickHatChangedMsg >", "classhelios_1_1ecs_1_1MessageReader.html", null ],
      [ "helios::ecs::MessageReader< helios::input::KeyboardInputMsg >", "classhelios_1_1ecs_1_1MessageReader.html", null ],
      [ "helios::ecs::MessageReader< helios::input::TextInputMsg >", "classhelios_1_1ecs_1_1MessageReader.html", null ],
      [ "helios::ecs::MessageReader< helios::input::MouseButtonInputMsg >", "classhelios_1_1ecs_1_1MessageReader.html", null ],
      [ "helios::ecs::MessageReader< helios::input::CursorMovedMsg >", "classhelios_1_1ecs_1_1MessageReader.html", null ],
      [ "helios::ecs::MessageReader< helios::input::MouseMotionMsg >", "classhelios_1_1ecs_1_1MessageReader.html", null ],
      [ "helios::ecs::MessageReader< helios::input::MouseWheelMsg >", "classhelios_1_1ecs_1_1MessageReader.html", null ],
      [ "helios::ecs::MessageReader< helios::input::PenProximityMsg >", "classhelios_1_1ecs_1_1MessageReader.html", null ],
      [ "helios::ecs::MessageReader< helios::input::PenTouchMsg >", "classhelios_1_1ecs_1_1MessageReader.html", null ],
      [ "helios::ecs::MessageReader< helios::input::PenButtonInputMsg >", "classhelios_1_1ecs_1_1MessageReader.html", null ],
      [ "helios::ecs::MessageReader< helios::input::PenMovedMsg >", "classhelios_1_1ecs_1_1MessageReader.html", null ],
      [ "helios::ecs::MessageReader< helios::input::PenAxisChangedMsg >", "classhelios_1_1ecs_1_1MessageReader.html", null ],
      [ "helios::ecs::MessageReader< helios::window::ModeChangedMsg >", "classhelios_1_1ecs_1_1MessageReader.html", null ],
      [ "helios::ecs::MessageReader< helios::window::CursorModeChangedMsg >", "classhelios_1_1ecs_1_1MessageReader.html", null ],
      [ "helios::ecs::MessageReader< helios::window::VisibilityChangedMsg >", "classhelios_1_1ecs_1_1MessageReader.html", null ],
      [ "helios::ecs::MessageReader< helios::window::FocusChangedMsg >", "classhelios_1_1ecs_1_1MessageReader.html", null ],
      [ "helios::ecs::MessageReader< helios::window::MaximizedChangedMsg >", "classhelios_1_1ecs_1_1MessageReader.html", null ],
      [ "helios::ecs::MessageReader< helios::window::IconChangedMsg >", "classhelios_1_1ecs_1_1MessageReader.html", null ],
      [ "helios::ecs::MessageReader< helios::window::ResizableChangedMsg >", "classhelios_1_1ecs_1_1MessageReader.html", null ],
      [ "helios::ecs::MessageReader< helios::window::DecoratedChangedMsg >", "classhelios_1_1ecs_1_1MessageReader.html", null ],
      [ "helios::ecs::MessageReader< helios::window::OpacityChangedMsg >", "classhelios_1_1ecs_1_1MessageReader.html", null ],
      [ "helios::ecs::MessageReader< helios::window::FloatingChangedMsg >", "classhelios_1_1ecs_1_1MessageReader.html", null ],
      [ "helios::ecs::MessageReader< helios::window::HoverChangedMsg >", "classhelios_1_1ecs_1_1MessageReader.html", null ],
      [ "helios::ecs::MessageReader< helios::window::MousePassthroughChangedMsg >", "classhelios_1_1ecs_1_1MessageReader.html", null ],
      [ "helios::ecs::MessageReader< helios::window::ResizedMsg >", "classhelios_1_1ecs_1_1MessageReader.html", null ],
      [ "helios::ecs::MessageReader< helios::window::ClientResizedMsg >", "classhelios_1_1ecs_1_1MessageReader.html", null ],
      [ "helios::ecs::MessageReader< helios::window::ContentScaleChangedMsg >", "classhelios_1_1ecs_1_1MessageReader.html", null ],
      [ "helios::ecs::MessageReader< helios::window::PosChangedMsg >", "classhelios_1_1ecs_1_1MessageReader.html", null ],
      [ "helios::ecs::MessageReader< helios::window::CreatedMsg >", "classhelios_1_1ecs_1_1MessageReader.html", null ],
      [ "helios::ecs::MessageReader< helios::window::ClosedMsg >", "classhelios_1_1ecs_1_1MessageReader.html", null ],
      [ "helios::ecs::MessageReader< helios::window::CloseRequestedMsg >", "classhelios_1_1ecs_1_1MessageReader.html", null ],
      [ "helios::ecs::MessageReader< helios::window::CreationFailedMsg >", "classhelios_1_1ecs_1_1MessageReader.html", null ],
      [ "helios::ecs::MessageReader< helios::window::ClipboardChangedMsg >", "classhelios_1_1ecs_1_1MessageReader.html", null ],
      [ "helios::ecs::MessageReader< helios::window::DroppedFilesMsg >", "classhelios_1_1ecs_1_1MessageReader.html", null ],
      [ "helios::ecs::MessageReader< helios::window::MonitorConnectedMsg >", "classhelios_1_1ecs_1_1MessageReader.html", null ],
      [ "helios::ecs::MessageReader< helios::window::MonitorDisconnectedMsg >", "classhelios_1_1ecs_1_1MessageReader.html", null ],
      [ "helios::ecs::MessageReader< T >", "classhelios_1_1ecs_1_1MessageReader.html", null ]
    ] ],
    [ "helios::input::Messages", "structhelios_1_1input_1_1Messages.html", null ],
    [ "helios::window::Messages", "structhelios_1_1window_1_1Messages.html", null ],
    [ "helios::ecs::MessageWrapper&lt; T &gt;", "classhelios_1_1ecs_1_1MessageWrapper.html", null ],
    [ "helios::window::ModeChangedMsg", "structhelios_1_1window_1_1ModeChangedMsg.html", null ],
    [ "helios::window::Monitor", "structhelios_1_1window_1_1Monitor.html", null ],
    [ "helios::window::MonitorConnectedMsg", "structhelios_1_1window_1_1MonitorConnectedMsg.html", null ],
    [ "helios::window::MonitorDisconnectedMsg", "structhelios_1_1window_1_1MonitorDisconnectedMsg.html", null ],
    [ "helios::window::Monitors", "structhelios_1_1window_1_1Monitors.html", null ],
    [ "helios::input::Mouse", "structhelios_1_1input_1_1Mouse.html", null ],
    [ "helios::input::MouseButtonInputMsg", "structhelios_1_1input_1_1MouseButtonInputMsg.html", null ],
    [ "helios::input::MouseMessages", "structhelios_1_1input_1_1MouseMessages.html", null ],
    [ "helios::input::MouseMotionMsg", "structhelios_1_1input_1_1MouseMotionMsg.html", null ],
    [ "helios::window::MousePassthroughChangedMsg", "structhelios_1_1window_1_1MousePassthroughChangedMsg.html", null ],
    [ "helios::input::MouseWheelMsg", "structhelios_1_1input_1_1MouseWheelMsg.html", null ],
    [ "helios::input::MouseWriters", "structhelios_1_1input_1_1MouseWriters.html", null ],
    [ "helios::container::MultiTypeMap&lt; Storage &gt;", "classhelios_1_1container_1_1MultiTypeMap.html", null ],
    [ "helios::window::NativeHandleComponent", "structhelios_1_1window_1_1NativeHandleComponent.html", null ],
    [ "helios::window::OpacityChangedMsg", "structhelios_1_1window_1_1OpacityChangedMsg.html", null ],
    [ "helios::input::Pen", "structhelios_1_1input_1_1Pen.html", null ],
    [ "helios::input::PenAxisChangedMsg", "structhelios_1_1input_1_1PenAxisChangedMsg.html", null ],
    [ "helios::input::PenButtonInputMsg", "structhelios_1_1input_1_1PenButtonInputMsg.html", null ],
    [ "helios::input::PenMessages", "structhelios_1_1input_1_1PenMessages.html", null ],
    [ "helios::input::PenMovedMsg", "structhelios_1_1input_1_1PenMovedMsg.html", null ],
    [ "helios::input::PenProximityMsg", "structhelios_1_1input_1_1PenProximityMsg.html", null ],
    [ "helios::input::Pens", "structhelios_1_1input_1_1Pens.html", null ],
    [ "helios::input::PenTouchMsg", "structhelios_1_1input_1_1PenTouchMsg.html", null ],
    [ "helios::input::PenWriters", "structhelios_1_1input_1_1PenWriters.html", null ],
    [ "helios::window::PlatformMessages", "structhelios_1_1window_1_1PlatformMessages.html", null ],
    [ "helios::window::PlatformWriters", "structhelios_1_1window_1_1PlatformWriters.html", null ],
    [ "helios::app::Plugin", "classhelios_1_1app_1_1Plugin.html", [
      [ "helios::app::ExecutorPlugin", "classhelios_1_1app_1_1ExecutorPlugin.html", null ],
      [ "helios::app::FrameCountPlugin", "classhelios_1_1app_1_1FrameCountPlugin.html", null ],
      [ "helios::app::FrameLimiterPlugin", "classhelios_1_1app_1_1FrameLimiterPlugin.html", null ],
      [ "helios::app::TimePlugin", "classhelios_1_1app_1_1TimePlugin.html", null ],
      [ "helios::glfw::Plugin", "structhelios_1_1glfw_1_1Plugin.html", null ],
      [ "helios::input::Plugin", "structhelios_1_1input_1_1Plugin.html", null ],
      [ "helios::sdl3::Plugin", "structhelios_1_1sdl3_1_1Plugin.html", null ],
      [ "helios::sdl3::input::Plugin", "structhelios_1_1sdl3_1_1input_1_1Plugin.html", null ],
      [ "helios::sdl3::window::Plugin", "structhelios_1_1sdl3_1_1window_1_1Plugin.html", null ],
      [ "helios::window::Plugin", "structhelios_1_1window_1_1Plugin.html", null ]
    ] ],
    [ "helios::app::PluginGroup", "classhelios_1_1app_1_1PluginGroup.html", [
      [ "helios::glfw::WindowPlugin", "structhelios_1_1glfw_1_1WindowPlugin.html", null ],
      [ "helios::sdl3::input::InputPlugin", "structhelios_1_1sdl3_1_1input_1_1InputPlugin.html", null ],
      [ "helios::sdl3::window::WindowPlugin", "structhelios_1_1sdl3_1_1window_1_1WindowPlugin.html", null ]
    ] ],
    [ "helios::app::PluginTypeExport", "structhelios_1_1app_1_1PluginTypeExport.html", null ],
    [ "helios::glfw::PollEvents", "structhelios_1_1glfw_1_1PollEvents.html", null ],
    [ "helios::sdl3::window::PollEvents", "structhelios_1_1sdl3_1_1window_1_1PollEvents.html", null ],
    [ "helios::sdl3::input::PollGamepads", "structhelios_1_1sdl3_1_1input_1_1PollGamepads.html", null ],
    [ "helios::mem::PoolAllocatorOptions", "structhelios_1_1mem_1_1PoolAllocatorOptions.html", null ],
    [ "helios::window::PosChangedMsg", "structhelios_1_1window_1_1PosChangedMsg.html", null ],
    [ "helios::app::PostShutdown", "structhelios_1_1app_1_1PostShutdown.html", null ],
    [ "helios::app::PostStartup", "structhelios_1_1app_1_1PostStartup.html", null ],
    [ "helios::app::PostUpdate", "structhelios_1_1app_1_1PostUpdate.html", null ],
    [ "helios::details::PrependReturnType&lt; R, ArgsTuple &gt;", "structhelios_1_1details_1_1PrependReturnType.html", null ],
    [ "helios::details::PrependReturnType&lt; R, std::tuple&lt; Args... &gt; &gt;", "structhelios_1_1details_1_1PrependReturnType_3_01R_00_01std_1_1tuple_3_01Args_8_8_8_01_4_01_4.html", null ],
    [ "helios::app::PreShutdown", "structhelios_1_1app_1_1PreShutdown.html", null ],
    [ "helios::app::PreStartup", "structhelios_1_1app_1_1PreStartup.html", null ],
    [ "helios::app::PreUpdate", "structhelios_1_1app_1_1PreUpdate.html", null ],
    [ "helios::window::Primary", "structhelios_1_1window_1_1Primary.html", null ],
    [ "helios::window::PrimaryWindow", "structhelios_1_1window_1_1PrimaryWindow.html", null ],
    [ "helios::window::PrimaryWindows", "structhelios_1_1window_1_1PrimaryWindows.html", null ],
    [ "helios::window::PrimaryWindowsView", "structhelios_1_1window_1_1PrimaryWindowsView.html", null ],
    [ "helios::profile::Profiler", "classhelios_1_1profile_1_1Profiler.html", null ],
    [ "helios::window::Properties", "structhelios_1_1window_1_1Properties.html", null ],
    [ "helios::sdl3::PumpEvents", "structhelios_1_1sdl3_1_1PumpEvents.html", null ],
    [ "helios::utils::RandomGenerator&lt; Engine &gt;", "classhelios_1_1utils_1_1RandomGenerator.html", null ],
    [ "helios::mem::RcFromThis&lt; Derived &gt;", "classhelios_1_1mem_1_1RcFromThis.html", null ],
    [ "helios::mem::RefCounted&lt; Derived &gt;", "classhelios_1_1mem_1_1RefCounted.html", null ],
    [ "helios::ecs::details::RegisterQueryAccess&lt; Tuple &gt;", "structhelios_1_1ecs_1_1details_1_1RegisterQueryAccess.html", null ],
    [ "helios::ecs::details::RegisterQueryAccess&lt; std::tuple&lt; Cs... &gt; &gt;", "structhelios_1_1ecs_1_1details_1_1RegisterQueryAccess_3_01std_1_1tuple_3_01Cs_8_8_8_01_4_01_4.html", null ],
    [ "helios::ecs::RemoveBundleCmd&lt; B &gt;", "classhelios_1_1ecs_1_1RemoveBundleCmd.html", null ],
    [ "helios::ecs::RemoveComponentsCmd&lt; Ts &gt;", "classhelios_1_1ecs_1_1RemoveComponentsCmd.html", null ],
    [ "helios::ecs::RemoveResourceCmd&lt; T &gt;", "structhelios_1_1ecs_1_1RemoveResourceCmd.html", null ],
    [ "helios::ecs::Res&lt; T &gt;", "classhelios_1_1ecs_1_1Res.html", null ],
    [ "helios::window::ResizableChangedMsg", "structhelios_1_1window_1_1ResizableChangedMsg.html", null ],
    [ "helios::window::ResizedMsg", "structhelios_1_1window_1_1ResizedMsg.html", null ],
    [ "helios::ecs::ResourceConflictInfo", "structhelios_1_1ecs_1_1ResourceConflictInfo.html", null ],
    [ "helios::ecs::ResourceInsertedMsg&lt; T &gt;", "structhelios_1_1ecs_1_1ResourceInsertedMsg.html", null ],
    [ "helios::ecs::ResourceManager", "classhelios_1_1ecs_1_1ResourceManager.html", null ],
    [ "helios::ecs::ResourceRemovedMsg&lt; T &gt;", "structhelios_1_1ecs_1_1ResourceRemovedMsg.html", null ],
    [ "helios::ecs::RunConditionStorage", "structhelios_1_1ecs_1_1RunConditionStorage.html", null ],
    [ "helios::ecs::RunStageOptions", "structhelios_1_1ecs_1_1RunStageOptions.html", null ],
    [ "helios::ecs::Schedule", "classhelios_1_1ecs_1_1Schedule.html", null ],
    [ "helios::ecs::ScheduleError", "structhelios_1_1ecs_1_1ScheduleError.html", null ],
    [ "helios::ecs::ScheduleOrdering", "classhelios_1_1ecs_1_1ScheduleOrdering.html", null ],
    [ "helios::app::Scheduler", "classhelios_1_1app_1_1Scheduler.html", null ],
    [ "helios::ecs::Scheduler", "classhelios_1_1ecs_1_1Scheduler.html", null ],
    [ "helios::ecs::ScheduleRunScope", "classhelios_1_1ecs_1_1ScheduleRunScope.html", null ],
    [ "helios::ecs::ScheduleSettings", "structhelios_1_1ecs_1_1ScheduleSettings.html", null ],
    [ "helios::ecs::ScheduleSystemId", "structhelios_1_1ecs_1_1ScheduleSystemId.html", null ],
    [ "helios::ecs::ScheduleSystemMetadata", "structhelios_1_1ecs_1_1ScheduleSystemMetadata.html", null ],
    [ "helios::profile::ScopedZone", "classhelios_1_1profile_1_1ScopedZone.html", null ],
    [ "helios::input::Settings", "structhelios_1_1input_1_1Settings.html", null ],
    [ "helios::window::Settings", "structhelios_1_1window_1_1Settings.html", null ],
    [ "helios::app::Shutdown", "structhelios_1_1app_1_1Shutdown.html", null ],
    [ "helios::glfw::Shutdown", "structhelios_1_1glfw_1_1Shutdown.html", null ],
    [ "helios::sdl3::Shutdown", "structhelios_1_1sdl3_1_1Shutdown.html", null ],
    [ "helios::sdl3::window::Shutdown", "structhelios_1_1sdl3_1_1window_1_1Shutdown.html", null ],
    [ "helios::sdl3::ShutdownSet", "structhelios_1_1sdl3_1_1ShutdownSet.html", null ],
    [ "helios::sdl3::window::ShutdownSet", "structhelios_1_1sdl3_1_1window_1_1ShutdownSet.html", null ],
    [ "helios::app::ShutdownStage", "structhelios_1_1app_1_1ShutdownStage.html", null ],
    [ "helios::utils::SlideView&lt; Iter &gt;", "classhelios_1_1utils_1_1SlideView.html", null ],
    [ "helios::ecs::SparseComponentStorage&lt; T &gt;", "classhelios_1_1ecs_1_1SparseComponentStorage.html", null ],
    [ "helios::container::SparseSet&lt; T, IndexType &gt;", "classhelios_1_1container_1_1SparseSet.html", null ],
    [ "helios::ecs::ComponentManager::SparseStorageEntry", "structhelios_1_1ecs_1_1ComponentManager_1_1SparseStorageEntry.html", null ],
    [ "helios::mem::StackAllocatorOptions", "structhelios_1_1mem_1_1StackAllocatorOptions.html", null ],
    [ "helios::Stacktrace", "classhelios_1_1Stacktrace.html", null ],
    [ "helios::StacktraceConfig", "structhelios_1_1StacktraceConfig.html", null ],
    [ "helios::ecs::StageOrdering", "classhelios_1_1ecs_1_1StageOrdering.html", null ],
    [ "helios::ecs::StageSettings", "structhelios_1_1ecs_1_1StageSettings.html", null ],
    [ "helios::app::Startup", "structhelios_1_1app_1_1Startup.html", null ],
    [ "helios::sdl3::input::StartupSet", "structhelios_1_1sdl3_1_1input_1_1StartupSet.html", null ],
    [ "helios::sdl3::StartupSet", "structhelios_1_1sdl3_1_1StartupSet.html", null ],
    [ "helios::sdl3::window::StartupSet", "structhelios_1_1sdl3_1_1window_1_1StartupSet.html", null ],
    [ "helios::app::StartupStage", "structhelios_1_1app_1_1StartupStage.html", null ],
    [ "helios::input::State", "structhelios_1_1input_1_1State.html", null ],
    [ "helios::input::StateView", "structhelios_1_1input_1_1StateView.html", null ],
    [ "helios::utils::StringEqual", "structhelios_1_1utils_1_1StringEqual.html", null ],
    [ "helios::utils::StringHash", "structhelios_1_1utils_1_1StringHash.html", null ],
    [ "helios::utils::StringLess", "structhelios_1_1utils_1_1StringLess.html", null ],
    [ "helios::app::SubApp", "classhelios_1_1app_1_1SubApp.html", null ],
    [ "helios::async::SubTaskGraph", "classhelios_1_1async_1_1SubTaskGraph.html", null ],
    [ "helios::window::SyncFrameLimiterRefreshRate", "structhelios_1_1window_1_1SyncFrameLimiterRefreshRate.html", null ],
    [ "helios::ecs::details::SystemArgsTupleImpl&lt; T, kHasCallOperator &gt;", "structhelios_1_1ecs_1_1details_1_1SystemArgsTupleImpl.html", null ],
    [ "helios::ecs::details::SystemArgsTupleImpl&lt; T, true &gt;", "structhelios_1_1ecs_1_1details_1_1SystemArgsTupleImpl_3_01T_00_01true_01_4.html", null ],
    [ "helios::ecs::SystemGroupHandle", "classhelios_1_1ecs_1_1SystemGroupHandle.html", null ],
    [ "helios::ecs::SystemHandle", "classhelios_1_1ecs_1_1SystemHandle.html", null ],
    [ "helios::ecs::SystemId", "structhelios_1_1ecs_1_1SystemId.html", null ],
    [ "helios::ecs::SystemLocalData", "structhelios_1_1ecs_1_1SystemLocalData.html", null ],
    [ "helios::ecs::SystemLocalDataOptions", "structhelios_1_1ecs_1_1SystemLocalDataOptions.html", null ],
    [ "helios::ecs::SystemParamTraits&lt; T &gt;", "structhelios_1_1ecs_1_1SystemParamTraits.html", null ],
    [ "helios::ecs::SystemParamTraits&lt; AsyncMessageReader&lt; T &gt; &gt;", "structhelios_1_1ecs_1_1SystemParamTraits_3_01AsyncMessageReader_3_01T_01_4_01_4.html", null ],
    [ "helios::ecs::SystemParamTraits&lt; AsyncMessageWriter&lt; T &gt; &gt;", "structhelios_1_1ecs_1_1SystemParamTraits_3_01AsyncMessageWriter_3_01T_01_4_01_4.html", null ],
    [ "helios::ecs::SystemParamTraits&lt; Commands &gt;", "structhelios_1_1ecs_1_1SystemParamTraits_3_01Commands_01_4.html", null ],
    [ "helios::ecs::SystemParamTraits&lt; ConsumableMessageReader&lt; T &gt; &gt;", "structhelios_1_1ecs_1_1SystemParamTraits_3_01ConsumableMessageReader_3_01T_01_4_01_4.html", null ],
    [ "helios::ecs::SystemParamTraits&lt; Local&lt; const LocalArena &gt; &gt;", "structhelios_1_1ecs_1_1SystemParamTraits_3_01Local_3_01const_01LocalArena_01_4_01_4.html", null ],
    [ "helios::ecs::SystemParamTraits&lt; Local&lt; const T &gt; &gt;", "structhelios_1_1ecs_1_1SystemParamTraits_3_01Local_3_01const_01T_01_4_01_4.html", null ],
    [ "helios::ecs::SystemParamTraits&lt; Local&lt; LocalArena &gt; &gt;", "structhelios_1_1ecs_1_1SystemParamTraits_3_01Local_3_01LocalArena_01_4_01_4.html", null ],
    [ "helios::ecs::SystemParamTraits&lt; Local&lt; T &gt; &gt;", "structhelios_1_1ecs_1_1SystemParamTraits_3_01Local_3_01T_01_4_01_4.html", null ],
    [ "helios::ecs::SystemParamTraits&lt; MessageReader&lt; T &gt; &gt;", "structhelios_1_1ecs_1_1SystemParamTraits_3_01MessageReader_3_01T_01_4_01_4.html", null ],
    [ "helios::ecs::SystemParamTraits&lt; MessageWriter&lt; T &gt; &gt;", "structhelios_1_1ecs_1_1SystemParamTraits_3_01MessageWriter_3_01T_01_4_01_4.html", null ],
    [ "helios::ecs::SystemParamTraits&lt; OptRes&lt; const T &gt; &gt;", "structhelios_1_1ecs_1_1SystemParamTraits_3_01OptRes_3_01const_01T_01_4_01_4.html", null ],
    [ "helios::ecs::SystemParamTraits&lt; OptRes&lt; T &gt; &gt;", "structhelios_1_1ecs_1_1SystemParamTraits_3_01OptRes_3_01T_01_4_01_4.html", null ],
    [ "helios::ecs::SystemParamTraits&lt; Query&lt; Args... &gt; &gt;", "structhelios_1_1ecs_1_1SystemParamTraits_3_01Query_3_01Args_8_8_8_01_4_01_4.html", null ],
    [ "helios::ecs::SystemParamTraits&lt; Res&lt; const T &gt; &gt;", "structhelios_1_1ecs_1_1SystemParamTraits_3_01Res_3_01const_01T_01_4_01_4.html", null ],
    [ "helios::ecs::SystemParamTraits&lt; Res&lt; T &gt; &gt;", "structhelios_1_1ecs_1_1SystemParamTraits_3_01Res_3_01T_01_4_01_4.html", null ],
    [ "helios::ecs::SystemParamTraits&lt; World &gt;", "structhelios_1_1ecs_1_1SystemParamTraits_3_01World_01_4.html", null ],
    [ "helios::ecs::SystemParamTraits&lt; WorldView &gt;", "structhelios_1_1ecs_1_1SystemParamTraits_3_01WorldView_01_4.html", null ],
    [ "helios::ecs::SystemSet", "classhelios_1_1ecs_1_1SystemSet.html", null ],
    [ "helios::ecs::SystemSetHandle", "classhelios_1_1ecs_1_1SystemSetHandle.html", null ],
    [ "helios::ecs::SystemSetId", "structhelios_1_1ecs_1_1SystemSetId.html", null ],
    [ "helios::ecs::SystemStorage", "structhelios_1_1ecs_1_1SystemStorage.html", null ],
    [ "helios::async::Task", "classhelios_1_1async_1_1Task.html", null ],
    [ "helios::async::TaskGraph", "classhelios_1_1async_1_1TaskGraph.html", null ],
    [ "helios::input::TextInputMsg", "structhelios_1_1input_1_1TextInputMsg.html", null ],
    [ "helios::app::Time", "structhelios_1_1app_1_1Time.html", null ],
    [ "helios::utils::Timer&lt; Clock &gt;", "classhelios_1_1utils_1_1Timer.html", null ],
    [ "helios::ecs::anonymous_namespace{scheduler.cpp}::TopoNode", "structhelios_1_1ecs_1_1anonymous__namespace_02scheduler_8cpp_03_1_1TopoNode.html", null ],
    [ "std::true_type", null, [
      [ "helios::utils::details::UniqueTypesHelper< T, Rest... >", "structhelios_1_1utils_1_1details_1_1UniqueTypesHelper_3_01T_00_01Rest_8_8_8_01_4.html", null ],
      [ "helios::ecs::details::HasStructBundleBuild< T >", "structhelios_1_1ecs_1_1details_1_1HasStructBundleBuild_3_01T_01_4.html", null ],
      [ "helios::ecs::details::IsComponentBundle< ComponentBundleTypes< Ts... > >", "structhelios_1_1ecs_1_1details_1_1IsComponentBundle_3_01ComponentBundleTypes_3_01Ts_8_8_8_01_4_01_4.html", null ],
      [ "helios::ecs::details::IsComponentBundleTypes< ComponentBundleTypes< Ts... > >", "structhelios_1_1ecs_1_1details_1_1IsComponentBundleTypes_3_01ComponentBundleTypes_3_01Ts_8_8_8_01_4_01_4.html", null ],
      [ "helios::utils::details::UniqueTypesHelper<... >", "structhelios_1_1utils_1_1details_1_1UniqueTypesHelper.html", null ]
    ] ],
    [ "helios::ecs::TryAddBundleCmd&lt; B &gt;", "classhelios_1_1ecs_1_1TryAddBundleCmd.html", null ],
    [ "helios::ecs::TryAddComponentsCmd&lt; Ts &gt;", "classhelios_1_1ecs_1_1TryAddComponentsCmd.html", null ],
    [ "helios::ecs::TryDestroyEntitiesCmd", "classhelios_1_1ecs_1_1TryDestroyEntitiesCmd.html", null ],
    [ "helios::ecs::TryDestroyEntityCmd", "classhelios_1_1ecs_1_1TryDestroyEntityCmd.html", null ],
    [ "helios::ecs::TryInsertResourceCmd&lt; T &gt;", "classhelios_1_1ecs_1_1TryInsertResourceCmd.html", null ],
    [ "helios::ecs::TryRemoveBundleCmd&lt; B &gt;", "classhelios_1_1ecs_1_1TryRemoveBundleCmd.html", null ],
    [ "helios::ecs::TryRemoveComponentsCmd&lt; Ts &gt;", "classhelios_1_1ecs_1_1TryRemoveComponentsCmd.html", null ],
    [ "helios::ecs::TryRemoveResourceCmd&lt; T &gt;", "structhelios_1_1ecs_1_1TryRemoveResourceCmd.html", null ],
    [ "helios::details::TupleToFunctionSignature&lt; T &gt;", "structhelios_1_1details_1_1TupleToFunctionSignature.html", null ],
    [ "helios::details::TupleToFunctionSignature&lt; std::tuple&lt; R, Args... &gt; &gt;", "structhelios_1_1details_1_1TupleToFunctionSignature_3_01std_1_1tuple_3_01R_00_01Args_8_8_8_01_4_01_4.html", null ],
    [ "helios::container::TypedBuffer", "classhelios_1_1container_1_1TypedBuffer.html", null ],
    [ "helios::container::TypedBufferArray", "classhelios_1_1container_1_1TypedBufferArray.html", null ],
    [ "helios::utils::TypeId", "classhelios_1_1utils_1_1TypeId.html", null ],
    [ "helios::utils::TypeIndex", "classhelios_1_1utils_1_1TypeIndex.html", null ],
    [ "helios::app::Update", "structhelios_1_1app_1_1Update.html", null ],
    [ "helios::input::UpdateGamepadState", "structhelios_1_1input_1_1UpdateGamepadState.html", null ],
    [ "helios::input::UpdateJoystickState", "structhelios_1_1input_1_1UpdateJoystickState.html", null ],
    [ "helios::input::UpdateKeyboardState", "structhelios_1_1input_1_1UpdateKeyboardState.html", null ],
    [ "helios::input::UpdateMouseState", "structhelios_1_1input_1_1UpdateMouseState.html", null ],
    [ "helios::input::UpdatePenState", "structhelios_1_1input_1_1UpdatePenState.html", null ],
    [ "helios::app::UpdateStage", "structhelios_1_1app_1_1UpdateStage.html", null ],
    [ "helios::app::UpdateTime", "structhelios_1_1app_1_1UpdateTime.html", null ],
    [ "helios::Uuid", "classhelios_1_1Uuid.html", null ],
    [ "helios::UuidGenerator", "classhelios_1_1UuidGenerator.html", null ],
    [ "helios::window::VideoMode", "structhelios_1_1window_1_1VideoMode.html", null ],
    [ "helios::window::VisibilityChangedMsg", "structhelios_1_1window_1_1VisibilityChangedMsg.html", null ],
    [ "helios::window::Window", "structhelios_1_1window_1_1Window.html", null ],
    [ "helios::window::Windows", "structhelios_1_1window_1_1Windows.html", null ],
    [ "helios::window::WindowStage", "structhelios_1_1window_1_1WindowStage.html", null ],
    [ "helios::window::WindowsView", "structhelios_1_1window_1_1WindowsView.html", null ],
    [ "helios::ecs::World", "classhelios_1_1ecs_1_1World.html", null ],
    [ "helios::ecs::WorldCmdBuffer", "classhelios_1_1ecs_1_1WorldCmdBuffer.html", null ],
    [ "helios::ecs::WorldView", "classhelios_1_1ecs_1_1WorldView.html", null ],
    [ "helios::input::Writers", "structhelios_1_1input_1_1Writers.html", null ],
    [ "helios::window::Writers", "structhelios_1_1window_1_1Writers.html", null ],
    [ "helios::profile::ZoneSpec", "structhelios_1_1profile_1_1ZoneSpec.html", null ]
];