var hierarchy =
[
    [ "helios::ecs::AccessPolicy", "classhelios_1_1ecs_1_1AccessPolicy.html", null ],
    [ "helios::ecs::AccessPolicyBuilder", "classhelios_1_1ecs_1_1AccessPolicyBuilder.html", null ],
    [ "helios::utils::details::adapter_iterator_traits&lt; Iter &gt;", "structhelios_1_1utils_1_1details_1_1adapter__iterator__traits.html", null ],
    [ "helios::ecs::AddComponentsCmd&lt; Ts &gt;", "classhelios_1_1ecs_1_1AddComponentsCmd.html", null ],
    [ "anonymous_namespace{free_list_allocator.cpp}::AllocationHeader", "structanonymous__namespace_02free__list__allocator_8cpp_03_1_1AllocationHeader.html", null ],
    [ "helios::mem::AllocatorStats", "structhelios_1_1mem_1_1AllocatorStats.html", null ],
    [ "helios::app::App", "classhelios_1_1app_1_1App.html", null ],
    [ "helios::app::AppExit", "structhelios_1_1app_1_1AppExit.html", null ],
    [ "helios::mem::ArcFromThis&lt; Derived &gt;", "classhelios_1_1mem_1_1ArcFromThis.html", null ],
    [ "helios::ecs::Archetype", "classhelios_1_1ecs_1_1Archetype.html", null ],
    [ "helios::ecs::ArchetypeId", "classhelios_1_1ecs_1_1ArchetypeId.html", null ],
    [ "helios::mem::ArenaOptions", "structhelios_1_1mem_1_1ArenaOptions.html", null ],
    [ "helios::ecs::AsyncMessageQueue", "classhelios_1_1ecs_1_1AsyncMessageQueue.html", null ],
    [ "helios::ecs::AsyncMessageReader&lt; T &gt;", "classhelios_1_1ecs_1_1AsyncMessageReader.html", null ],
    [ "helios::ecs::details::AsyncMessageStorage", "classhelios_1_1ecs_1_1details_1_1AsyncMessageStorage.html", [
      [ "helios::ecs::TypedAsyncMessageStorage< T >", "classhelios_1_1ecs_1_1TypedAsyncMessageStorage.html", null ]
    ] ],
    [ "helios::ecs::AsyncMessageWrapper&lt; T &gt;", "classhelios_1_1ecs_1_1AsyncMessageWrapper.html", null ],
    [ "helios::ecs::AsyncMessageWriter&lt; T &gt;", "classhelios_1_1ecs_1_1AsyncMessageWriter.html", null ],
    [ "helios::async::AsyncTask", "classhelios_1_1async_1_1AsyncTask.html", null ],
    [ "helios::mem::AtomicRefCounted&lt; Derived, Allocator &gt;", "classhelios_1_1mem_1_1AtomicRefCounted.html", null ],
    [ "helios::profile::Backend", "classhelios_1_1profile_1_1Backend.html", [
      [ "helios::profile::FlamegraphBackend", "classhelios_1_1profile_1_1FlamegraphBackend.html", null ],
      [ "helios::profile::TracyBackend", "classhelios_1_1profile_1_1TracyBackend.html", null ]
    ] ],
    [ "helios::BasicCStringView&lt; CharT, Traits &gt;", "classhelios_1_1BasicCStringView.html", null ],
    [ "helios::ecs::BasicMessageWriter&lt; T, Allocator &gt;", "classhelios_1_1ecs_1_1BasicMessageWriter.html", null ],
    [ "helios::ecs::BasicQuery&lt; WorldT, Allocator, Args &gt;", "classhelios_1_1ecs_1_1BasicQuery.html", null ],
    [ "helios::ecs::BasicQueryWithEntity&lt; WorldT, Allocator, Args &gt;", "classhelios_1_1ecs_1_1BasicQueryWithEntity.html", null ],
    [ "helios::container::BasicStaticString&lt; StrCapacity, CharT, Traits &gt;", "classhelios_1_1container_1_1BasicStaticString.html", null ],
    [ "std::bool_constant", null, [
      [ "helios::utils::details::UniqueTypesHelper< T, Rest... >", "structhelios_1_1utils_1_1details_1_1UniqueTypesHelper_3_01T_00_01Rest_8_8_8_01_4.html", null ],
      [ "helios::utils::details::is_folder_applicable_impl< Folder, Accumulator, std::tuple< TupleArgs... > >", "structhelios_1_1utils_1_1details_1_1is__folder__applicable__impl_3_01Folder_00_01Accumulator_00_5474f6b3ac109ab26feda2bd4f995a76.html", null ]
    ] ],
    [ "helios::container::details::CallableBufferArrayDeducer&lt; Args &gt;", "structhelios_1_1container_1_1details_1_1CallableBufferArrayDeducer.html", null ],
    [ "helios::container::details::CallableBufferArrayDeducer&lt; Alloc, FirstSig, RestSigs... &gt;", "structhelios_1_1container_1_1details_1_1CallableBufferArrayDeducer_3_01Alloc_00_01FirstSig_00_01RestSigs_8_8_8_01_4.html", null ],
    [ "helios::container::details::CallableBufferArrayDeducer&lt; FirstSig, RestSigs... &gt;", "structhelios_1_1container_1_1details_1_1CallableBufferArrayDeducer_3_01FirstSig_00_01RestSigs_8_8_8_01_4.html", null ],
    [ "helios::container::CallableBufferArrayImpl&lt; Allocator, Signatures &gt;", "classhelios_1_1container_1_1CallableBufferArrayImpl.html", null ],
    [ "helios::container::details::CallableBufferDeducer&lt; Args &gt;", "structhelios_1_1container_1_1details_1_1CallableBufferDeducer.html", null ],
    [ "helios::container::details::CallableBufferDeducer&lt; Alloc, FirstSig, RestSigs... &gt;", "structhelios_1_1container_1_1details_1_1CallableBufferDeducer_3_01Alloc_00_01FirstSig_00_01RestSigs_8_8_8_01_4.html", null ],
    [ "helios::container::details::CallableBufferDeducer&lt; FirstSig, RestSigs... &gt;", "structhelios_1_1container_1_1details_1_1CallableBufferDeducer_3_01FirstSig_00_01RestSigs_8_8_8_01_4.html", null ],
    [ "helios::container::CallableBufferImpl&lt; Allocator, Signatures &gt;", "classhelios_1_1container_1_1CallableBufferImpl.html", null ],
    [ "anonymous_namespace{stacktrace.cpp}::CapturedFramesResult", "structanonymous__namespace_02stacktrace_8cpp_03_1_1CapturedFramesResult.html", null ],
    [ "helios::ecs::ClearAllMessagesCmd", "structhelios_1_1ecs_1_1ClearAllMessagesCmd.html", null ],
    [ "helios::ecs::ClearComponentsCmd", "classhelios_1_1ecs_1_1ClearComponentsCmd.html", null ],
    [ "helios::ecs::ClearMessagesCmd&lt; T &gt;", "structhelios_1_1ecs_1_1ClearMessagesCmd.html", null ],
    [ "helios::ecs::CmdQueue&lt; Allocator &gt;", "classhelios_1_1ecs_1_1CmdQueue.html", null ],
    [ "helios::ecs::Commands", "classhelios_1_1ecs_1_1Commands.html", null ],
    [ "helios::ecs::ComponentAddedMsg&lt; T &gt;", "classhelios_1_1ecs_1_1ComponentAddedMsg.html", null ],
    [ "helios::ecs::ComponentConflictInfo", "structhelios_1_1ecs_1_1ComponentConflictInfo.html", null ],
    [ "helios::ecs::ComponentManager", "classhelios_1_1ecs_1_1ComponentManager.html", null ],
    [ "helios::ecs::ComponentMetadata", "structhelios_1_1ecs_1_1ComponentMetadata.html", null ],
    [ "helios::ecs::ComponentRemovedMsg&lt; T &gt;", "classhelios_1_1ecs_1_1ComponentRemovedMsg.html", null ],
    [ "helios::ecs::ComponentsClearedMsg", "classhelios_1_1ecs_1_1ComponentsClearedMsg.html", null ],
    [ "helios::ecs::ComponentTraits&lt; T &gt;", "structhelios_1_1ecs_1_1ComponentTraits.html", null ],
    [ "helios::ecs::ComponentTypeInfo", "classhelios_1_1ecs_1_1ComponentTypeInfo.html", null ],
    [ "helios::ecs::CompositeSystemParam&lt; Param, Fields &gt;", "structhelios_1_1ecs_1_1CompositeSystemParam.html", null ],
    [ "helios::log::Config", "structhelios_1_1log_1_1Config.html", null ],
    [ "helios::ecs::ConsumableMessageWrapper&lt; T &gt;", "classhelios_1_1ecs_1_1ConsumableMessageWrapper.html", null ],
    [ "helios::ecs::ConsumedMessagesRegistry&lt; Alloc &gt;", "classhelios_1_1ecs_1_1ConsumedMessagesRegistry.html", null ],
    [ "helios::ecs::Dag", "classhelios_1_1ecs_1_1Dag.html", null ],
    [ "helios::ecs::DagError", "structhelios_1_1ecs_1_1DagError.html", null ],
    [ "helios::log::DefaultLogger", "structhelios_1_1log_1_1DefaultLogger.html", null ],
    [ "helios::utils::Defer&lt; F &gt;", "classhelios_1_1utils_1_1Defer.html", null ],
    [ "helios::utils::details::DeferHelper", "structhelios_1_1utils_1_1details_1_1DeferHelper.html", null ],
    [ "helios::Delegate&lt; FunctionSignature &gt;", "classhelios_1_1Delegate.html", null ],
    [ "helios::Delegate&lt; ReturnType(Args...)&gt;", "classhelios_1_1Delegate_3_01ReturnType_07Args_8_8_8_08_4.html", null ],
    [ "helios::ecs::DestroyEntitiesCmd&lt; Alloc &gt;", "classhelios_1_1ecs_1_1DestroyEntitiesCmd.html", null ],
    [ "helios::ecs::DestroyEntityCmd", "classhelios_1_1ecs_1_1DestroyEntityCmd.html", null ],
    [ "helios::utils::DynamicLibrary", "classhelios_1_1utils_1_1DynamicLibrary.html", null ],
    [ "helios::app::DynamicPlugin", "classhelios_1_1app_1_1DynamicPlugin.html", null ],
    [ "helios::app::DynamicPluginConfig", "structhelios_1_1app_1_1DynamicPluginConfig.html", null ],
    [ "helios::ecs::Entity", "classhelios_1_1ecs_1_1Entity.html", null ],
    [ "helios::ecs::EntityAddedMsg", "classhelios_1_1ecs_1_1EntityAddedMsg.html", null ],
    [ "helios::ecs::EntityCmdBuffer&lt; Allocator &gt;", "classhelios_1_1ecs_1_1EntityCmdBuffer.html", null ],
    [ "helios::ecs::EntityDestroyedMsg", "classhelios_1_1ecs_1_1EntityDestroyedMsg.html", null ],
    [ "helios::ecs::EntityManager", "classhelios_1_1ecs_1_1EntityManager.html", null ],
    [ "helios::async::Executor", "classhelios_1_1async_1_1Executor.html", null ],
    [ "helios::ecs::Executor", "classhelios_1_1ecs_1_1Executor.html", [
      [ "helios::ecs::MainThreadExecutor", "classhelios_1_1ecs_1_1MainThreadExecutor.html", null ],
      [ "helios::ecs::MultiThreadedExecutor", "classhelios_1_1ecs_1_1MultiThreadedExecutor.html", null ],
      [ "helios::ecs::SingleThreadedExecutor", "classhelios_1_1ecs_1_1SingleThreadedExecutor.html", null ]
    ] ],
    [ "helios::app::Extract", "structhelios_1_1app_1_1Extract.html", null ],
    [ "helios::app::ExtractStage", "structhelios_1_1app_1_1ExtractStage.html", null ],
    [ "std::false_type", null, [
      [ "helios::utils::details::is_folder_applicable_impl< Folder, Accumulator, std::tuple< TupleArgs... > >", "structhelios_1_1utils_1_1details_1_1is__folder__applicable__impl_3_01Folder_00_01Accumulator_00_5474f6b3ac109ab26feda2bd4f995a76.html", null ],
      [ "helios::utils::details::is_folder_applicable_impl< Folder, Accumulator, Tuple >", "structhelios_1_1utils_1_1details_1_1is__folder__applicable__impl.html", null ]
    ] ],
    [ "helios::utils::FastPimpl&lt; T, Size, Alignment, RequireStrictMatch &gt;", "classhelios_1_1utils_1_1FastPimpl.html", null ],
    [ "helios::app::First", "structhelios_1_1app_1_1First.html", null ],
    [ "helios::mem::FixedPoolAllocatorOptions", "structhelios_1_1mem_1_1FixedPoolAllocatorOptions.html", null ],
    [ "helios::app::FixedRunnerConfig", "structhelios_1_1app_1_1FixedRunnerConfig.html", null ],
    [ "helios::utils::details::FixedString&lt; N &gt;", "structhelios_1_1utils_1_1details_1_1FixedString.html", null ],
    [ "helios::profile::FlamegraphBackendConfig", "structhelios_1_1profile_1_1FlamegraphBackendConfig.html", null ],
    [ "helios::utils::details::folder_apply_result&lt; Folder, Accumulator, Tuple &gt;", "structhelios_1_1utils_1_1details_1_1folder__apply__result.html", null ],
    [ "helios::utils::details::folder_apply_result&lt; Folder, Accumulator, std::tuple&lt; TupleArgs... &gt; &gt;", "structhelios_1_1utils_1_1details_1_1folder__apply__result_3_01Folder_00_01Accumulator_00_01std_1ce2978c0f27b507bfe0e6e04cc632169.html", null ],
    [ "formatter", null, [
      [ "std::formatter< helios::BasicCStringView< CharT, Traits > >", "structstd_1_1formatter_3_01helios_1_1BasicCStringView_3_01CharT_00_01Traits_01_4_01_4.html", null ],
      [ "std::formatter< helios::container::BasicStaticString< StrCapacity, CharT, Traits > >", "structstd_1_1formatter_3_01helios_1_1container_1_1BasicStaticString_3_01StrCapacity_00_01CharT_00_01Traits_01_4_01_4.html", null ]
    ] ],
    [ "std::formatter&lt; helios::ecs::Entity &gt;", "structstd_1_1formatter_3_01helios_1_1ecs_1_1Entity_01_4.html", null ],
    [ "helios::mem::FrameAllocatorOptions", "structhelios_1_1mem_1_1FrameAllocatorOptions.html", null ],
    [ "helios::details::FreeFunctionTraits&lt; FunctionSignature &gt;", "structhelios_1_1details_1_1FreeFunctionTraits.html", null ],
    [ "helios::details::FreeFunctionTraits&lt; R(*)(Args...)&gt;", "structhelios_1_1details_1_1FreeFunctionTraits_3_01R_07_5_08_07Args_8_8_8_08_4.html", null ],
    [ "helios::mem::FreeListAllocatorOptions", "structhelios_1_1mem_1_1FreeListAllocatorOptions.html", null ],
    [ "helios::utils::FunctionalAdapterBase&lt; Derived &gt;", "classhelios_1_1utils_1_1FunctionalAdapterBase.html", null ],
    [ "helios::utils::FunctionalAdapterBase&lt; BasicQueryIter&lt; IsConst, Components... &gt; &gt;", "classhelios_1_1utils_1_1FunctionalAdapterBase.html", [
      [ "helios::ecs::BasicQueryIter< false, Components... >", "classhelios_1_1ecs_1_1BasicQueryIter.html", null ],
      [ "helios::ecs::BasicQueryIter< true, Components... >", "classhelios_1_1ecs_1_1BasicQueryIter.html", null ],
      [ "helios::ecs::BasicQueryIter< IsConst, Components >", "classhelios_1_1ecs_1_1BasicQueryIter.html", null ]
    ] ],
    [ "helios::utils::FunctionalAdapterBase&lt; BasicQueryWithEntityIter&lt; IsConst, Components... &gt; &gt;", "classhelios_1_1utils_1_1FunctionalAdapterBase.html", [
      [ "helios::ecs::BasicQueryWithEntityIter< false, Components... >", "classhelios_1_1ecs_1_1BasicQueryWithEntityIter.html", null ],
      [ "helios::ecs::BasicQueryWithEntityIter< true, Components... >", "classhelios_1_1ecs_1_1BasicQueryWithEntityIter.html", null ],
      [ "helios::ecs::BasicQueryWithEntityIter< IsConst, Components >", "classhelios_1_1ecs_1_1BasicQueryWithEntityIter.html", null ]
    ] ],
    [ "helios::utils::FunctionalAdapterBase&lt; ChainAdapter&lt; Iter1, Iter2 &gt; &gt;", "classhelios_1_1utils_1_1FunctionalAdapterBase.html", [
      [ "helios::utils::ChainAdapter< Iter1, Iter2 >", "classhelios_1_1utils_1_1ChainAdapter.html", null ]
    ] ],
    [ "helios::utils::FunctionalAdapterBase&lt; ConsumableMessageWrapperIter&lt; T &gt; &gt;", "classhelios_1_1utils_1_1FunctionalAdapterBase.html", [
      [ "helios::ecs::ConsumableMessageWrapperIter< T >", "classhelios_1_1ecs_1_1ConsumableMessageWrapperIter.html", null ]
    ] ],
    [ "helios::utils::FunctionalAdapterBase&lt; EnumerateAdapter&lt; Iter &gt; &gt;", "classhelios_1_1utils_1_1FunctionalAdapterBase.html", [
      [ "helios::utils::EnumerateAdapter< Iter >", "classhelios_1_1utils_1_1EnumerateAdapter.html", null ]
    ] ],
    [ "helios::utils::FunctionalAdapterBase&lt; FilterAdapter&lt; Iter, Pred &gt; &gt;", "classhelios_1_1utils_1_1FunctionalAdapterBase.html", [
      [ "helios::utils::FilterAdapter< Iter, Pred >", "classhelios_1_1utils_1_1FilterAdapter.html", null ]
    ] ],
    [ "helios::utils::FunctionalAdapterBase&lt; InspectAdapter&lt; Iter, Func &gt; &gt;", "classhelios_1_1utils_1_1FunctionalAdapterBase.html", [
      [ "helios::utils::InspectAdapter< Iter, Func >", "classhelios_1_1utils_1_1InspectAdapter.html", null ]
    ] ],
    [ "helios::utils::FunctionalAdapterBase&lt; MapAdapter&lt; Iter, Func &gt; &gt;", "classhelios_1_1utils_1_1FunctionalAdapterBase.html", [
      [ "helios::utils::MapAdapter< Iter, Func >", "classhelios_1_1utils_1_1MapAdapter.html", null ]
    ] ],
    [ "helios::utils::FunctionalAdapterBase&lt; MessageWrapperIter&lt; T &gt; &gt;", "classhelios_1_1utils_1_1FunctionalAdapterBase.html", [
      [ "helios::ecs::MessageWrapperIter< T >", "classhelios_1_1ecs_1_1MessageWrapperIter.html", null ]
    ] ],
    [ "helios::utils::FunctionalAdapterBase&lt; ReverseAdapter&lt; Iter &gt; &gt;", "classhelios_1_1utils_1_1FunctionalAdapterBase.html", [
      [ "helios::utils::ReverseAdapter< Iter >", "classhelios_1_1utils_1_1ReverseAdapter.html", null ]
    ] ],
    [ "helios::utils::FunctionalAdapterBase&lt; SkipAdapter&lt; Iter &gt; &gt;", "classhelios_1_1utils_1_1FunctionalAdapterBase.html", [
      [ "helios::utils::SkipAdapter< Iter >", "classhelios_1_1utils_1_1SkipAdapter.html", null ]
    ] ],
    [ "helios::utils::FunctionalAdapterBase&lt; SkipWhileAdapter&lt; Iter, Pred &gt; &gt;", "classhelios_1_1utils_1_1FunctionalAdapterBase.html", [
      [ "helios::utils::SkipWhileAdapter< Iter, Pred >", "classhelios_1_1utils_1_1SkipWhileAdapter.html", null ]
    ] ],
    [ "helios::utils::FunctionalAdapterBase&lt; SlideAdapter&lt; Iter &gt; &gt;", "classhelios_1_1utils_1_1FunctionalAdapterBase.html", [
      [ "helios::utils::SlideAdapter< Iter >", "classhelios_1_1utils_1_1SlideAdapter.html", null ]
    ] ],
    [ "helios::utils::FunctionalAdapterBase&lt; StepByAdapter&lt; Iter &gt; &gt;", "classhelios_1_1utils_1_1FunctionalAdapterBase.html", [
      [ "helios::utils::StepByAdapter< Iter >", "classhelios_1_1utils_1_1StepByAdapter.html", null ]
    ] ],
    [ "helios::utils::FunctionalAdapterBase&lt; StrideAdapter&lt; Iter &gt; &gt;", "classhelios_1_1utils_1_1FunctionalAdapterBase.html", [
      [ "helios::utils::StrideAdapter< Iter >", "classhelios_1_1utils_1_1StrideAdapter.html", null ]
    ] ],
    [ "helios::utils::FunctionalAdapterBase&lt; TakeAdapter&lt; Iter &gt; &gt;", "classhelios_1_1utils_1_1FunctionalAdapterBase.html", [
      [ "helios::utils::TakeAdapter< Iter >", "classhelios_1_1utils_1_1TakeAdapter.html", null ]
    ] ],
    [ "helios::utils::FunctionalAdapterBase&lt; TakeWhileAdapter&lt; Iter, Pred &gt; &gt;", "classhelios_1_1utils_1_1FunctionalAdapterBase.html", [
      [ "helios::utils::TakeWhileAdapter< Iter, Pred >", "classhelios_1_1utils_1_1TakeWhileAdapter.html", null ]
    ] ],
    [ "helios::utils::FunctionalAdapterBase&lt; ZipAdapter&lt; Iter1, Iter2 &gt; &gt;", "classhelios_1_1utils_1_1FunctionalAdapterBase.html", [
      [ "helios::utils::ZipAdapter< Iter1, Iter2 >", "classhelios_1_1utils_1_1ZipAdapter.html", null ]
    ] ],
    [ "helios::ecs::FunctionCmd&lt; F &gt;", "classhelios_1_1ecs_1_1FunctionCmd.html", null ],
    [ "helios::async::Future&lt; T &gt;", "classhelios_1_1async_1_1Future.html", null ],
    [ "helios::mem::GrowthPolicy", "structhelios_1_1mem_1_1GrowthPolicy.html", null ],
    [ "std::hash&lt; helios::BasicCStringView&lt; CharT, Traits &gt; &gt;", "structstd_1_1hash_3_01helios_1_1BasicCStringView_3_01CharT_00_01Traits_01_4_01_4.html", null ],
    [ "std::hash&lt; helios::container::BasicStaticString&lt; StrCapacity, CharT, Traits &gt; &gt;", "structstd_1_1hash_3_01helios_1_1container_1_1BasicStaticString_3_01StrCapacity_00_01CharT_00_01Traits_01_4_01_4.html", null ],
    [ "std::hash&lt; helios::ecs::ArchetypeId &gt;", "structstd_1_1hash_3_01helios_1_1ecs_1_1ArchetypeId_01_4.html", null ],
    [ "std::hash&lt; helios::ecs::ComponentTypeInfo &gt;", "structstd_1_1hash_3_01helios_1_1ecs_1_1ComponentTypeInfo_01_4.html", null ],
    [ "std::hash&lt; helios::ecs::Entity &gt;", "structstd_1_1hash_3_01helios_1_1ecs_1_1Entity_01_4.html", null ],
    [ "std::hash&lt; helios::ecs::SystemId &gt;", "structstd_1_1hash_3_01helios_1_1ecs_1_1SystemId_01_4.html", null ],
    [ "std::hash&lt; helios::utils::TypeId &gt;", "structstd_1_1hash_3_01helios_1_1utils_1_1TypeId_01_4.html", null ],
    [ "std::hash&lt; helios::utils::TypeIndex &gt;", "structstd_1_1hash_3_01helios_1_1utils_1_1TypeIndex_01_4.html", null ],
    [ "std::hash&lt; helios::Uuid &gt;", "structstd_1_1hash_3_01helios_1_1Uuid_01_4.html", null ],
    [ "helios::ecs::details::HasSystemParamCallOperatorHelper&lt; T &gt;", "structhelios_1_1ecs_1_1details_1_1HasSystemParamCallOperatorHelper.html", null ],
    [ "helios::ecs::InsertResourceCmd&lt; T &gt;", "classhelios_1_1ecs_1_1InsertResourceCmd.html", null ],
    [ "helios::utils::JoinAdapter&lt; Iter &gt;", "classhelios_1_1utils_1_1JoinAdapter.html", null ],
    [ "helios::app::Last", "structhelios_1_1app_1_1Last.html", null ],
    [ "helios::ecs::Local&lt; T &gt;", "classhelios_1_1ecs_1_1Local.html", null ],
    [ "helios::log::Logger", "classhelios_1_1log_1_1Logger.html", null ],
    [ "helios::app::MainStartup", "structhelios_1_1app_1_1MainStartup.html", null ],
    [ "helios::mem::FixedStackAllocator::Marker", "structhelios_1_1mem_1_1FixedStackAllocator_1_1Marker.html", null ],
    [ "helios::mem::StackAllocator::Marker", "structhelios_1_1mem_1_1StackAllocator_1_1Marker.html", null ],
    [ "helios::ecs::details::MemberFnArgs&lt; F &gt;", "structhelios_1_1ecs_1_1details_1_1MemberFnArgs.html", null ],
    [ "helios::ecs::details::MemberFnArgs&lt; R(*)(Args...)&gt;", "structhelios_1_1ecs_1_1details_1_1MemberFnArgs_3_01R_07_5_08_07Args_8_8_8_08_4.html", null ],
    [ "helios::ecs::details::MemberFnArgs&lt; R(Args...)&gt;", "structhelios_1_1ecs_1_1details_1_1MemberFnArgs_3_01R_07Args_8_8_8_08_4.html", null ],
    [ "helios::ecs::details::MemberFnArgs&lt; R(C::*)(Args...) const &gt;", "structhelios_1_1ecs_1_1details_1_1MemberFnArgs_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01const_01_4.html", null ],
    [ "helios::ecs::details::MemberFnArgs&lt; R(C::*)(Args...)&gt;", "structhelios_1_1ecs_1_1details_1_1MemberFnArgs_3_01R_07C_1_1_5_08_07Args_8_8_8_08_4.html", null ],
    [ "helios::details::MemberFunctionTraits&lt; FunctionSignature &gt;", "structhelios_1_1details_1_1MemberFunctionTraits.html", null ],
    [ "helios::details::MemberFunctionTraits&lt; R(C::*)(Args...) const &gt;", "structhelios_1_1details_1_1MemberFunctionTraits_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01const_01_4.html", null ],
    [ "helios::details::MemberFunctionTraits&lt; R(C::*)(Args...)&gt;", "structhelios_1_1details_1_1MemberFunctionTraits_3_01R_07C_1_1_5_08_07Args_8_8_8_08_4.html", null ],
    [ "std::pmr::memory_resource", null, [
      [ "helios::mem::ArenaAllocator", "classhelios_1_1mem_1_1ArenaAllocator.html", null ],
      [ "helios::mem::FixedArenaAllocator", "classhelios_1_1mem_1_1FixedArenaAllocator.html", null ],
      [ "helios::mem::FixedFreeListAllocator", "classhelios_1_1mem_1_1FixedFreeListAllocator.html", null ],
      [ "helios::mem::FixedPoolAllocator", "classhelios_1_1mem_1_1FixedPoolAllocator.html", null ],
      [ "helios::mem::FixedStackAllocator", "classhelios_1_1mem_1_1FixedStackAllocator.html", null ],
      [ "helios::mem::FrameAllocator< N >", "classhelios_1_1mem_1_1FrameAllocator.html", null ],
      [ "helios::mem::FreeListAllocator", "classhelios_1_1mem_1_1FreeListAllocator.html", null ],
      [ "helios::mem::PoolAllocator", "classhelios_1_1mem_1_1PoolAllocator.html", null ],
      [ "helios::mem::StackAllocator", "classhelios_1_1mem_1_1StackAllocator.html", null ]
    ] ],
    [ "helios::ecs::MessageManager", "classhelios_1_1ecs_1_1MessageManager.html", null ],
    [ "helios::ecs::MessageMetadata", "structhelios_1_1ecs_1_1MessageMetadata.html", null ],
    [ "helios::ecs::MessageQueue&lt; Allocator &gt;", "classhelios_1_1ecs_1_1MessageQueue.html", null ],
    [ "helios::ecs::MessageReaderBase&lt; Derived, T, IterType &gt;", "classhelios_1_1ecs_1_1MessageReaderBase.html", null ],
    [ "helios::ecs::MessageReaderBase&lt; ConsumableMessageReader&lt; T &gt;, T, ConsumableMessageWrapperIter&lt; T &gt; &gt;", "classhelios_1_1ecs_1_1MessageReaderBase.html", [
      [ "helios::ecs::ConsumableMessageReader< T >", "classhelios_1_1ecs_1_1ConsumableMessageReader.html", null ]
    ] ],
    [ "helios::ecs::MessageReaderBase&lt; MessageReader&lt; T &gt;, T, MessageWrapperIter&lt; T &gt; &gt;", "classhelios_1_1ecs_1_1MessageReaderBase.html", [
      [ "helios::ecs::MessageReader< T >", "classhelios_1_1ecs_1_1MessageReader.html", null ]
    ] ],
    [ "helios::ecs::MessageWrapper&lt; T &gt;", "classhelios_1_1ecs_1_1MessageWrapper.html", null ],
    [ "helios::container::MultiTypeMap&lt; Storage, Allocator &gt;", "classhelios_1_1container_1_1MultiTypeMap.html", null ],
    [ "helios::app::Plugin", "classhelios_1_1app_1_1Plugin.html", null ],
    [ "helios::app::PluginTypeExport", "structhelios_1_1app_1_1PluginTypeExport.html", null ],
    [ "helios::mem::PoolAllocatorOptions", "structhelios_1_1mem_1_1PoolAllocatorOptions.html", null ],
    [ "helios::app::PostShutdown", "structhelios_1_1app_1_1PostShutdown.html", null ],
    [ "helios::app::PostStartup", "structhelios_1_1app_1_1PostStartup.html", null ],
    [ "helios::app::PostUpdate", "structhelios_1_1app_1_1PostUpdate.html", null ],
    [ "helios::app::PreShutdown", "structhelios_1_1app_1_1PreShutdown.html", null ],
    [ "helios::app::PreStartup", "structhelios_1_1app_1_1PreStartup.html", null ],
    [ "helios::app::PreUpdate", "structhelios_1_1app_1_1PreUpdate.html", null ],
    [ "helios::profile::Profiler", "classhelios_1_1profile_1_1Profiler.html", null ],
    [ "helios::utils::RandomGenerator&lt; Engine &gt;", "classhelios_1_1utils_1_1RandomGenerator.html", null ],
    [ "helios::mem::RcFromThis&lt; Derived &gt;", "classhelios_1_1mem_1_1RcFromThis.html", null ],
    [ "helios::mem::RefCounted&lt; Derived, Allocator &gt;", "classhelios_1_1mem_1_1RefCounted.html", null ],
    [ "helios::ecs::details::RegisterQueryAccess&lt; Tuple &gt;", "structhelios_1_1ecs_1_1details_1_1RegisterQueryAccess.html", null ],
    [ "helios::ecs::details::RegisterQueryAccess&lt; std::tuple&lt; Cs... &gt; &gt;", "structhelios_1_1ecs_1_1details_1_1RegisterQueryAccess_3_01std_1_1tuple_3_01Cs_8_8_8_01_4_01_4.html", null ],
    [ "helios::ecs::RemoveComponentsCmd&lt; Ts &gt;", "classhelios_1_1ecs_1_1RemoveComponentsCmd.html", null ],
    [ "helios::ecs::RemoveResourceCmd&lt; T &gt;", "structhelios_1_1ecs_1_1RemoveResourceCmd.html", null ],
    [ "helios::ecs::Res&lt; T &gt;", "classhelios_1_1ecs_1_1Res.html", null ],
    [ "helios::ecs::ResourceConflictInfo", "structhelios_1_1ecs_1_1ResourceConflictInfo.html", null ],
    [ "helios::ecs::ResourceInsertedMsg&lt; T &gt;", "structhelios_1_1ecs_1_1ResourceInsertedMsg.html", null ],
    [ "helios::ecs::ResourceManager", "classhelios_1_1ecs_1_1ResourceManager.html", null ],
    [ "helios::ecs::ResourceRemovedMsg&lt; T &gt;", "structhelios_1_1ecs_1_1ResourceRemovedMsg.html", null ],
    [ "helios::ecs::RunConditionStorage", "structhelios_1_1ecs_1_1RunConditionStorage.html", null ],
    [ "helios::ecs::Schedule", "classhelios_1_1ecs_1_1Schedule.html", null ],
    [ "helios::ecs::ScheduleError", "structhelios_1_1ecs_1_1ScheduleError.html", null ],
    [ "helios::ecs::ScheduleOrdering", "classhelios_1_1ecs_1_1ScheduleOrdering.html", null ],
    [ "helios::app::Scheduler", "classhelios_1_1app_1_1Scheduler.html", null ],
    [ "helios::ecs::Scheduler", "classhelios_1_1ecs_1_1Scheduler.html", null ],
    [ "helios::ecs::ScheduleSettings", "structhelios_1_1ecs_1_1ScheduleSettings.html", null ],
    [ "helios::ecs::ScheduleSystemId", "structhelios_1_1ecs_1_1ScheduleSystemId.html", null ],
    [ "helios::ecs::ScheduleSystemMetadata", "structhelios_1_1ecs_1_1ScheduleSystemMetadata.html", null ],
    [ "helios::profile::ScopedZone", "classhelios_1_1profile_1_1ScopedZone.html", null ],
    [ "helios::app::Shutdown", "structhelios_1_1app_1_1Shutdown.html", null ],
    [ "helios::app::ShutdownStage", "structhelios_1_1app_1_1ShutdownStage.html", null ],
    [ "helios::utils::SlideView&lt; Iter &gt;", "classhelios_1_1utils_1_1SlideView.html", null ],
    [ "helios::ecs::SparseComponentStorage&lt; T &gt;", "classhelios_1_1ecs_1_1SparseComponentStorage.html", null ],
    [ "helios::container::SparseSet&lt; T, IndexType, Allocator &gt;", "classhelios_1_1container_1_1SparseSet.html", null ],
    [ "helios::ecs::ComponentManager::SparseStorageEntry", "structhelios_1_1ecs_1_1ComponentManager_1_1SparseStorageEntry.html", null ],
    [ "helios::mem::StackAllocatorOptions", "structhelios_1_1mem_1_1StackAllocatorOptions.html", null ],
    [ "helios::Stacktrace", "classhelios_1_1Stacktrace.html", null ],
    [ "helios::StacktraceConfig", "structhelios_1_1StacktraceConfig.html", null ],
    [ "helios::ecs::StageOrdering", "classhelios_1_1ecs_1_1StageOrdering.html", null ],
    [ "helios::app::Startup", "structhelios_1_1app_1_1Startup.html", null ],
    [ "helios::app::StartupStage", "structhelios_1_1app_1_1StartupStage.html", null ],
    [ "helios::utils::StringEqual", "structhelios_1_1utils_1_1StringEqual.html", null ],
    [ "helios::utils::StringHash", "structhelios_1_1utils_1_1StringHash.html", null ],
    [ "helios::app::SubApp", "classhelios_1_1app_1_1SubApp.html", null ],
    [ "helios::async::SubTaskGraph", "classhelios_1_1async_1_1SubTaskGraph.html", null ],
    [ "helios::ecs::SystemGroupHandle", "classhelios_1_1ecs_1_1SystemGroupHandle.html", null ],
    [ "helios::ecs::SystemHandle", "classhelios_1_1ecs_1_1SystemHandle.html", null ],
    [ "helios::ecs::SystemId", "structhelios_1_1ecs_1_1SystemId.html", null ],
    [ "helios::ecs::SystemLocalData", "structhelios_1_1ecs_1_1SystemLocalData.html", null ],
    [ "helios::ecs::SystemLocalDataOptions", "structhelios_1_1ecs_1_1SystemLocalDataOptions.html", null ],
    [ "helios::ecs::SystemParamTraits&lt; T &gt;", "structhelios_1_1ecs_1_1SystemParamTraits.html", null ],
    [ "helios::ecs::SystemParamTraits&lt; AsyncMessageReader&lt; T &gt; &gt;", "structhelios_1_1ecs_1_1SystemParamTraits_3_01AsyncMessageReader_3_01T_01_4_01_4.html", null ],
    [ "helios::ecs::SystemParamTraits&lt; AsyncMessageWriter&lt; T &gt; &gt;", "structhelios_1_1ecs_1_1SystemParamTraits_3_01AsyncMessageWriter_3_01T_01_4_01_4.html", null ],
    [ "helios::ecs::SystemParamTraits&lt; BasicMessageWriter&lt; T, Allocator &gt; &gt;", "structhelios_1_1ecs_1_1SystemParamTraits_3_01BasicMessageWriter_3_01T_00_01Allocator_01_4_01_4.html", null ],
    [ "helios::ecs::SystemParamTraits&lt; Commands &gt;", "structhelios_1_1ecs_1_1SystemParamTraits_3_01Commands_01_4.html", null ],
    [ "helios::ecs::SystemParamTraits&lt; ConsumableMessageReader&lt; T &gt; &gt;", "structhelios_1_1ecs_1_1SystemParamTraits_3_01ConsumableMessageReader_3_01T_01_4_01_4.html", null ],
    [ "helios::ecs::SystemParamTraits&lt; Local&lt; const T &gt; &gt;", "structhelios_1_1ecs_1_1SystemParamTraits_3_01Local_3_01const_01T_01_4_01_4.html", null ],
    [ "helios::ecs::SystemParamTraits&lt; Local&lt; T &gt; &gt;", "structhelios_1_1ecs_1_1SystemParamTraits_3_01Local_3_01T_01_4_01_4.html", null ],
    [ "helios::ecs::SystemParamTraits&lt; MessageReader&lt; T &gt; &gt;", "structhelios_1_1ecs_1_1SystemParamTraits_3_01MessageReader_3_01T_01_4_01_4.html", null ],
    [ "helios::ecs::SystemParamTraits&lt; MessageWriter&lt; T &gt; &gt;", "structhelios_1_1ecs_1_1SystemParamTraits_3_01MessageWriter_3_01T_01_4_01_4.html", null ],
    [ "helios::ecs::SystemParamTraits&lt; Query&lt; Args... &gt; &gt;", "structhelios_1_1ecs_1_1SystemParamTraits_3_01Query_3_01Args_8_8_8_01_4_01_4.html", null ],
    [ "helios::ecs::SystemParamTraits&lt; Res&lt; const T &gt; &gt;", "structhelios_1_1ecs_1_1SystemParamTraits_3_01Res_3_01const_01T_01_4_01_4.html", null ],
    [ "helios::ecs::SystemParamTraits&lt; Res&lt; T &gt; &gt;", "structhelios_1_1ecs_1_1SystemParamTraits_3_01Res_3_01T_01_4_01_4.html", null ],
    [ "helios::ecs::SystemParamTraits&lt; std::optional&lt; Local&lt; const T &gt; &gt; &gt;", "structhelios_1_1ecs_1_1SystemParamTraits_3_01std_1_1optional_3_01Local_3_01const_01T_01_4_01_4_01_4.html", null ],
    [ "helios::ecs::SystemParamTraits&lt; std::optional&lt; Local&lt; T &gt; &gt; &gt;", "structhelios_1_1ecs_1_1SystemParamTraits_3_01std_1_1optional_3_01Local_3_01T_01_4_01_4_01_4.html", null ],
    [ "helios::ecs::SystemParamTraits&lt; std::optional&lt; Res&lt; const T &gt; &gt; &gt;", "structhelios_1_1ecs_1_1SystemParamTraits_3_01std_1_1optional_3_01Res_3_01const_01T_01_4_01_4_01_4.html", null ],
    [ "helios::ecs::SystemParamTraits&lt; std::optional&lt; Res&lt; T &gt; &gt; &gt;", "structhelios_1_1ecs_1_1SystemParamTraits_3_01std_1_1optional_3_01Res_3_01T_01_4_01_4_01_4.html", null ],
    [ "helios::ecs::SystemParamTraits&lt; WorldView &gt;", "structhelios_1_1ecs_1_1SystemParamTraits_3_01WorldView_01_4.html", null ],
    [ "helios::ecs::SystemSet", "classhelios_1_1ecs_1_1SystemSet.html", null ],
    [ "helios::ecs::SystemSetHandle", "classhelios_1_1ecs_1_1SystemSetHandle.html", null ],
    [ "helios::ecs::SystemSetId", "structhelios_1_1ecs_1_1SystemSetId.html", null ],
    [ "helios::ecs::SystemStorage", "structhelios_1_1ecs_1_1SystemStorage.html", null ],
    [ "helios::async::Task", "classhelios_1_1async_1_1Task.html", null ],
    [ "helios::async::TaskGraph", "classhelios_1_1async_1_1TaskGraph.html", null ],
    [ "helios::utils::Timer&lt; Clock &gt;", "classhelios_1_1utils_1_1Timer.html", null ],
    [ "helios::ecs::anonymous_namespace{scheduler.cpp}::TopoNode", "structhelios_1_1ecs_1_1anonymous__namespace_02scheduler_8cpp_03_1_1TopoNode.html", null ],
    [ "std::true_type", null, [
      [ "helios::utils::details::UniqueTypesHelper< T, Rest... >", "structhelios_1_1utils_1_1details_1_1UniqueTypesHelper_3_01T_00_01Rest_8_8_8_01_4.html", null ],
      [ "helios::utils::details::UniqueTypesHelper<... >", "structhelios_1_1utils_1_1details_1_1UniqueTypesHelper.html", null ]
    ] ],
    [ "helios::ecs::TryAddComponentsCmd&lt; Ts &gt;", "classhelios_1_1ecs_1_1TryAddComponentsCmd.html", null ],
    [ "helios::ecs::TryDestroyEntitiesCmd&lt; Alloc &gt;", "classhelios_1_1ecs_1_1TryDestroyEntitiesCmd.html", null ],
    [ "helios::ecs::TryDestroyEntityCmd", "classhelios_1_1ecs_1_1TryDestroyEntityCmd.html", null ],
    [ "helios::ecs::TryInsertResourceCmd&lt; T &gt;", "classhelios_1_1ecs_1_1TryInsertResourceCmd.html", null ],
    [ "helios::ecs::TryRemoveComponentsCmd&lt; Ts &gt;", "classhelios_1_1ecs_1_1TryRemoveComponentsCmd.html", null ],
    [ "helios::ecs::TryRemoveResourceCmd&lt; T &gt;", "structhelios_1_1ecs_1_1TryRemoveResourceCmd.html", null ],
    [ "helios::details::TupleToFunctionSignature&lt; T &gt;", "structhelios_1_1details_1_1TupleToFunctionSignature.html", null ],
    [ "helios::details::TupleToFunctionSignature&lt; std::tuple&lt; R, Args... &gt; &gt;", "structhelios_1_1details_1_1TupleToFunctionSignature_3_01std_1_1tuple_3_01R_00_01Args_8_8_8_01_4_01_4.html", null ],
    [ "helios::container::TypedBuffer&lt; Allocator &gt;", "classhelios_1_1container_1_1TypedBuffer.html", null ],
    [ "helios::container::TypedBufferArray&lt; Allocator &gt;", "classhelios_1_1container_1_1TypedBufferArray.html", null ],
    [ "helios::utils::TypeId", "classhelios_1_1utils_1_1TypeId.html", null ],
    [ "helios::utils::TypeIndex", "classhelios_1_1utils_1_1TypeIndex.html", null ],
    [ "helios::app::Update", "structhelios_1_1app_1_1Update.html", null ],
    [ "helios::app::UpdateStage", "structhelios_1_1app_1_1UpdateStage.html", null ],
    [ "helios::Uuid", "classhelios_1_1Uuid.html", null ],
    [ "helios::UuidGenerator", "classhelios_1_1UuidGenerator.html", null ],
    [ "helios::ecs::World", "classhelios_1_1ecs_1_1World.html", null ],
    [ "helios::ecs::WorldCmdBuffer&lt; Allocator &gt;", "classhelios_1_1ecs_1_1WorldCmdBuffer.html", null ],
    [ "helios::ecs::WorldView", "classhelios_1_1ecs_1_1WorldView.html", null ],
    [ "helios::profile::ZoneSpec", "structhelios_1_1profile_1_1ZoneSpec.html", null ]
];