#ifndef HELIOS_PLATFORM_PLATFORM_H
#define HELIOS_PLATFORM_PLATFORM_H

#include <helios/platform/detail/platform.h>

#ifdef HELIOS_C_BUILDING
#define HELIOS_C_API HELIOS_DETAIL_EXPORT
#elif defined(HELIOS_C_STATIC)
#define HELIOS_C_API
#else
#define HELIOS_C_API HELIOS_DETAIL_IMPORT
#endif

#define HELIOS_C_EXPORT HELIOS_DETAIL_EXPORT
#define HELIOS_C_DEBUG_BREAK() HELIOS_DETAIL_DEBUG_BREAK()
#define HELIOS_C_PAUSE_CPU() HELIOS_DETAIL_PAUSE_CPU()

#endif
