"""Emit a CMake module list from a resolution."""

from __future__ import annotations

from .resolve import Resolution


def _cmake_string(value: str) -> str:
    return '"' + value.replace("\\", "/").replace('"', '\\"') + '"'


def _cmake_list(values: list[str]) -> str:
    return " ".join(_cmake_string(value) for value in values)


def emit_cmake(resolution: Resolution, *, user_only: bool = False) -> str:
    lines = [
        "# Generated by helios_modules. Do not edit.",
        "include_guard(GLOBAL)",
        "",
    ]
    for warning in resolution.warnings:
        lines.append(f"message(WARNING {_cmake_string(warning)})")
    for note in resolution.status:
        lines.append(f"message(STATUS {_cmake_string(note)})")
    for dep_name, because in resolution.forced:
        option = "HELIOS_BUILD_" + dep_name.upper()
        lines.append(
            f"set({option} ON CACHE BOOL {_cmake_string('Required by ' + because)} FORCE)"
        )
    lines.append("")

    buildable = []
    for module in resolution.modules:
        if user_only and module.origin != "user":
            continue
        if module.fixed:
            continue
        if module.enabled:
            buildable.append(module)
        lines.append("helios_declare_module(")
        lines.append(f"    NAME {_cmake_string(module.name)}")
        lines.append(f"    PATH {_cmake_string(str(module.path))}")
        lines.append(f"    TARGET {_cmake_string(module.target)}")
        if module.alias:
            lines.append(f"    ALIAS {_cmake_string(module.alias)}")
        lines.append(f"    VERSION {_cmake_string(module.version)}")
        lines.append(f"    DESCRIPTION {_cmake_string(module.description)}")
        lines.append(f"    LANGUAGES {_cmake_list(module.languages)}")
        lines.append(f"    ORIGIN {_cmake_string(module.origin)}")
        lines.append(f"    C_API {'ON' if module.c_api else 'OFF'}")
        lines.append(f"    DEFAULT {'ON' if module.default else 'OFF'}")
        if module.deps_public:
            lines.append(f"    DEPENDS_PUBLIC {_cmake_list(module.deps_public)}")
        if module.deps_private:
            lines.append(f"    DEPENDS_PRIVATE {_cmake_list(module.deps_private)}")
        if module.opt_public:
            lines.append(f"    OPTIONAL_PUBLIC {_cmake_list(module.opt_public)}")
        if module.opt_private:
            lines.append(f"    OPTIONAL_PRIVATE {_cmake_list(module.opt_private)}")
        if module.implements:
            lines.append(f"    IMPLEMENTS {_cmake_list(module.implements)}")
        if module.backend_wins:
            lines.append(f"    BACKEND_WINS {_cmake_list(module.backend_wins)}")
        lines.append(")")
        for feature in module.features:
            lines.append("helios_declare_feature(")
            lines.append(f"    MODULE {_cmake_string(module.name)}")
            lines.append(f"    NAME {_cmake_string(feature.name)}")
            lines.append(f"    OPTION {_cmake_string(module.feature_option(feature))}")
            lines.append(f"    DEFAULT {'ON' if feature.default else 'OFF'}")
            lines.append(f"    ABI {'ON' if feature.abi else 'OFF'}")
            lines.append(f"    DESCRIPTION {_cmake_string(feature.description)}")
            lines.append(")")
        lines.append("")

    names = [module.name for module in buildable]
    # Preserve topological order from resolution.enabled.
    ordered = [name for name in resolution.enabled if name in names]
    lines.append(f"set(HELIOS_ENABLED_MODULES {_cmake_list(ordered)})")
    for tag, winner in sorted(resolution.backends.items()):
        lines.append(
            f'set(HELIOS_BACKEND_{tag.upper()} {_cmake_string(winner)} CACHE INTERNAL "")'
        )
    lines.append("")
    return "\n".join(lines) + "\n"


def emit_json(resolution: Resolution) -> dict:
    return {
        "modules": [module.to_json() for module in resolution.modules],
        "enabled": resolution.enabled,
        "backends": resolution.backends,
        "warnings": resolution.warnings,
    }
