#pragma once

#if defined(HELIOS_ASYNC_ENABLE_PROFILE) && \
    defined(HELIOS_MODULE_PROFILE_AVAILABLE)
#define HELIOS_ENABLE_PROFILE
#include <helios/profile/macros.hpp>

#define HELIOS_ASYNC_PROFILE_SCOPE() HELIOS_PROFILE_SCOPE()
#define HELIOS_ASYNC_PROFILE_SCOPE_N(name) HELIOS_PROFILE_SCOPE_N(name)
#define HELIOS_ASYNC_PROFILE_SCOPE_IF(name, active) \
  HELIOS_PROFILE_SCOPE_IF(name, active)
#define HELIOS_ASYNC_PROFILE_ZONE_VALUE(value) HELIOS_PROFILE_ZONE_VALUE(value)
#define HELIOS_ASYNC_PROFILE_ZONE_NAME(name) HELIOS_PROFILE_ZONE_NAME(name)
#define HELIOS_ASYNC_PROFILE_SET_THREAD_NAME(name) \
  HELIOS_PROFILE_SET_THREAD_NAME(name)

#undef HELIOS_ENABLE_PROFILE

#else

#define HELIOS_ASYNC_PROFILE_SCOPE()
#define HELIOS_ASYNC_PROFILE_SCOPE_N(name)
#define HELIOS_ASYNC_PROFILE_SCOPE_IF(name, active)
#define HELIOS_ASYNC_PROFILE_ZONE_VALUE(value)
#define HELIOS_ASYNC_PROFILE_ZONE_NAME(name)
#define HELIOS_ASYNC_PROFILE_SET_THREAD_NAME(name)

#endif
