[module]
name = "helios_core"
version = "0.1.0"
description = "Core engine module providing asserts, UUID, and other core functionality"
languages = ["cpp"]
default = true
implements = []
c_api = true

[build]
system = "cmake"

[dependencies]
public = ["helios_compiler", "helios_platform", "helios_utils"]
private = []

[dependencies.optional]
public = []
private = []
