#pragma once

#include <iostream>
#include <memory>
#include <utility>
#include <algorithm>
#include <random>
#include <functional>
#include <type_traits>
#include <filesystem>
#include <format>
#include <ranges>
#include <thread>
#include <mutex>
#include <shared_mutex>
#include <condition_variable>
#include <future>
#include <typeindex>
#include <optional>
#include <source_location>
#include <execution>
#include <expected>
#include <cstdint>
#include <cstdlib> 
#include <sstream>
#include <string>
#include <string_view>
#include <array>
#include <vector>
#include <deque>
#include <queue>
#include <set>
#include <bitset>
#include <map>
#include <unordered_map>
#include <span>

#include "HeliosEngine/Core.h"
#include "HeliosEngine/Log.h"
#include "HeliosEngine/Input.h"
#include "HeliosEngine/PathManager.h"
#include "HeliosEngine/KeyCodes.h"
#include "HeliosEngine/MouseButtonCodes.h"
#include "HeliosEngine/Timestep.h"
#include "HeliosEngine/UUID.h"

#include "HeliosEngine/Utils/Filesystem.h"
#include "HeliosEngine/Utils/Profiler.h"
#include "HeliosEngine/Utils/Random.h"
#include "HeliosEngine/Utils/ThreadPool.h"
#include "HeliosEngine/Utils/Timer.h"

#include "HeliosEngine/Events/Event.h"
#include "HeliosEngine/Events/ApplicationEvent.h"
#include "HeliosEngine/Events/KeyEvent.h"
#include "HeliosEngine/Events/MouseEvent.h"