[module]
name = "helios_window"
version = "0.1.0"
description = "Window ECS contract module"
languages = ["cpp"]
default = true
implements = []
c_api = true

[build]
system = "cmake"

[dependencies]
public = ["helios_app", "helios_compiler", "helios_ecs", "helios_memory", "helios_platform"]
private = []

[dependencies.optional]
public = []
private = []
