#ifndef HELIOS_PLATFORM_PLATFORM_H
#define HELIOS_PLATFORM_PLATFORM_H

#include <helios/platform/detail/platform.h>

#ifdef HELIOS_BUILD_SHARED
#define HELIOS_API HELIOS_DETAIL_EXPORT
#else
#define HELIOS_API HELIOS_DETAIL_IMPORT
#endif

#define HELIOS_EXPORT HELIOS_DETAIL_EXPORT
#define HELIOS_DEBUG_BREAK() HELIOS_DETAIL_DEBUG_BREAK()
#define HELIOS_PAUSE_CPU() HELIOS_DETAIL_PAUSE_CPU()

#endif
