# Runs scripts/helios_modules.py and builds the generated module list.

include_guard(GLOBAL)

function(helios_configure_module_graph)
  find_package(Python3 3.11 REQUIRED COMPONENTS Interpreter)

  file(GLOB _src_manifests CONFIGURE_DEPENDS
      "${HELIOS_ROOT_DIR}/src/*/module.toml")
  if(NOT HELIOS_MODULES_LAUNCHER)
    set(HELIOS_MODULES_LAUNCHER "${HELIOS_ROOT_DIR}/scripts/helios_modules.py")
  endif()
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
      ${_src_manifests}
      "${HELIOS_MODULES_LAUNCHER}")

  helios_get_extra_module_dirs(_extras)
  foreach(_dir IN LISTS _extras)
    file(GLOB _extra_manifests CONFIGURE_DEPENDS
        "${_dir}/module.toml"
        "${_dir}/*/module.toml")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${_extra_manifests})
  endforeach()

  set(_out_dir "${CMAKE_BINARY_DIR}/helios")
  file(MAKE_DIRECTORY "${_out_dir}")
  set(_cmd
      "${Python3_EXECUTABLE}"
      "${HELIOS_MODULES_LAUNCHER}"
      resolve
      --root "${HELIOS_ROOT_DIR}/src"
      --cmake-out "${_out_dir}/Modules.cmake"
      --json-out "${_out_dir}/modules.json"
  )
  foreach(_dir IN LISTS _extras)
    list(APPEND _cmd --extra-dir "${_dir}")
  endforeach()
  if(HELIOS_BUILD_ALL_MODULES)
    list(APPEND _cmd --set "HELIOS_BUILD_ALL_MODULES=ON")
  endif()
  if(HELIOS_BUILD_C_API)
    list(APPEND _cmd --set "HELIOS_BUILD_C_API=ON")
  else()
    list(APPEND _cmd --set "HELIOS_BUILD_C_API=OFF")
  endif()

  get_cmake_property(_cache_vars CACHE_VARIABLES)
  set(_skip HELIOS_BUILD_TESTS HELIOS_BUILD_EXAMPLES HELIOS_BUILD_DOCS HELIOS_BUILD_C_API HELIOS_BUILD_ALL_MODULES)
  foreach(_var IN LISTS _cache_vars)
    if(_var MATCHES "^HELIOS_BUILD_" AND NOT _var IN_LIST _skip AND NOT _var MATCHES "^HELIOS_BUILD_OPTION_")
      list(APPEND _cmd --set "${_var}=${${_var}}")
    endif()
  endforeach()

  execute_process(
      COMMAND ${_cmd}
      RESULT_VARIABLE _rc
      OUTPUT_VARIABLE _stdout
      ERROR_VARIABLE _stderr
  )
  if(NOT _rc EQUAL 0)
    message(FATAL_ERROR
        "helios_modules resolve failed (${_rc})\n${_stdout}\n${_stderr}")
  endif()
  include("${_out_dir}/Modules.cmake")
  helios_write_alias_file()
  helios_build_declared_modules()
  helios_flush_deferred_module_links()
endfunction()

# Records engine module aliases for an installed package. find_package loads
# this file so a consumer can link helios::app rather than helios::helios_app.
function(helios_write_alias_file)
  get_property(_registered GLOBAL PROPERTY HELIOS_REGISTERED_MODULES)
  set(_body "# Generated by Helios. Maps a module name to its alias.\n")
  foreach(_name IN LISTS _registered)
    string(TOUPPER "${_name}" _upper)
    if(NOT "${${_upper}_ORIGIN}" STREQUAL "engine")
      continue()
    endif()
    if(NOT DEFINED ${_upper}_ALIAS OR "${${_upper}_ALIAS}" STREQUAL "")
      continue()
    endif()
    string(APPEND _body "set(${_upper}_ALIAS \"${${_upper}_ALIAS}\" CACHE INTERNAL \"\")\n")
  endforeach()
  file(WRITE "${CMAKE_BINARY_DIR}/helios/HeliosAliases.cmake" "${_body}")
endfunction()
